ResolutionGraph {
    root_package_path: "tests/test_sources/resolution/multiple_deps_rename",
    build_options: BuildConfig {
        dev_mode: true,
        test_mode: false,
        generate_docs: false,
        generate_abis: false,
        install_dir: Some(
            "ELIDED_FOR_TEST",
        ),
        force_recompilation: false,
    },
    root_package: SourceManifest {
        package: PackageInfo {
            name: "test",
            version: (
                0,
                0,
                0,
            ),
            authors: [],
            license: None,
        },
        addresses: None,
        dev_address_assignments: None,
        build: None,
        dependencies: {
            "C": Dependency {
                local: "./deps_only/C",
                subst: Some(
                    {
                        "CA": RenameFrom(
                            "A",
                        ),
                    },
                ),
                version: None,
                digest: None,
                git_info: None,
            },
            "D": Dependency {
                local: "./deps_only/D",
                subst: Some(
                    {
                        "DA": RenameFrom(
                            "A",
                        ),
                    },
                ),
                version: None,
                digest: None,
                git_info: None,
            },
        },
        dev_dependencies: {},
    },
    graph: {
        "test": [
            (
                "C",
                Outgoing,
            ),
            (
                "D",
                Outgoing,
            ),
        ],
        "C": [
            (
                "test",
                Incoming,
            ),
        ],
        "D": [
            (
                "test",
                Incoming,
            ),
        ],
    },
    package_table: {
        "C": ResolutionPackage {
            resolution_graph_index: "C",
            source_package: SourceManifest {
                package: PackageInfo {
                    name: "C",
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: Some(
                    {
                        "A": Some(
                            00000000000000000000000000000001,
                        ),
                    },
                ),
                dev_address_assignments: None,
                build: None,
                dependencies: {},
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {},
            resolution_table: {
                "A": 00000000000000000000000000000001,
            },
            source_digest: "ELIDED_FOR_TEST",
        },
        "D": ResolutionPackage {
            resolution_graph_index: "D",
            source_package: SourceManifest {
                package: PackageInfo {
                    name: "D",
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: Some(
                    {
                        "A": Some(
                            00000000000000000000000000000002,
                        ),
                    },
                ),
                dev_address_assignments: None,
                build: None,
                dependencies: {},
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {},
            resolution_table: {
                "A": 00000000000000000000000000000002,
            },
            source_digest: "ELIDED_FOR_TEST",
        },
        "test": ResolutionPackage {
            resolution_graph_index: "test",
            source_package: SourceManifest {
                package: PackageInfo {
                    name: "test",
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: None,
                dev_address_assignments: None,
                build: None,
                dependencies: {
                    "C": Dependency {
                        local: "./deps_only/C",
                        subst: Some(
                            {
                                "CA": RenameFrom(
                                    "A",
                                ),
                            },
                        ),
                        version: None,
                        digest: None,
                        git_info: None,
                    },
                    "D": Dependency {
                        local: "./deps_only/D",
                        subst: Some(
                            {
                                "DA": RenameFrom(
                                    "A",
                                ),
                            },
                        ),
                        version: None,
                        digest: None,
                        git_info: None,
                    },
                },
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {
                "CA": (
                    "C",
                    "A",
                ),
                "DA": (
                    "D",
                    "A",
                ),
            },
            resolution_table: {
                "CA": 00000000000000000000000000000001,
                "DA": 00000000000000000000000000000002,
            },
            source_digest: "ELIDED_FOR_TEST",
        },
    },
}
