processed 9 tasks

task 1 'run'. lines 158-170:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 2 'run'. lines 172-187:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 3 'run'. lines 189-220:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 4 'run'. lines 222-244:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 5 'run'. lines 246-264:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 6 'run'. lines 266-278:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 7 'run'. lines 280-303:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 8 'run'. lines 306-327:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}
