processed 9 tasks

task 1 'run'. lines 147-158:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 2 'run'. lines 160-174:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 3 'run'. lines 176-206:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 4 'run'. lines 208-229:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 5 'run'. lines 231-248:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 6 'run'. lines 250-261:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 7 'run'. lines 263-285:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 8 'run'. lines 288-308:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}
