Command `sandbox publish --override-ordering A -v`:
Found 2 modules
Invalid multi-module publishing: VMError with status LINKER_ERROR at location UNDEFINED and message Cannot find ModuleId { address: 00000000000000000000000000000002, name: Identifier("B") } in data cache
Command `sandbox publish --override-ordering B -v`:
Found 2 modules
Invalid multi-module publishing: VMError with status LINKER_ERROR at location UNDEFINED and message Cannot find ModuleId { address: 00000000000000000000000000000002, name: Identifier("A") } in data cache
Command `sandbox publish --override-ordering B --override-ordering A -v`:
Found 2 modules
Invalid multi-module publishing: VMError with status LINKER_ERROR at location UNDEFINED and message Cannot find ModuleId { address: 00000000000000000000000000000002, name: Identifier("A") } in data cache
Command `sandbox publish --override-ordering A --override-ordering B -v`:
Found 2 modules
Publishing a new module 00000000000000000000000000000002::A (wrote 89 bytes)
Publishing a new module 00000000000000000000000000000002::B (wrote 97 bytes)
Wrote 186 bytes of module ID's and code
Command `sandbox view storage/0x00000000000000000000000000000002/modules/A.mv`:
// Move bytecode v4
module 2.A {


public(friend) foo() {
B0:
	0: Ret
}
}
Command `sandbox view storage/0x00000000000000000000000000000002/modules/B.mv`:
// Move bytecode v4
module 2.B {


bar() {
B0:
	0: Call[1](foo())
	1: Ret
}
}
