processed 2 tasks

task 0 'publish'. lines 1-10:
Error: Unable to publish module '00000000000000000000000000000001::M'. Got VMError: {
    major_status: CONSTRAINT_NOT_SATISFIED,
    sub_status: None,
    location: 0x1::M,
    indices: [(Signature, 1), (FunctionDefinition, 0)],
    offsets: [],
}

task 1 'publish'. lines 12-22:
Error: Unable to publish module '00000000000000000000000000000001::M2'. Got VMError: {
    major_status: CONSTRAINT_NOT_SATISFIED,
    sub_status: None,
    location: 0x1::M2,
    indices: [(Signature, 1), (FunctionDefinition, 0)],
    offsets: [],
}
