---
server_config:
  api_path_base: ""
metrics_server_config:
  listen_port: 9106
bypasser_configs:
  - type: "AuthToken"
    file: "/tmp/auth_tokens.txt"
checker_configs: []
funder_config:
  type: "MintFunder"
  node_url: "http://127.0.0.1:8080"
  chain_id: 4
  wait_for_transactions: true
  assets:
    apt:
      do_not_delegate: false
      key_file_path: "/tmp/mint.key"
      mint_account_address: "0xA550C18"
      maximum_amount: 0
      maximum_amount_with_bypass: 10000
handler_config:
  use_helpful_errors: true
  return_rejections_early: false
