[package]
name = "aptos-keyless-validation"
description = "Validation of the keyless authenticators carried by a transaction."
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-crypto = { workspace = true }
aptos-types = { workspace = true }
ark-bn254 = { workspace = true }
ark-groth16 = { workspace = true }
hex = { workspace = true }
move-core-types = { workspace = true }
thiserror = { workspace = true }
