{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "owner", "query": { "query": "label_values(owner)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ValidatorSet",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, diem_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Current Round",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, diem_consensus_current_round)"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(diem_consensus_last_committed_version[1m])"
    }
   ]
  },
  {
   "title": "Down node %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (count(rate(diem_consensus_current_round[10m]) > 0) OR on() vector(0)) / quantile(0.67, diem_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Not reporting metrics",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"federate\"} == 0 or up{job=\"aptos-procs\", role=\"validator\"} == 0"
    }
   ]
  },
  {
   "title": "Not Participating Consensus",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "rate(diem_consensus_last_committed_round{role=\"validator\"}[1m]) == 0 OR vector(0)"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator Uptime SLA",
     "type": "graph",
     "description": "Average uptime for 30 days.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(commit_uptime{owner=~\"$owner\"}[30d])",
       "legendFormat": "{{owner}}"
      }
     ]
    },
    {
     "title": "Validator Participation SLA",
     "type": "graph",
     "description": "Average participation uptime for 30 days. A node is required to propose at least one block every 12 hours to be counted as up.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(proposal_uptime{owner=~\"$owner\"}[30d])",
       "legendFormat": "{{owner}}"
      }
     ]
    },
    {
     "title": "Fullnode Uptime SLA",
     "type": "graph",
     "description": "Average fullnode uptime for 30 days. A fully synchronized fullnode is counted as up.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(fullnode_uptime{owner=~\"$owner\"}[30d])",
       "legendFormat": "{{owner}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Validator health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator Connected Peers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (owner)(diem_connections{network_id=\"Validator\", role_type=\"validator\", owner=~\"$owner\"})",
       "legendFormat": "{{owner}}"
      }
     ]
    },
    {
     "title": "Committed & Synced Version",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "diem_state_sync_version{type=\"committed\", role=\"validator\", owner=~\"$owner\"}",
       "legendFormat": "{{owner}}-committed"
      },
      {
       "expr": "diem_state_sync_version{type=\"synced\", role=\"validator\", owner=~\"$owner\"}",
       "legendFormat": "{{owner}}-synced"
      }
     ]
    },
    {
     "title": "Committed blocks per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "blocks per sec" }
     ],
     "targets": [
      {
       "expr": "rate(diem_consensus_last_committed_round{owner=~\"$owner\"}[1m])",
       "legendFormat": "{{owner}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fullnode health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fullnode Connected Peers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (owner, network_id)(diem_connections{role_type=\"full_node\", owner=~\"$owner\"})",
       "legendFormat": "{{owner}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Fullnode Upstream Peers",
     "type": "graph",
     "description": "Number of upstream validator peers a full node can proxy transactions up to",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "diem_state_sync_active_upstream_peers{role=\"fullnode\", owner=~\"$owner\"}",
       "legendFormat": "{{owner}}"
      }
     ]
    },
    {
     "title": "State synced version",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "diem_state_sync_version{type=\"synced\", role=\"fullnode\", owner=~\"$owner\"}",
       "legendFormat": "{{owner}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate",
     "type": "graph",
     "description": "The error rate of main loop.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_consensus_error_count{owner=~\"$owner\"}[1m]) / on (owner) rate(consensus_duration_count{op='main_loop', owner=~\"$owner\"}[1m])",
       "legendFormat": "{{owner}}"
      }
     ]
    },
    {
     "title": "Round Timeout Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_consensus_timeout_rounds_count{owner=~\"$owner\"}[1m])",
       "legendFormat": "{{owner}}"
      }
     ]
    },
    {
     "title": "Current Round",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "diem_consensus_current_round{owner=~\"$owner\"}",
       "legendFormat": "{{owner}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mempool size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "diem_core_mempool_index_size{index=\"system_ttl\", owner=~\"$owner\"}",
       "legendFormat": "{{owner}}-{{role}}"
      }
     ]
    },
    {
     "title": "Avg e2e latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted|commit_rejected\", owner=~\"$owner\"}[1m])/rate(diem_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted|commit_rejected\", owner=~\"$owner\"}[1m])",
       "legendFormat": "{{owner}}-{{role}}"
      }
     ]
    },
    {
     "title": "Block execution time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_executor_execute_block_seconds_bucket{role=\"validator\", owner=~\"$owner\"}[1m])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(diem_executor_execute_block_seconds_bucket{role=\"validator\", owner=~\"$owner\"}[1m])) by (le))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(diem_executor_execute_block_seconds_bucket{role=\"validator\", owner=~\"$owner\"}[1m])) by (le))",
       "legendFormat": "P50"
      }
     ]
    }
   ]
  }
 ]
}