{
 "title": "Validator",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": "label_values(owner)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ValidatorSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Down node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_current_epoch_validators) - (count(rate(aptos_consensus_current_round[10m]) > 0) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Down node %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (count(rate(aptos_consensus_current_round[10m]) > 0) OR on() vector(0)) / quantile(0.67, aptos_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Node not Participating Consensus",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_current_round{role=\"validator\"}[1m]) == 0"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Validator Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"validator\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}"
    },
    {
     "expr": "time() - container_start_time_seconds{container_name=\"validator\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (owner)(aptos_connections{network_id=\"Validator\", role_type=\"validator\", owner=~\"$owner\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Committed & Synced Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{type=\"committed\", role=\"validator\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-committed"
    },
    {
     "expr": "aptos_state_sync_version{type=\"synced\", role=\"validator\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-synced"
    }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_current_round{owner=~\"$owner\"}[1m])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Committed Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_last_committed_round{owner=~\"$owner\"}[1m])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_last_committed_version{owner=~\"$owner\"}[1m])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Failed Transaction Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "sum without (state) (rate(aptos_consensus_committed_txns_count{state=\"failed\", owner=~\"$owner\"}[1m])) / sum without (state) (rate(aptos_consensus_committed_txns_count{owner=~\"$owner\"}[1m]))",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted|commit_rejected\", owner=~\"$owner\"}[1m])/rate(core_mempool_txn_commit_latency_count{stage=~\"commit_accepted|commit_rejected\", owner=~\"$owner\"}[1m])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "core_mempool_index_size{index=\"system_ttl\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Key Manager: Keys Still Fresh (Last Hour)",
   "type": "graph",
   "description": "This panel tracks whether the key manager successfully ran within the last hour and determined if the keys are still fresh. If so, the key manager is healthy and 1 is displayed, otherwise, the key manager is unhealthy and 0 is displayed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    {
     "format": "short",
     "label": "Keys Still Fresh? (Bool: 1 = Yes, 0 = No)"
    }
   ],
   "targets": [
    {
     "expr": "increase(aptos_key_manager_state{state=\"keys_still_fresh\", owner=~\"$owner\"}[1h]) > bool 1",
     "legendFormat": "{{owner}}"
    }
   ]
  }
 ]
}