{
 "title": "Mempool",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": "label_values(owner)" },
   { "name": "role", "query": "label_values(role)" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mempool size",
   "type": "graph",
   "description": "total number of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# keys" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"system_ttl\", owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Successful Txn Insertion Rate",
   "type": "graph",
   "description": "rate of mempool insertion of txn",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "txns / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role, status) (rate(diem_shared_mempool_transactions_processed{status=\"success\", owner=~\"$owner\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{owner}}:{{role}} - {{status}}"
    }
   ]
  },
  {
   "title": "Txn Removal Rate",
   "type": "graph",
   "description": "Rate at which txns are removed (via commit) from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "txns/sec" }
   ],
   "targets": [
    {
     "expr": "rate(diem_core_mempool_removed_txns_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Active Upstream Peers",
   "type": "graph",
   "description": "number of live peers a node can broadcast to in each network",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role, network) (diem_mempool_active_upstream_peers_count{owner=~\"$owner\", role=~\"$role\"})",
     "legendFormat": "{{owner}}:{{role}}  ({{network}} network)"
    }
   ]
  },
  {
   "title": "VM Failed Txns Rate",
   "type": "graph",
   "description": "rate of submitted txns that failed to pass the VM validation",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "txn / s" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role, network, sender) (rate(diem_shared_mempool_transactions_processed{status=\"vm_validation\", owner=~\"$owner\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{owner}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Mempool Service Timeout",
   "type": "graph",
   "description": "number of timeouts on a mempool service request (from consensus/state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_latency_ms_count{result=\"fail\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} - {{type}}"
    }
   ]
  },
  {
   "title": "DB error",
   "type": "graph",
   "description": "number of times a DB error occurred",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_db_error_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "JSON RPC Callback Timeout",
   "type": "graph",
   "description": "number of timeouts in callback to JSON RPC",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_json_rpc_callback_fail_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Network Send Fail",
   "type": "graph",
   "description": "number of times a diem network send failed",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_network_send_fail_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "VM Reconfiguration Failure",
   "type": "graph",
   "description": "number of times reconfiguration of VM failed",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_vm_reconfig_update_fail_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Core Mempool Invariant Violation",
   "type": "graph",
   "description": "number of times core mempool invariant was violated",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_core_mempool_invariant_violated_count{owner=\"$owner\", role=\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Unexpected Network Messages",
   "type": "graph",
   "description": "rate of unexpected network messages received",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_unexpected_network_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} <- {{network}}:{{peer}}"
    }
   ]
  },
  {
   "title": "Core Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true
  },
  {
   "title": "Client-expired txns",
   "type": "graph",
   "description": "rate of number of transactions that expired in mempool based on client-specified expiration time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "txns" }
   ],
   "targets": [
    {
     "expr": "rate(diem_core_mempool_gc_latency_count{type=\"client_expiration\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} : {{status}}"
    }
   ]
  },
  {
   "title": "System-expired Txns",
   "type": "graph",
   "description": "Rate of number of transactions that expired in mempool based on mempool-specified expiration time",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "txns" }
   ],
   "targets": [
    {
     "expr": "rate(diem_core_mempool_gc_latency_count{type=\"system_ttl\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} : {{status}}"
    }
   ]
  },
  {
   "title": "Parking Lot Index",
   "type": "graph",
   "description": "number of transactions in parking lot index. These transactions are not ready for broadcast or consensus",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "# keys" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"parking_lot\", owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Timeline Index",
   "type": "graph",
   "description": "number of transactions ready for broadcast in core mempool ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "# keys" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"timeline\", owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Priority Index",
   "type": "graph",
   "description": "transactions ready for consensus",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "# keys" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"priority\", role=\"validator\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Failed Mempool Insertion Rate",
   "type": "graph",
   "description": "rate of transactions that passed VM validation but were rejected from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "failures / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_transactions_processed{status!=\"success\", status!=\"vm_validation\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} <- ({{network}} network:{{sender}}) -  {{status}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Event Rate",
   "type": "graph",
   "description": "Number of times garbage-collection event occurred (regardless of how many txns were actually removed in the event)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "events / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_core_mempool_gc_event_count{type=\"system_ttl\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "GC Latency",
   "type": "graph",
   "description": "how long a transaction stayed in mempool before being garbage-collected",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_core_mempool_gc_latency_sum{owner=~\"$owner\", role=~\"$role\"}[$interval])/rate(diem_core_mempool_gc_latency_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true
  },
  {
   "title": "Accepted Transaction Commit Rate",
   "type": "graph",
   "description": "Rate of accepted transactions committed per second (notified from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "accepted txns / sec" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_transactions_sum{type=\"commit_accepted\", owner=~\"$owner\", role=~\"$role\"}[$interval])\n",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Avg latency for commit (accepted)",
   "type": "graph",
   "description": "average time it takes for mempool to process a commit of accepted transactions (sent from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_latency_ms_sum{type=\"commit_accepted\", owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_mempool_service_latency_ms_count{type=\"commit_accepted\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Rejected Transaction Commit Rate",
   "type": "graph",
   "description": "rate of rejected committed transactions (notified from consensus)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "txns/sec" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_transactions_sum{type=\"commit_rejected\", owner=~\"$owner\", role=~\"$role\"}[$interval])\n",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Avg time of commit (rejected txns)",
   "type": "graph",
   "description": "avg time it takes to process committed rejected txns",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_latency_ms_sum{type=\"commit_rejected\", owner=~\"$owner\"}[$interval])/rate(diem_mempool_service_latency_ms_count{type=\"commit_rejected\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "graph",
   "description": "Average size of consensus blocks pulled from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short", "label": "avg block size" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_transactions_sum{type=\"get_block\", owner=~\"$owner\"}[$interval]) / rate(diem_mempool_service_transactions_count{type=\"get_block\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Avg latency for get_block",
   "type": "graph",
   "description": "Avg time it takes for consensus to pull block from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_latency_ms_sum{type=\"get_block\", owner=~\"$owner\"}[$interval]) / rate(diem_mempool_service_latency_ms_count{type=\"get_block\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Shared mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true
  },
  {
   "title": "Incoming events rate",
   "type": "graph",
   "description": "rate of shared mempool events from peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "events/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_events{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} - {{event}}"
    }
   ]
  },
  {
   "title": "Shared Mempool Task Start Latency",
   "type": "graph",
   "description": "average time it takes for mempool to start an async task",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_bounded_executor_spawn_latency_sum{stage=\"start\", owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_mempool_bounded_executor_spawn_latency_count{stage=\"start\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} - {{task}}"
    }
   ]
  },
  {
   "title": "Incoming Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true
  },
  {
   "title": "New transactions received rate",
   "type": "graph",
   "description": "rate of new transactions received from other peers or JSON-RPC",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "txns/s" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role, network, sender) (rate(diem_shared_mempool_transactions_processed{owner=~\"$owner\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{owner}}:{{role}} <- ({{network}} network, {{sender}})"
    }
   ]
  },
  {
   "title": "Successful transaction validation rate",
   "type": "graph",
   "description": "rate of transactions that were successfully validated before mempool insertion\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "txns/s" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role, network, sender) (rate(diem_shared_mempool_transactions_processed{status!=\"vm_validation\", owner=~\"$owner\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{owner}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "Average Txn Processing Latency",
   "type": "graph",
   "description": "avg time it takes to process incoming transactions, per incoming submission",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "s", "label": "sec / txn submission" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_request_latency_sum{owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_shared_mempool_request_latency_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "Average VM Validation Latency",
   "type": "graph",
   "description": "avg time it takes to VM-validate txns in a submission",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_process_txn_breakdown_latency_sum{portion=\"vm_validation\", owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_mempool_process_txn_breakdown_latency_count{portion=\"vm_validation\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Average DB Read Latency",
   "type": "graph",
   "description": "latency of db read when validating transaction",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_process_txn_breakdown_latency_sum{portion=\"storage_fetch\", owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_mempool_process_txn_breakdown_latency_count{portion=\"storage_fetch\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Outgoing Txn Broadcasts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true
  },
  {
   "title": "Average Broadcast Size",
   "type": "graph",
   "description": "average number of transactions in a single broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "txns / broadcast" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_transaction_broadcast_sum{owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_shared_mempool_transaction_broadcast_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} -> ({{network}} network:{{recipient}})"
    }
   ]
  },
  {
   "title": "Broadcasted Txns Rate",
   "type": "graph",
   "description": "rate of transactions broadcasted to other peers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "txns/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_transaction_broadcast_sum{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} -> ({{network}} network:{{recipient}})"
    }
   ]
  },
  {
   "title": "Broadcast Rate",
   "type": "graph",
   "description": "avg number of broadcasts / sec",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "broadcasts / sec" }
   ],
   "targets": [
    {
     "expr": "rate(diem_broadcast_latency_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} -> ({{network}} network:{{recipient}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Execution Latency",
   "type": "graph",
   "description": "avg time it takes to execute a broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "s", "label": "secs / broadcast" }
   ],
   "targets": [
    {
     "expr": "rate(diem_broadcast_latency_sum{owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_broadcast_latency_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} -> ({{network}} network,{{recipient}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Roundtrip Time",
   "type": "graph",
   "description": "average time b/w broadcast sent and ACK coming back for it",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_broadcast_roundtrip_latency_sum{owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_shared_mempool_broadcast_roundtrip_latency_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} -> ({{network}} network:{{recipient}})"
    }
   ]
  },
  {
   "title": "Pending Broadcasts",
   "type": "graph",
   "description": "number of sent broadcasts awaiting an ACK",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "# broadcasts" }
   ],
   "targets": [
    {
     "expr": "diem_shared_mempool_pending_broadcasts_count{owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}:{{role}} -> ({{network}}:{{recipient}})"
    }
   ]
  },
  {
   "title": "Expired Rebroadcast Rate",
   "type": "graph",
   "description": "rate of broadcasts that are retrying expired braodcasts (that did not get back an ACK in window of time)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short", "label": "expired / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_rebroadcast_count{type=\"expired\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} -> {{network}}:{{recipient}}"
    }
   ]
  },
  {
   "title": "Retry Rebroadcast",
   "type": "graph",
   "description": "rate of broadcasts that are retrying past broadcasts that received a retry ACK",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_rebroadcast_count{type=\"retry\", owner=~\"$owner\", role=~\"role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} -> ({{network}}:{{recipient}})"
    }
   ]
  },
  {
   "title": "Backpressure Broadcast",
   "type": "graph",
   "description": "rate of broadcasts that were executed as a backpressure broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_rebroadcast_count{type=\"backpressure\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} -> {{network}}:{{recipient}}"
    }
   ]
  },
  {
   "title": "ACKs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "collapsed": true
  },
  {
   "title": "Sent ACKs (backoff/retry)",
   "type": "graph",
   "description": "rate of backoff/retry ACKs sent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_shared_mempool_ack_count{direction=\"sent\", owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}:{{role}} -> {{network}}:{{recipient}} - {{type}}"
    }
   ]
  },
  {
   "title": "ACKs Received",
   "type": "graph",
   "description": "rate of retry/backpressure ACKs received",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_ack_count{direction=\"received\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}} <- {{network}}:{{recipient}} - {{type}}"
    }
   ]
  },
  {
   "title": "Network Sender",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "collapsed": true
  },
  {
   "title": "Dropped Messages",
   "type": "graph",
   "description": "number of messages dropped from mempool channel sender",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_pending_network_events{state=\"dropped\", owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Messages Enqueued Rate",
   "type": "graph",
   "description": "rate of messages being enqueued to be sent out",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mempool_pending_network_events{state=\"enqueued\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Messages Dequeued Rate",
   "type": "graph",
   "description": "Rate of messages dequeued from mempool network sender",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mempool_pending_network_events{state=\"dequeued\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  },
  {
   "title": "Messages Queued",
   "type": "graph",
   "description": "Messages currently queued to be sent out",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role) (mempool_pending_network_events{state=\"enqueued\", owner=~\"$owner\", role=~\"$role\"}) - sum by (owner, role)  (mempool_pending_network_events{state=\"dequeued\", owner=~\"$owner\", role=~\"$role\"})",
     "legendFormat": "{{owner}}:{{role}}"
    }
   ]
  }
 ]
}