{
 "title": "VM",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": "label_values(owner)" },
   { "name": "role", "query": "label_values(role)" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Transactions (Successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_user_transactions_executed{status=\"success\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "System Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_system_transactions_executed{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Validated Transactions (Successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_transactions_validated{status=\"success\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Num Txns per Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "txns per block" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_num_txns_per_block_sum{owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_vm_num_txns_per_block_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  { "title": "Gas Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg Gas per User Txn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "gas/txn" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_txn_gas_usage_sum{owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_vm_txn_gas_usage_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Avg Txn Total Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_txn_total_seconds_sum{owner=~\"$owner\", role=~\"$role\"}[$interval]) / rate(diem_vm_txn_total_seconds_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg Txn Validation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_txn_validation_seconds_sum{owner=~\"$owner\", role=~\"$role\"}[$interval])/rate(diem_vm_txn_validation_seconds_count{owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg Time per Gas Unit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s", "label": "seconds / unit gas" }
   ],
   "targets": [
    {
     "expr": "rate(diem_vm_txn_total_seconds_sum{owner=~\"$owner\", role=~\"$role\"}[$interval])/rate(diem_vm_txn_total_seconds_count{owner=~\"$owner\", role=~\"$role\"}[$interval])/(rate(diem_vm_txn_gas_usage_sum{owner=~\"$owner\", role=~\"$role\"}[$interval])/rate(diem_vm_txn_gas_usage_count{owner=~\"$owner\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  }
 ]
}