============ initial translation from Move ================

[variant baseline]
public fun GlobalSpecRelevance::create($t0|i: u64, $t1|j: u64): GlobalSpecRelevance::Nonzero {
     var $t2: u64
     var $t3: u64
     var $t4: GlobalSpecRelevance::Nonzero
  0: $t2 := copy($t0)
  1: $t3 := copy($t1)
  2: $t4 := pack GlobalSpecRelevance::Nonzero($t2, $t3)
  3: return $t4
}


[variant baseline]
public fun GlobalSpecRelevance::leak_i_bad($t0|n: &mut GlobalSpecRelevance::Nonzero): &mut u64 {
     var $t1: &mut GlobalSpecRelevance::Nonzero
     var $t2: &mut u64
  0: $t1 := move($t0)
  1: $t2 := borrow_field<GlobalSpecRelevance::Nonzero>.i($t1)
  2: return $t2
}


[variant baseline]
public fun GlobalSpecRelevance::leak_j_ok($t0|n: &mut GlobalSpecRelevance::Nonzero): &mut u64 {
     var $t1: &mut GlobalSpecRelevance::Nonzero
     var $t2: &mut u64
  0: $t1 := move($t0)
  1: $t2 := borrow_field<GlobalSpecRelevance::Nonzero>.j($t1)
  2: return $t2
}


[variant baseline]
public fun GlobalSpecRelevance::publish($t0|account: &signer, $t1|n: GlobalSpecRelevance::Nonzero) {
     var $t2|tmp#$2: bool
     var $t3|tmp#$3: u64
     var $t4: &GlobalSpecRelevance::Nonzero
     var $t5: &u64
     var $t6: u64
     var $t7: u64
     var $t8: bool
     var $t9: bool
     var $t10: &signer
     var $t11: u64
     var $t12: &signer
     var $t13: GlobalSpecRelevance::Nonzero
  0: $t4 := borrow_local($t1)
  1: $t5 := borrow_field<GlobalSpecRelevance::Nonzero>.i($t4)
  2: $t6 := read_ref($t5)
  3: $t7 := 0
  4: $t8 := >($t6, $t7)
  5: $t2 := $t8
  6: $t9 := move($t2)
  7: if ($t9) goto 13 else goto 8
  8: label L1
  9: $t10 := move($t0)
 10: destroy($t10)
 11: $t11 := 0
 12: abort($t11)
 13: label L0
 14: $t12 := move($t0)
 15: $t13 := move($t1)
 16: move_to<GlobalSpecRelevance::Nonzero>($t13, $t12)
 17: return ()
}

============ after pipeline `escape_analysis` ================

[variant baseline]
public fun GlobalSpecRelevance::create($t0|i: u64, $t1|j: u64): GlobalSpecRelevance::Nonzero {
     var $t2: u64
     var $t3: u64
     var $t4: GlobalSpecRelevance::Nonzero
  0: $t2 := copy($t0)
  1: $t3 := copy($t1)
  2: $t4 := pack GlobalSpecRelevance::Nonzero($t2, $t3)
  3: return $t4
}


[variant baseline]
public fun GlobalSpecRelevance::leak_i_bad($t0|n: &mut GlobalSpecRelevance::Nonzero): &mut u64 {
     var $t1: &mut GlobalSpecRelevance::Nonzero
     var $t2: &mut u64
  0: $t1 := move($t0)
  1: $t2 := borrow_field<GlobalSpecRelevance::Nonzero>.i($t1)
  2: return $t2
}


[variant baseline]
public fun GlobalSpecRelevance::leak_j_ok($t0|n: &mut GlobalSpecRelevance::Nonzero): &mut u64 {
     var $t1: &mut GlobalSpecRelevance::Nonzero
     var $t2: &mut u64
  0: $t1 := move($t0)
  1: $t2 := borrow_field<GlobalSpecRelevance::Nonzero>.j($t1)
  2: return $t2
}


[variant baseline]
public fun GlobalSpecRelevance::publish($t0|account: &signer, $t1|n: GlobalSpecRelevance::Nonzero) {
     var $t2|tmp#$2: bool
     var $t3|tmp#$3: u64
     var $t4: &GlobalSpecRelevance::Nonzero
     var $t5: &u64
     var $t6: u64
     var $t7: u64
     var $t8: bool
     var $t9: bool
     var $t10: &signer
     var $t11: u64
     var $t12: &signer
     var $t13: GlobalSpecRelevance::Nonzero
  0: $t4 := borrow_local($t1)
  1: $t5 := borrow_field<GlobalSpecRelevance::Nonzero>.i($t4)
  2: $t6 := read_ref($t5)
  3: $t7 := 0
  4: $t8 := >($t6, $t7)
  5: $t2 := $t8
  6: $t9 := move($t2)
  7: if ($t9) goto 13 else goto 8
  8: label L1
  9: $t10 := move($t0)
 10: destroy($t10)
 11: $t11 := 0
 12: abort($t11)
 13: label L0
 14: $t12 := move($t0)
 15: $t13 := move($t1)
 16: move_to<GlobalSpecRelevance::Nonzero>($t13, $t12)
 17: return ()
}

============ Diagnostics ================
error: Leaked mutable module-internal reference via return value 0
   ┌─ tests/escape_analysis/global_spec_relevance.move:12:5
   │
12 │ ╭     public fun leak_j_ok(n: &mut Nonzero): &mut u64 {
13 │ │         &mut n.j
14 │ │     }
   │ ╰─────^

error: Leaked mutable module-internal reference via return value 0
  ┌─ tests/escape_analysis/global_spec_relevance.move:7:5
  │
7 │ ╭     public fun leak_i_bad(n: &mut Nonzero): &mut u64 {
8 │ │         &mut n.i
9 │ │     }
  │ ╰─────^
