processed 2 tasks

task 0 'publish'. lines 1-17:
Error: Unable to publish module '00000000000000000000000000000001::M'. Got VMError: {
    major_status: STLOC_UNSAFE_TO_DESTROY_ERROR,
    sub_status: None,
    location: 0x1::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 7)],
}

task 1 'publish'. lines 19-35:
Error: Unable to publish module '00000000000000000000000000000001::N'. Got VMError: {
    major_status: STLOC_UNSAFE_TO_DESTROY_ERROR,
    sub_status: None,
    location: 0x1::N,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 10)],
}
