processed 4 tasks

task 0 'publish'. lines 1-14:
Error: Unable to publish module '00000000000000000000000000000001::M'. Got VMError: {
    major_status: UNSAFE_RET_LOCAL_OR_RESOURCE_STILL_BORROWED,
    sub_status: None,
    location: 0x1::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 5)],
}

task 1 'publish'. lines 16-28:
Error: Unable to publish module '00000000000000000000000000000001::M2'. Got VMError: {
    major_status: UNSAFE_RET_LOCAL_OR_RESOURCE_STILL_BORROWED,
    sub_status: None,
    location: 0x1::M2,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 5)],
}

task 2 'publish'. lines 30-46:
Error: Unable to publish module '00000000000000000000000000000001::M3'. Got VMError: {
    major_status: UNSAFE_RET_LOCAL_OR_RESOURCE_STILL_BORROWED,
    sub_status: None,
    location: 0x1::M3,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 13)],
}

task 3 'publish'. lines 48-64:
Error: Unable to publish module '00000000000000000000000000000001::M4'. Got VMError: {
    major_status: UNSAFE_RET_LOCAL_OR_RESOURCE_STILL_BORROWED,
    sub_status: None,
    location: 0x1::M4,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 13)],
}
