warning[W04022]: script function cannot be invoked with this signature (NOTE: this may become an error in the future)
  ┌─ tests/move_check/typing/public_script_signature_warning.move:7:24
  │
7 │     public(script) fun signer_ref(_: &signer) {}
  │                        ^^^^^^^^^^    ------- Found: '&signer'. But expected one of: 'u8', 'u64', 'u128', 'bool', 'address', 'vector<_>'
  │                        │              
  │                        Invalid parameter for script function 'signer_ref'

warning[W04022]: script function cannot be invoked with this signature (NOTE: this may become an error in the future)
  ┌─ tests/move_check/typing/public_script_signature_warning.move:9:24
  │
9 │     public(script) fun late_signer(_u: u64, _s: signer) {}
  │                        ^^^^^^^^^^^              ------ 'signer's must be a prefix of the arguments to a script--they must come before any non-signer types
  │                        │                         
  │                        Invalid parameter for script function 'late_signer'

warning[W04022]: script function cannot be invoked with this signature (NOTE: this may become an error in the future)
   ┌─ tests/move_check/typing/public_script_signature_warning.move:11:24
   │
11 │     public(script) fun struct_arg(_: CoolStruct) {}
   │                        ^^^^^^^^^^    ---------- Found: '0x42::M::CoolStruct'. But expected one of: 'u8', 'u64', 'u128', 'bool', 'address', 'vector<_>'
   │                        │              
   │                        Invalid parameter for script function 'struct_arg'

warning[W04022]: script function cannot be invoked with this signature (NOTE: this may become an error in the future)
   ┌─ tests/move_check/typing/public_script_signature_warning.move:13:24
   │
13 │     public(script) fun u64_ret(): u64 {
   │                        ^^^^^^^    --- Given: 'u64'
   │                        │           
   │                        'public(script)' functions must have a return type of '()' in order to be invocable as a script entry point
   │                        Expected: '()'

warning[W04022]: script function cannot be invoked with this signature (NOTE: this may become an error in the future)
   ┌─ tests/move_check/typing/public_script_signature_warning.move:17:24
   │
17 │     public(script) fun struct_ret(): CoolStruct {
   │                        ^^^^^^^^^^    ---------- Given: '0x42::M::CoolStruct'
   │                        │              
   │                        'public(script)' functions must have a return type of '()' in order to be invocable as a script entry point
   │                        Expected: '()'

