ResolutionGraph {
    root_package_path: "tests/test_sources/resolution/basic_no_deps_address_assigned",
    build_options: BuildConfig {
        dev_mode: true,
        test_mode: false,
        generate_docs: false,
        generate_abis: false,
        install_dir: Some(
            "ELIDED_FOR_TEST",
        ),
        force_recompilation: false,
    },
    root_package: SourceManifest {
        package: PackageInfo {
            name: "test",
            version: (
                0,
                0,
                0,
            ),
            authors: [],
            license: None,
        },
        addresses: Some(
            {
                "A": Some(
                    00000000000000000000000000000000,
                ),
            },
        ),
        dev_address_assignments: None,
        build: None,
        dependencies: {},
        dev_dependencies: {},
    },
    graph: {
        "test": [],
    },
    package_table: {
        "test": ResolutionPackage {
            resolution_graph_index: "test",
            source_package: SourceManifest {
                package: PackageInfo {
                    name: "test",
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: Some(
                    {
                        "A": Some(
                            00000000000000000000000000000000,
                        ),
                    },
                ),
                dev_address_assignments: None,
                build: None,
                dependencies: {},
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {},
            resolution_table: {
                "A": 00000000000000000000000000000000,
            },
            source_digest: "ELIDED_FOR_TEST",
        },
    },
}
