// Copyright (c) Aptos
// SPDX-License-Identifier: Apache-2.0

#![recursion_limit = "512"]

#[macro_use]
extern crate diesel_migrations;

// Need to use this for because src/schema.rs uses the macros and is autogenerated
#[macro_use]
extern crate diesel;

pub mod counters;
pub mod database;
pub mod default_processor;
pub mod indexer;
pub mod models;
pub mod schema;
