processed 17 tasks

task 1 'run'. lines 17-23:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2 'run'. lines 25-31:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 4 'run'. lines 48-54:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 5 'run'. lines 56-62:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7 'run'. lines 79-85:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 8 'run'. lines 87-93:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 10 'run'. lines 111-117:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 11 'run'. lines 119-125:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 12 'run'. lines 127-133:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 14 'run'. lines 152-158:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 15 'run'. lines 160-166:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 16 'run'. lines 168-174:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
