
Diagnostics:
warning: [lint] Address parameter 'warn_q' used without zero-address validation
  ┌─ tests/stackless_bytecode_lints/zero_address.move:3:49
  │
3 │     public fun example_zero_address(p: address, warn_q: address): address {
  │                                                 ^^^^^^
  │
  = To suppress this warning, annotate the function/module with the attribute `#[lint::skip(zero_address)]`.
  = For more information, see https://aptos.dev/en/build/smart-contracts/linter#zero_address.

warning: [lint] Address parameter 'warn_p' used without zero-address validation
   ┌─ tests/stackless_bytecode_lints/zero_address.move:10:40
   │
10 │     public fun example_unchecked_param(warn_p: address): u32 {
   │                                        ^^^^^^
   │
   = To suppress this warning, annotate the function/module with the attribute `#[lint::skip(zero_address)]`.
   = For more information, see https://aptos.dev/en/build/smart-contracts/linter#zero_address.

warning: [lint] Address parameter 'warn_p' used without zero-address validation
   ┌─ tests/stackless_bytecode_lints/zero_address.move:51:25
   │
51 │     public fun no_check(warn_p: address){
   │                         ^^^^^^
   │
   = To suppress this warning, annotate the function/module with the attribute `#[lint::skip(zero_address)]`.
   = For more information, see https://aptos.dev/en/build/smart-contracts/linter#zero_address.
