#!/bin/bash
# Copyright (c) Aptos Foundation
# Licensed pursuant to the Innovation-Enabling Source Code License, available at
# https://github.com/aptos-labs/aptos-core/blob/main/LICENSE
#
# Publishes the MoveFlow Claude Code plugin to the aptos-labs/aptos-ai repo.
#
# Usage: publish-plugin.sh [aptos-ai-repo-path]
#
# Builds move-flow, generates the plugin tree, syncs it into aptos-ai, and
# opens (or updates) a PR. Defaults to ~/aptos-ai if no path is given.

set -euo pipefail

# --- Phase 0: Setup and validation ---

REPO_ROOT="$(git rev-parse --show-toplevel)"
FLOW_DIR="$REPO_ROOT/aptos-move/flow"
APTOS_AI="${1:-$HOME/aptos-ai}"

VERSION=$(sed -n 's/^version *= *"\(.*\)"/\1/p' "$FLOW_DIR/Cargo.toml")
if [ -z "$VERSION" ]; then
    echo "ERROR: could not extract version from $FLOW_DIR/Cargo.toml"
    exit 1
fi

for cmd in cargo gh git; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "ERROR: $cmd is required but not found on PATH"
        exit 1
    fi
done

if [ ! -d "$APTOS_AI/.git" ]; then
    echo "ERROR: $APTOS_AI is not a git repository"
    exit 1
fi

if [ -n "$(git -C "$APTOS_AI" status --porcelain)" ]; then
    echo "ERROR: $APTOS_AI has uncommitted changes. Please commit or stash first."
    exit 1
fi

echo "Publishing move-flow plugin v${VERSION}"
echo "  Source:  $FLOW_DIR"
echo "  Target:  $APTOS_AI/plugins/move-flow/"
echo

# --- Phase 1: Build move-flow ---

echo "==> Building move-flow..."
(cd "$REPO_ROOT" && cargo build -p aptos-move-flow --profile=ci)
MOVE_FLOW="$REPO_ROOT/target/ci/move-flow"

if [ ! -x "$MOVE_FLOW" ]; then
    echo "ERROR: build succeeded but binary not found at $MOVE_FLOW"
    exit 1
fi

# --- Phase 2: Generate plugin tree ---

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "==> Generating plugin tree..."
"$MOVE_FLOW" plugin "$TMPDIR/plugin"

if [ ! -f "$TMPDIR/plugin/.claude-plugin/plugin.json" ]; then
    echo "ERROR: plugin generation failed — missing .claude-plugin/plugin.json"
    exit 1
fi

# --- Phase 3: Sync into aptos-ai ---

echo "==> Syncing into aptos-ai..."
cd "$APTOS_AI"
git checkout main
git pull --ff-only origin main

rm -rf plugins/move-flow
mkdir -p plugins/move-flow
cp -r "$TMPDIR/plugin/." plugins/move-flow/

# --- Phase 4: Check for existing PR ---

BRANCH="move-flow/v${VERSION}"
EXISTING_PR=$(gh pr list --repo aptos-labs/aptos-ai --head "$BRANCH" --state open --json url --jq '.[0].url // empty' 2>/dev/null || true)

# --- Phase 5: Branch, commit, push, PR ---

git checkout -B "$BRANCH"
git add plugins/move-flow/

if git diff --cached --quiet; then
    echo "No changes to publish — plugin is already up to date."
    exit 0
fi

APTOS_CORE_SHA=$(git -C "$REPO_ROOT" rev-parse --short HEAD)

git commit -m "Update move-flow plugin to v${VERSION}

Generated from aptos-core commit ${APTOS_CORE_SHA}."

git push -u origin "$BRANCH" --force-with-lease

if [ -z "$EXISTING_PR" ]; then
    PR_URL=$(gh pr create \
        --repo aptos-labs/aptos-ai \
        --title "Update move-flow plugin to v${VERSION}" \
        --body "$(cat <<EOF
## Summary
- Regenerated move-flow Claude Code plugin from aptos-core at \`${APTOS_CORE_SHA}\`
- Plugin version: ${VERSION}

## Files
The \`plugins/move-flow/\` directory contains the full generated plugin tree
(agents, skills, hooks, MCP config, plugin manifest).

Generated by \`aptos-move/flow/scripts/publish-plugin.sh\`.
EOF
)")
    echo
    echo "PR created: $PR_URL"
else
    echo
    echo "Existing PR updated: $EXISTING_PR"
fi
