// Copyright (c) Aptos Foundation
// Licensed pursuant to the Innovation-Enabling Source Code License, available at https://github.com/aptos-labs/aptos-core/blob/main/LICENSE

//! Loader for the mainnet validator snapshot used by the mainnet-mirror forge
//! suite.
//!
//! The snapshot is produced by `scripts/pull_mainnet_validator_snapshot.py`
//! against the live mainnet validator set: each entry has a peer_id, voting
//! power, and a forge region bucket derived from IP geolocation.
//!
//! This module turns that JSON into the two arrays the forge suite needs:
//! - per-validator stake amounts (passed to the genesis chart)
//! - region weights for `MultiRegionNetworkEmulationConfig`
//!
//! The validators are sorted into the same order that
//! `MultiRegionNetworkEmulationTest` chunks peers by region: alphabetical by
//! `link_stats` region key (which is what the BTreeMap iteration in
//! `create_link_stats_table_with_peer_groups` produces). With this ordering
//! the chunked validator list naturally lines up stake-with-region.

use anyhow::{ensure, Context, Result};
use serde::Deserialize;
use std::{fs, path::Path};

/// The mainnet validator snapshot bundled at build time. Generated by
/// `scripts/pull_mainnet_validator_snapshot.py`. Embedded so the deployed forge
/// binary doesn't need to read the file off disk at runtime.
const EMBEDDED_SNAPSHOT: &str = include_str!("data/mainnet-mirror/mainnet_validator_snapshot.json");

/// A forge region bucket. The variants are listed in the same alphabetical
/// order as their `link_stats` names so that
/// `Region::ordered_for_chunking()` matches the BTreeMap iteration in
/// `MultiRegionNetworkEmulationTest`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Region {
    /// `aws--ap-northeast-1`
    Apne1,
    /// `aws--eu-central1`
    EuCentral1,
    /// `aws--eu-west-1`
    EuWest1,
    /// `aws--sa-east-1`
    SaEast1,
    /// `gcp--ca-central-1`
    CaCentral1,
    /// `gcp--us-central1`
    UsCentral1,
}

impl Region {
    /// Region order matching the BTreeMap iteration used by
    /// `MultiRegionNetworkEmulationTest::create_link_stats_table_with_peer_groups`.
    /// Peers are chunked by weight in this order, so stake amounts must be
    /// supplied in the same order.
    pub const ORDERED: [Region; 6] = [
        Region::Apne1,      // aws--ap-northeast-1
        Region::EuCentral1, // aws--eu-central1
        Region::EuWest1,    // aws--eu-west-1
        Region::SaEast1,    // aws--sa-east-1
        Region::CaCentral1, // gcp--ca-central-1
        Region::UsCentral1, // gcp--us-central1
    ];

    /// The label written by the snapshot script (`scripts/pull_mainnet_validator_snapshot.py`).
    pub fn snapshot_label(&self) -> &'static str {
        match self {
            Region::Apne1 => "apne1",
            Region::EuCentral1 => "eu-central1",
            Region::EuWest1 => "eu-west-1",
            Region::SaEast1 => "sa-east-1",
            Region::CaCentral1 => "ca-central-1",
            Region::UsCentral1 => "us-central1",
        }
    }

    fn from_snapshot_label(s: &str) -> Option<Region> {
        match s {
            "apne1" => Some(Region::Apne1),
            "eu-central1" => Some(Region::EuCentral1),
            "eu-west-1" => Some(Region::EuWest1),
            "sa-east-1" => Some(Region::SaEast1),
            "ca-central-1" => Some(Region::CaCentral1),
            "us-central1" => Some(Region::UsCentral1),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
pub struct ValidatorEntry {
    pub peer_id: String,
    pub stake_octa: u64,
    pub region: Region,
}

#[derive(Deserialize)]
struct RawSnapshot {
    validators: Vec<RawEntry>,
}

#[derive(Deserialize)]
struct RawEntry {
    peer_id: String,
    /// Octa as decimal string — voting_power is u64-sized, so JSON stores it
    /// as a string for cross-language safety.
    voting_power: String,
    region: String,
}

/// A loaded mainnet snapshot, filtered to active validators (non-zero stake +
/// known region) and sorted into chaos-chunking order.
pub struct MainnetMirrorSnapshot {
    validators: Vec<ValidatorEntry>,
}

impl MainnetMirrorSnapshot {
    /// Load and validate a snapshot from a JSON file.
    ///
    /// Most callers should use [`load_embedded`] instead — this is for tests
    /// and the rare case of overriding the bundled snapshot.
    ///
    /// Filters out:
    /// - validators with zero voting power (e.g. unstaked or pending)
    /// - validators with `region == "unknown"` (couldn't geolocate; kept in
    ///   the snapshot for auditability but excluded from forge runs)
    ///
    /// Sorts the remainder by (region in `Region::ORDERED` order, stake desc)
    /// so the forge swarm iteration yields the right per-region chunks.
    pub fn load(path: &Path) -> Result<Self> {
        let bytes = fs::read(path)
            .with_context(|| format!("reading mainnet snapshot from {}", path.display()))?;
        Self::load_from_slice(&bytes)
            .with_context(|| format!("parsing mainnet snapshot at {}", path.display()))
    }

    /// Parse a snapshot from its JSON bytes. See [`load`] for filtering rules.
    pub fn load_from_slice(bytes: &[u8]) -> Result<Self> {
        let raw: RawSnapshot = serde_json::from_slice(bytes).context("parsing snapshot JSON")?;

        let mut entries: Vec<ValidatorEntry> = raw
            .validators
            .into_iter()
            .filter_map(|e| {
                let stake: u64 = e.voting_power.parse().ok()?;
                if stake == 0 {
                    return None;
                }
                let region = Region::from_snapshot_label(&e.region)?;
                Some(ValidatorEntry {
                    peer_id: e.peer_id,
                    stake_octa: stake,
                    region,
                })
            })
            .collect();

        ensure!(
            !entries.is_empty(),
            "snapshot contains no usable validators"
        );

        // Sort by region (in chaos-chunking order), then descending stake within region.
        let region_index = |r: Region| {
            Region::ORDERED
                .iter()
                .position(|x| *x == r)
                .expect("Region::ORDERED covers all variants")
        };
        entries.sort_by(|a, b| {
            region_index(a.region)
                .cmp(&region_index(b.region))
                .then_with(|| b.stake_octa.cmp(&a.stake_octa))
        });

        Ok(Self {
            validators: entries,
        })
    }

    /// Loads the snapshot bundled with this crate (`include_str!`-embedded at
    /// compile time). This is what forge suites should call.
    pub fn load_embedded() -> Result<Self> {
        Self::load_from_slice(EMBEDDED_SNAPSHOT.as_bytes())
            .context("parsing embedded mainnet validator snapshot")
    }

    pub fn validator_count(&self) -> usize {
        self.validators.len()
    }

    pub fn validators(&self) -> &[ValidatorEntry] {
        &self.validators
    }

    /// Per-validator stake amounts, in chaos-chunking order. Index `i` is the
    /// stake for the `i`th validator in the forge swarm.
    pub fn stake_amounts(&self) -> Vec<u64> {
        self.validators.iter().map(|v| v.stake_octa).collect()
    }

    /// Region weights summing to 1.0, ordered to match `Region::ORDERED` (i.e.
    /// the BTreeMap iteration of `link_stats`).
    pub fn region_weights(&self) -> Vec<f64> {
        let total = self.validators.len() as f64;
        Region::ORDERED
            .iter()
            .map(|target| {
                let count = self
                    .validators
                    .iter()
                    .filter(|v| v.region == *target)
                    .count();
                count as f64 / total
            })
            .collect()
    }

    /// Counts of validators per region in `Region::ORDERED` order. Useful for
    /// logging / diagnostics; sums to `validator_count()`.
    pub fn region_counts(&self) -> Vec<(Region, usize)> {
        Region::ORDERED
            .iter()
            .map(|r| {
                let count = self.validators.iter().filter(|v| v.region == *r).count();
                (*r, count)
            })
            .collect()
    }
}

// Module-private: surface a couple of guard checks that the suite consumer
// will want to call early.
impl MainnetMirrorSnapshot {
    /// Sanity-check that the snapshot has at least one validator in every
    /// region that `MultiRegionNetworkEmulationTest` will set up. Returns the
    /// first empty region if any.
    pub fn first_empty_region(&self) -> Option<Region> {
        Region::ORDERED
            .iter()
            .find(|r| !self.validators.iter().any(|v| v.region == **r))
            .copied()
    }
}

// Re-export so callers don't need to spell `mainnet_mirror::MainnetMirrorSnapshot`.
// (Pub use lives in lib.rs.)

impl std::fmt::Debug for MainnetMirrorSnapshot {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MainnetMirrorSnapshot")
            .field("validator_count", &self.validators.len())
            .field("region_counts", &self.region_counts())
            .finish()
    }
}

// guard against forgetting to update this if the chaos region ordering ever
// changes — this is a const-time check that we have exactly 6 regions.
const _: [(); 6] = [(); Region::ORDERED.len()];

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_temp_snapshot(json: &str) -> tempfile::NamedTempFile {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        f.write_all(json.as_bytes()).unwrap();
        f
    }

    #[test]
    fn loads_and_filters() {
        let json = r#"{
            "validators": [
                {"peer_id": "0xa", "voting_power": "100", "region": "us-central1"},
                {"peer_id": "0xb", "voting_power": "0",   "region": "us-central1"},
                {"peer_id": "0xc", "voting_power": "200", "region": "unknown"},
                {"peer_id": "0xd", "voting_power": "300", "region": "eu-west-1"},
                {"peer_id": "0xe", "voting_power": "150", "region": "apne1"}
            ]
        }"#;
        let f = write_temp_snapshot(json);
        let snap = MainnetMirrorSnapshot::load(f.path()).unwrap();

        // 0xb (zero stake) and 0xc (unknown region) dropped.
        assert_eq!(snap.validator_count(), 3);

        // Order is (region in Region::ORDERED order, stake desc).
        // Region::ORDERED: Apne1, EuCentral1, EuWest1, SaEast1, CaCentral1, UsCentral1.
        // So expected order: 0xe (apne1), 0xd (eu-west-1), 0xa (us-central1).
        let peers: Vec<&str> = snap
            .validators()
            .iter()
            .map(|v| v.peer_id.as_str())
            .collect();
        assert_eq!(peers, vec!["0xe", "0xd", "0xa"]);

        // Stakes match.
        assert_eq!(snap.stake_amounts(), vec![150, 300, 100]);
    }

    #[test]
    fn region_weights_sum_to_one_and_match_order() {
        let json = r#"{
            "validators": [
                {"peer_id": "0xa", "voting_power": "1", "region": "us-central1"},
                {"peer_id": "0xb", "voting_power": "1", "region": "us-central1"},
                {"peer_id": "0xc", "voting_power": "1", "region": "eu-west-1"},
                {"peer_id": "0xd", "voting_power": "1", "region": "apne1"}
            ]
        }"#;
        let f = write_temp_snapshot(json);
        let snap = MainnetMirrorSnapshot::load(f.path()).unwrap();

        let weights = snap.region_weights();
        assert_eq!(weights.len(), 6);
        // Order: Apne1, EuCentral1, EuWest1, SaEast1, CaCentral1, UsCentral1.
        assert_eq!(weights[0], 0.25); // apne1: 1/4
        assert_eq!(weights[1], 0.0); // eu-central1: 0
        assert_eq!(weights[2], 0.25); // eu-west-1: 1/4
        assert_eq!(weights[3], 0.0); // sa-east-1: 0
        assert_eq!(weights[4], 0.0); // ca-central-1: 0
        assert_eq!(weights[5], 0.5); // us-central1: 2/4
        let sum: f64 = weights.iter().sum();
        assert!((sum - 1.0).abs() < 1e-9);
    }

    #[test]
    fn first_empty_region_flags_gaps() {
        let json = r#"{
            "validators": [
                {"peer_id": "0xa", "voting_power": "1", "region": "us-central1"}
            ]
        }"#;
        let f = write_temp_snapshot(json);
        let snap = MainnetMirrorSnapshot::load(f.path()).unwrap();
        // Apne1 is the first in ORDERED and has zero entries.
        assert_eq!(snap.first_empty_region(), Some(Region::Apne1));
    }

    #[test]
    fn rejects_empty_snapshot() {
        let json = r#"{"validators": []}"#;
        let f = write_temp_snapshot(json);
        assert!(MainnetMirrorSnapshot::load(f.path()).is_err());
    }

    /// Verify the bundled snapshot at `mainnet-mirror-data/mainnet_validator_snapshot.json`
    /// parses cleanly and produces sensible aggregate stats. This runs unconditionally
    /// because the snapshot is `include_str!`-embedded, so build = file present.
    #[test]
    fn loads_embedded_snapshot() {
        let snap = MainnetMirrorSnapshot::load_embedded().expect("load_embedded");
        eprintln!("{:#?}", snap);
        let total_octa: u128 = snap.stake_amounts().iter().map(|s| *s as u128).sum();
        eprintln!("total stake: {} APT", total_octa / 100_000_000);
        // Today: 108 raw entries, 2 in `unknown` region (Kraken pair) → 106 active.
        // We sanity-check bounds rather than an exact value; the snapshot drifts as
        // validators join/leave between pulls.
        assert!(snap.validator_count() >= 80 && snap.validator_count() <= 200);
        let weights = snap.region_weights();
        let sum: f64 = weights.iter().sum();
        assert!(
            (sum - 1.0).abs() < 1e-9,
            "weights should sum to 1, got {}",
            sum
        );
    }
}
