processed 3 tasks

task 0 'print-bytecode'. lines 1-10:
// Move bytecode v4
script {


main() {
L0:	loc0: u64
L1:	loc1: &mut u64
B0:
	0: LdU64(3)
	1: StLoc[0](loc0: u64)
	2: MutBorrowLoc[0](loc0: u64)
	3: StLoc[1](loc1: &mut u64)
	4: LdU64(42)
	5: MoveLoc[1](loc1: &mut u64)
	6: WriteRef
	7: Ret
}
}

task 1 'print-bytecode'. lines 12-23:
// Move bytecode v4
module 3d.Foobar {
struct FooCoin {
	value: u64
}

public borrow_mut_field(loc0: &mut FooCoin) {
B0:
	0: MoveLoc[0](Arg0: &mut FooCoin)
	1: MutBorrowField[0](FooCoin.value: u64)
	2: StLoc[1](loc0: &mut u64)
	3: MoveLoc[1](loc0: &mut u64)
	4: Pop
	5: Ret
}
}

task 2 'print-bytecode'. lines 25-36:
// Move bytecode v4
module 4d.Foobar {
struct FooCoin<Ty0> {
	value: u64
}

public borrow_mut_field(loc0: &mut FooCoin<address>) {
B0:
	0: MoveLoc[0](Arg0: &mut FooCoin<address>)
	1: MutBorrowFieldGeneric[0](FooCoin.value: u64)
	2: StLoc[1](loc0: &mut u64)
	3: MoveLoc[1](loc0: &mut u64)
	4: Pop
	5: Ret
}
}
