processed 3 tasks

task 0 'print-bytecode'. lines 1-18:
// Move bytecode v4
module 1d12.M {
struct T {
	b: bool
}

new(): T {
B0:
	0: LdTrue
	1: Pack[0](T)
	2: Ret
}
f() {
L0:	loc0: T
L1:	loc1: bool
B0:
	0: Call[0](new(): T)
	1: StLoc[0](loc0: T)
	2: MoveLoc[0](loc0: T)
	3: Unpack[0](T)
	4: StLoc[1](loc1: bool)
	5: Ret
}
}

task 2 'print-bytecode'. lines 31-44:
Error: Missing struct definition for T
