Move prover returns: exiting with bytecode transformation errors
error: Public or script functions cannot delegate invariants
   ┌─ tests/sources/functional/disable_inv.move:11:5
   │
11 │ ╭     public fun f1_incorrect(s: &signer) {
12 │ │         move_to(s, R1 {});
13 │ │         move_to(s, R2 {});
14 │ │     }
   │ ╰─────^

error: Functions must not have a disable invariant pragma when invariants are disabled in a transitive caller or there is a pragma delegate_invariants_to_caller
   ┌─ tests/sources/functional/disable_inv.move:31:5
   │
31 │ ╭     fun f3_incorrect(s: &signer) {
32 │ │         move_to(s, R1 {});
33 │ │     }
   │ ╰─────^

error: Functions must not have a disable invariant pragma when invariants are disabled in a transitive caller or there is a pragma delegate_invariants_to_caller
   ┌─ tests/sources/functional/disable_inv.move:46:5
   │
46 │ ╭     fun f5_incorrect(s: &signer) {
47 │ │         move_to(s, R2 {});
48 │ │     }
   │ ╰─────^
