Move prover returns: exiting with verification errors
error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:34:5
   │
34 │ ╭     invariant
35 │ │         exists<S::Storage<u64, bool>>(@0x22)
36 │ │             ==> global<S::Storage<u64, bool>>(@0x22).x == 1;
   │ ╰────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:10: publish_u64_bool
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:11: publish_u64_bool
   =     at tests/sources/functional/generic_invariants.move:34

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:39:5
   │
39 │ ╭     invariant<Y>
40 │ │         exists<S::Storage<u64, Y>>(@0x23)
41 │ │             ==> global<S::Storage<u64, Y>>(@0x23).x > 0;
   │ ╰────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:10: publish_u64_bool
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:11: publish_u64_bool
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:44:5
   │
44 │ ╭     invariant<X>
45 │ │         exists<S::Storage<X, bool>>(@0x24)
46 │ │             ==> global<S::Storage<X, bool>>(@0x24).y;
   │ ╰─────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:10: publish_u64_bool
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:11: publish_u64_bool
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39
   =     at tests/sources/functional/generic_invariants.move:44

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:49:5
   │
49 │ ╭     invariant<X, Y>
50 │ │         (exists<S::Storage<X, Y>>(@0x25) && exists<S::Storage<X, Y>>(@0x26))
51 │ │             ==> global<S::Storage<X, Y>>(@0x25) == global<S::Storage<X, Y>>(@0x26);
   │ ╰───────────────────────────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:10: publish_u64_bool
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:11: publish_u64_bool
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39
   =     at tests/sources/functional/generic_invariants.move:44
   =     at tests/sources/functional/generic_invariants.move:49

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:39:5
   │
39 │ ╭     invariant<Y>
40 │ │         exists<S::Storage<u64, Y>>(@0x23)
41 │ │             ==> global<S::Storage<u64, Y>>(@0x23).x > 0;
   │ ╰────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:15: publish_u64_y
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:16: publish_u64_y
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:49:5
   │
49 │ ╭     invariant<X, Y>
50 │ │         (exists<S::Storage<X, Y>>(@0x25) && exists<S::Storage<X, Y>>(@0x26))
51 │ │             ==> global<S::Storage<X, Y>>(@0x25) == global<S::Storage<X, Y>>(@0x26);
   │ ╰───────────────────────────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:15: publish_u64_y
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:16: publish_u64_y
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39
   =     at tests/sources/functional/generic_invariants.move:44
   =     at tests/sources/functional/generic_invariants.move:49

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:34:5
   │
34 │ ╭     invariant
35 │ │         exists<S::Storage<u64, bool>>(@0x22)
36 │ │             ==> global<S::Storage<u64, bool>>(@0x22).x == 1;
   │ ╰────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:15: publish_u64_y
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:16: publish_u64_y
   =     at tests/sources/functional/generic_invariants.move:34

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:44:5
   │
44 │ ╭     invariant<X>
45 │ │         exists<S::Storage<X, bool>>(@0x24)
46 │ │             ==> global<S::Storage<X, bool>>(@0x24).y;
   │ ╰─────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:15: publish_u64_y
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:16: publish_u64_y
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39
   =     at tests/sources/functional/generic_invariants.move:44

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:44:5
   │
44 │ ╭     invariant<X>
45 │ │         exists<S::Storage<X, bool>>(@0x24)
46 │ │             ==> global<S::Storage<X, bool>>(@0x24).y;
   │ ╰─────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:20: publish_x_bool
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:21: publish_x_bool
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39
   =     at tests/sources/functional/generic_invariants.move:44

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:49:5
   │
49 │ ╭     invariant<X, Y>
50 │ │         (exists<S::Storage<X, Y>>(@0x25) && exists<S::Storage<X, Y>>(@0x26))
51 │ │             ==> global<S::Storage<X, Y>>(@0x25) == global<S::Storage<X, Y>>(@0x26);
   │ ╰───────────────────────────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:20: publish_x_bool
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:21: publish_x_bool
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39
   =     at tests/sources/functional/generic_invariants.move:44
   =     at tests/sources/functional/generic_invariants.move:49

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:34:5
   │
34 │ ╭     invariant
35 │ │         exists<S::Storage<u64, bool>>(@0x22)
36 │ │             ==> global<S::Storage<u64, bool>>(@0x22).x == 1;
   │ ╰────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:20: publish_x_bool
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:21: publish_x_bool
   =     at tests/sources/functional/generic_invariants.move:34

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:39:5
   │
39 │ ╭     invariant<Y>
40 │ │         exists<S::Storage<u64, Y>>(@0x23)
41 │ │             ==> global<S::Storage<u64, Y>>(@0x23).x > 0;
   │ ╰────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:20: publish_x_bool
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:21: publish_x_bool
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:49:5
   │
49 │ ╭     invariant<X, Y>
50 │ │         (exists<S::Storage<X, Y>>(@0x25) && exists<S::Storage<X, Y>>(@0x26))
51 │ │             ==> global<S::Storage<X, Y>>(@0x25) == global<S::Storage<X, Y>>(@0x26);
   │ ╰───────────────────────────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:25: publish_x_y
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:26: publish_x_y
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39
   =     at tests/sources/functional/generic_invariants.move:44
   =     at tests/sources/functional/generic_invariants.move:49

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:34:5
   │
34 │ ╭     invariant
35 │ │         exists<S::Storage<u64, bool>>(@0x22)
36 │ │             ==> global<S::Storage<u64, bool>>(@0x22).x == 1;
   │ ╰────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:25: publish_x_y
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:26: publish_x_y
   =     at tests/sources/functional/generic_invariants.move:34

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:39:5
   │
39 │ ╭     invariant<Y>
40 │ │         exists<S::Storage<u64, Y>>(@0x23)
41 │ │             ==> global<S::Storage<u64, Y>>(@0x23).x > 0;
   │ ╰────────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:25: publish_x_y
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:26: publish_x_y
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39

error: global memory invariant does not hold
   ┌─ tests/sources/functional/generic_invariants.move:44:5
   │
44 │ ╭     invariant<X>
45 │ │         exists<S::Storage<X, bool>>(@0x24)
46 │ │             ==> global<S::Storage<X, bool>>(@0x24).y;
   │ ╰─────────────────────────────────────────────────────^
   │
   =     at tests/sources/functional/generic_invariants.move:25: publish_x_y
   =         account = <redacted>
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/generic_invariants.move:26: publish_x_y
   =     at tests/sources/functional/generic_invariants.move:34
   =     at tests/sources/functional/generic_invariants.move:39
   =     at tests/sources/functional/generic_invariants.move:44
