Move prover returns: exiting with boogie verification errors
error: abort not covered by any of the `aborts_if` clauses
   ┌─ tests/sources/functional/script_incorrect.move:10:1
   │
10 │ ╭ spec main {
11 │ │     pragma verify = true;
12 │ │     aborts_if false;
13 │ │ }
   │ ╰─^
   │
   ┌─ tests/sources/functional/script_provider.move:18:9
   │
18 │         assert(Signer::address_of(account) == @0x1, 1);
   │         ---------------------------------------------- abort happened here with code 0x1
   │
   =     at tests/sources/functional/script_incorrect.move:6: main
   =         account = <redacted>
   =     at tests/sources/functional/script_incorrect.move:7: main
   =     at tests/sources/functional/script_provider.move:17: register
   =         account = <redacted>
   =     at tests/sources/functional/script_provider.move:18: register
   =     at ../move-stdlib/sources/Signer.move:12: address_of
   =         s = <redacted>
   =     at ../move-stdlib/sources/Signer.move:13: address_of
   =         result = <redacted>
   =     at ../move-stdlib/sources/Signer.move:14: address_of
   =         <redacted> = <redacted>
   =     at tests/sources/functional/script_provider.move:18: register
   =         ABORTED
