processed 9 tasks

task 0 'run'. lines 1-7:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 1 'run'. lines 9-14:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2 'run'. lines 16-21:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'run'. lines 25-30:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 4 'run'. lines 32-37:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 5 'run'. lines 39-44:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 6 'publish'. lines 48-56:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7 'publish'. lines 58-66:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 8 'publish'. lines 68-76:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
