processed 5 tasks

task 0 'run'. lines 1-6:
Error: Script execution failed with VMError: {
    major_status: INVALID_MAIN_FUNCTION_SIGNATURE,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [],
}

task 1 'run'. lines 9-13:
Error: Script execution failed with VMError: {
    major_status: INVALID_MAIN_FUNCTION_SIGNATURE,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [],
}

task 2 'run'. lines 16-20:
Error: Script execution failed with VMError: {
    major_status: INVALID_MAIN_FUNCTION_SIGNATURE,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [],
}

task 4 'run'. lines 29-35:
Error: Script execution failed with VMError: {
    major_status: INVALID_MAIN_FUNCTION_SIGNATURE,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [],
}
