processed 2 tasks

task 0 'run'. lines 1-6:
Error: Script execution failed with VMError: {
    major_status: INVALID_MAIN_FUNCTION_SIGNATURE,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [],
}

task 1 'run'. lines 8-13:
Error: Script execution failed with VMError: {
    major_status: INVALID_MAIN_FUNCTION_SIGNATURE,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [],
}
