processed 3 tasks

task 0 'run'. lines 1-5:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 1 'run'. lines 7-11:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 2 'run'. lines 13-17:
Error: Script execution failed with VMError: {
    major_status: INVALID_MAIN_FUNCTION_SIGNATURE,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [],
}
