# Config to import transactions onchain.
# Set the X_API_KEY environment variable to authenticate with the API.
# Alternatively, set api_key per-network below to override the env var.
mainnet:
  # Transaction Stream endpoint address.
  transaction_stream_endpoint: https://grpc.mainnet.aptoslabs.com:443
  # A map from versions to dump and their output names.
  versions_to_import: {
    # example:
    # 123: "example_transaction"
  }

# testnet:
#   transaction_stream_endpoint: https://grpc.testnet.aptoslabs.com:443
#   versions_to_import: {
#   }
