import_config:
  # Set the X_API_KEY environment variable to authenticate with the API.
  # Alternatively, set api_key per-network below to override the env var.
  testnet:
    # Transaction Stream endpoint address.
    transaction_stream_endpoint: https://grpc.testnet.aptoslabs.com:443
    # A map from versions to dump and their output names.
    versions_to_import:
      123: testnet_v1.json
  # mainnet:
  #   # Transaction Stream endpoint address.
  #   transaction_stream_endpoint: https://grpc.mainnet.aptoslabs.com:443
  #   versions_to_import:
  #     123: mainnetnet_v1.json
  # devnet:
  #   # Transaction Stream endpoint address.
  #   transaction_stream_endpoint: https://grpc.devnet.aptoslabs.com:443
  #   versions_to_import:
  #     123: devnet_v1.json
  # custom:
  #   # Transaction Stream endpoint address.
  #   transaction_stream_endpoint: YOUR_CUSTOM_ENDPOINT
  #   versions_to_import:
  #     123: custom_v1.json
