processed 5 tasks

task 1 'publish'. lines 4-31:
warning[W09003]: unused assignment
   ┌─ TEMPFILE:15:13
   │
15 │         let x = 3;
   │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning: unused assignment
   ┌─ TEMPFILE:15:13
   │
15 │         let x = 3;
   │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')



task 2 'run'. lines 33-33:
Events:
{
    type:    0x1::transaction_fee::FeeStatement
    data:    "30000000000000000300000000000000010000000000000030ac0000000000000000000000000000"
}mutable inputs after call: local#0: 0
return values: 0

task 3 'run'. lines 35-35:
Events:
{
    type:    0x1::transaction_fee::FeeStatement
    data:    "05000000000000000300000000000000020000000000000018010000000000000000000000000000"
}mutable inputs after call: local#0: 0
return values: 0

task 4 'view'. lines 37-37:
store key 0xf75daa73fc071f93593335eb9033da804777eb94491650dd3f095ce6f778acb6::hello_world::ModuleData {
    global_counter: 0
    state: copy drop store 0x1::string::String {
        bytes: 68656c6c6f20776f726c64
    }
}
