processed 9 tasks

task 0 'run'. lines 1-6:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 1 'run'. lines 8-12:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2 'run'. lines 14-18:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'run'. lines 22-26:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 4 'run'. lines 28-32:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 5 'run'. lines 34-38:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 6 'publish'. lines 42-49:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7 'publish'. lines 51-58:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 8 'publish'. lines 60-67:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
