processed 191 tasks

task 0 'run'. lines 1-10:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 1 'run'. lines 13-17:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2 'run'. lines 20-24:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 3 'run'. lines 27-31:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 4 'run'. lines 34-38:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 5 'run'. lines 41-45:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 6 'run'. lines 48-52:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7 'run'. lines 55-59:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 8 'run'. lines 62-66:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 9 'run'. lines 69-73:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 10 'run'. lines 76-80:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 11 'run'. lines 83-87:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 12 'publish'. lines 90-97:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 13 'publish'. lines 99-106:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 14 'publish'. lines 108-119:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 15 'run'. lines 120-124:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 16 'run'. lines 127-131:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 17 'run'. lines 134-138:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 18 'run'. lines 141-145:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 19 'run'. lines 148-152:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 20 'run'. lines 155-159:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 21 'run'. lines 162-166:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 22 'run'. lines 169-173:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 23 'run'. lines 176-180:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 24 'run'. lines 183-187:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 25 'run'. lines 190-194:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 26 'run'. lines 197-201:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 27 'publish'. lines 204-211:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 28 'publish'. lines 213-220:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 29 'publish'. lines 222-233:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 30 'run'. lines 234-238:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 31 'run'. lines 241-245:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 32 'run'. lines 248-252:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 33 'run'. lines 255-259:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 34 'run'. lines 262-266:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 35 'run'. lines 269-273:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 36 'run'. lines 276-280:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 37 'run'. lines 283-287:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 38 'run'. lines 290-294:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 39 'run'. lines 297-301:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 40 'run'. lines 304-308:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 41 'run'. lines 311-315:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 42 'publish'. lines 318-325:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 43 'publish'. lines 327-334:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 44 'publish'. lines 336-347:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 45 'run'. lines 348-352:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 46 'run'. lines 355-359:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 47 'run'. lines 362-366:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 48 'run'. lines 369-373:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 49 'run'. lines 376-380:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 50 'run'. lines 383-387:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 51 'run'. lines 390-394:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 52 'run'. lines 397-401:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 53 'run'. lines 404-408:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 54 'run'. lines 411-415:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 55 'run'. lines 418-422:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 56 'run'. lines 425-429:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 57 'publish'. lines 432-439:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 58 'publish'. lines 441-448:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 59 'publish'. lines 450-461:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 60 'run'. lines 462-466:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 61 'run'. lines 469-473:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 62 'run'. lines 476-480:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 63 'run'. lines 483-487:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 64 'run'. lines 490-494:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 65 'run'. lines 497-501:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 66 'run'. lines 504-508:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 67 'run'. lines 511-515:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 68 'run'. lines 518-522:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 69 'run'. lines 525-529:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 70 'run'. lines 532-536:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 71 'run'. lines 539-543:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 72 'publish'. lines 546-553:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 73 'publish'. lines 555-562:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 74 'publish'. lines 564-575:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 75 'run'. lines 576-580:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 76 'run'. lines 583-587:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 77 'run'. lines 590-594:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 78 'run'. lines 597-601:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 79 'run'. lines 604-608:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 80 'run'. lines 611-615:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 81 'run'. lines 618-622:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 82 'run'. lines 625-629:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 83 'run'. lines 632-636:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 84 'run'. lines 639-643:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 85 'run'. lines 646-650:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 86 'run'. lines 653-657:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 87 'publish'. lines 660-667:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 88 'publish'. lines 669-676:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 89 'publish'. lines 678-689:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 90 'run'. lines 690-694:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 91 'run'. lines 697-701:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 92 'run'. lines 704-708:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 93 'run'. lines 711-715:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 94 'run'. lines 718-722:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 95 'run'. lines 725-729:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 96 'run'. lines 732-736:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 97 'run'. lines 739-743:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 98 'run'. lines 746-750:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 99 'run'. lines 753-757:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 100 'run'. lines 760-764:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 101 'run'. lines 767-771:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 102 'publish'. lines 774-781:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 103 'publish'. lines 783-790:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 104 'publish'. lines 792-803:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 105 'run'. lines 804-808:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 106 'run'. lines 811-815:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 107 'run'. lines 818-822:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 108 'run'. lines 825-829:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 109 'run'. lines 832-836:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 110 'run'. lines 839-843:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 111 'run'. lines 846-850:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 112 'run'. lines 853-857:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 113 'run'. lines 860-864:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 114 'run'. lines 867-871:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 115 'publish'. lines 874-881:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 116 'publish'. lines 883-893:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 117 'run'. lines 894-898:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 118 'run'. lines 901-905:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 119 'run'. lines 908-912:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 120 'run'. lines 915-919:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 121 'run'. lines 922-926:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 122 'run'. lines 929-933:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 123 'run'. lines 936-940:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 124 'run'. lines 943-947:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 125 'run'. lines 950-954:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 126 'run'. lines 957-961:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 127 'publish'. lines 964-971:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 128 'publish'. lines 973-984:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 129 'run'. lines 985-989:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 130 'run'. lines 992-996:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 131 'run'. lines 999-1003:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 132 'run'. lines 1006-1010:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 133 'run'. lines 1013-1017:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 134 'run'. lines 1020-1024:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 135 'run'. lines 1027-1031:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 136 'run'. lines 1034-1038:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 137 'run'. lines 1041-1045:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 138 'run'. lines 1048-1055:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 139 'run'. lines 1056-1060:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 140 'run'. lines 1063-1067:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 141 'run'. lines 1070-1074:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 142 'run'. lines 1077-1081:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 143 'run'. lines 1084-1088:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 144 'run'. lines 1091-1095:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 145 'run'. lines 1098-1102:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 146 'run'. lines 1105-1109:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 147 'run'. lines 1112-1116:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 148 'run'. lines 1119-1126:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 149 'run'. lines 1127-1131:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 150 'run'. lines 1134-1138:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 151 'run'. lines 1141-1145:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 152 'run'. lines 1148-1152:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 153 'run'. lines 1155-1159:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 154 'run'. lines 1162-1166:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 155 'run'. lines 1169-1173:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 156 'run'. lines 1176-1180:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 157 'run'. lines 1183-1187:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 158 'run'. lines 1190-1197:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 159 'run'. lines 1198-1202:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 160 'run'. lines 1205-1209:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 161 'run'. lines 1212-1216:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 162 'run'. lines 1219-1223:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 163 'run'. lines 1226-1230:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 164 'run'. lines 1233-1237:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 165 'run'. lines 1240-1244:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 166 'run'. lines 1247-1251:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 167 'run'. lines 1254-1258:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 168 'run'. lines 1261-1268:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 169 'run'. lines 1269-1273:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 170 'run'. lines 1276-1280:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 171 'run'. lines 1283-1287:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 172 'run'. lines 1290-1294:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 173 'run'. lines 1297-1301:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 174 'run'. lines 1304-1308:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 175 'run'. lines 1311-1315:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 176 'run'. lines 1318-1322:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 177 'publish'. lines 1325-1332:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 178 'publish'. lines 1334-1341:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 179 'publish'. lines 1343-1354:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 180 'run'. lines 1355-1359:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 181 'run'. lines 1362-1366:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 182 'run'. lines 1369-1373:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 183 'run'. lines 1376-1380:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 184 'run'. lines 1383-1387:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 185 'run'. lines 1390-1394:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 186 'run'. lines 1397-1401:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 187 'run'. lines 1404-1408:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 188 'publish'. lines 1411-1418:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 189 'publish'. lines 1420-1427:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 190 'publish'. lines 1429-1436:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}
