processed 2 tasks

task 0 'publish'. lines 1-11:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: READREF_WITHOUT_COPY_ABILITY,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 1 'publish'. lines 13-23:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: READREF_WITHOUT_COPY_ABILITY,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 5)],
}
