processed 5 tasks

task 0 'publish'. lines 1-11:
Error: Unable to publish module '00000000000000000000000000000001::M1'. Got VMError: {
    major_status: UNSAFE_RET_UNUSED_VALUES_WITHOUT_DROP,
    sub_status: None,
    location: 0x1::M1,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 1 'publish'. lines 13-23:
Error: Unable to publish module '00000000000000000000000000000001::M2'. Got VMError: {
    major_status: STLOC_UNSAFE_TO_DESTROY_ERROR,
    sub_status: None,
    location: 0x1::M2,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2 'publish'. lines 25-34:
Error: Unable to publish module '00000000000000000000000000000001::M3'. Got VMError: {
    major_status: READREF_WITHOUT_COPY_ABILITY,
    sub_status: None,
    location: 0x1::M3,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'publish'. lines 36-46:
Error: Unable to publish module '00000000000000000000000000000001::M4'. Got VMError: {
    major_status: WRITEREF_WITHOUT_DROP_ABILITY,
    sub_status: None,
    location: 0x1::M4,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 4 'publish'. lines 48-57:
Error: Unable to publish module '00000000000000000000000000000001::M5'. Got VMError: {
    major_status: COPYLOC_WITHOUT_COPY_ABILITY,
    sub_status: None,
    location: 0x1::M5,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}
