processed 3 tasks
task 1 lines 4-5:  publish --private-key alice [module alice::test_friend_caller {}]
task 2 lines 7-26:  publish --private-key alice [module alice::entry_points_safety {]
warning: public(friend) entry functions are not private. Anyone can call these functions directly thanks to the 'entry' modifier. Add #[lint::allow_unsafe_friend_entry] to ignore this check.
   ┌─ TEMPFILE1:11:5
   │
11 │     public(friend) entry fun unsafe_friend_entry() {}
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


