processed 2 tasks
task 1 lines 4-27:  publish --private-key alice [module alice::entry_points_safety {]
warning: public(package) entry functions are not private. Anyone can call these functions directly thanks to the 'entry' modifier. Add #[lint::allow_unsafe_package_entry] to ignore this check.
  ┌─ TEMPFILE:7:5
  │  
7 │ ╭     public(package) entry fun unsafe_package_entry() {
8 │ │     }
  │ ╰─────^


