processed 4 tasks
task 1 lines 3-8:  publish --private-key Alice [module 0xf75daa73fc071f93593335eb9033da804777eb94491650dd3f095ce6f778acb6::target]
task 2 lines 10-47:  publish --private-key Alice [module 0xf75daa73fc071f93593335eb9033da804777eb94491650dd3f095ce6f778acb6::test_module]
Error: VMError with status CONSTRAINT_NOT_SATISFIED at location Module ModuleId { address: f75daa73fc071f93593335eb9033da804777eb94491650dd3f095ce6f778acb6, name: Identifier("test_module") } and message function type has invalid abilities: only copy, drop, and store are allowed at type 0 at index 5 for signature
task 3 lines 50-50:  run --signers Alice -- 0xf75daa73fc071f93593335eb9033da804777eb94491650dd3f095ce6f778acb6::test_module::key_ability_rejected
Error: Failed to execute transaction. ExecutionStatus: MiscellaneousError(Some(LINKER_ERROR))
