CompiledPackageInfo {
    package_name: "Root",
    address_alias_instantiation: {
        "A": 00000000000000000000000000000001,
    },
    module_resolution_metadata: {
        ModuleId {
            address: 00000000000000000000000000000001,
            name: Identifier(
                "B",
            ),
        }: "A",
        ModuleId {
            address: 00000000000000000000000000000001,
            name: Identifier(
                "Example",
            ),
        }: "A",
        ModuleId {
            address: 00000000000000000000000000000001,
            name: Identifier(
                "OneDep",
            ),
        }: "A",
    },
    source_digest: Some(
        "ELIDED_FOR_TEST",
    ),
}
