no_threads="--features=blst/no-threads"

cargo bench $no_threads -- "hash"

cargo bench $no_threads -- "bls12381/sig_deserialize"
cargo bench $no_threads -- "bls12381/pk_deserialize"
cargo bench $no_threads -- "bls12381/pk_prime_order_subgroup_check"
cargo bench $no_threads -- "bls12381/sig_prime_order_subgroup_check"
cargo bench $no_threads -- "bls12381/aggregate_pks/1024"
cargo bench $no_threads -- "bls12381/aggregate_sigshare/1024"
cargo bench $no_threads -- "bls12381/pop_verify"

cargo bench -- "ed25519/pk_deserialize"
cargo bench -- "ed25519/small_subgroup_check"
cargo bench -- "ed25519/sig_deserialize"
cargo bench -- "ed25519/sig_verify_zero_bytes"

cargo bench -- "secp256k1/ecdsa_recover"

cargo bench -- "ristretto255/basepoint_mul"
cargo bench -- "ristretto255/basepoint_double_mul"
cargo bench -- "ristretto255/point_add"
#cargo bench -- "ristretto255/point_clone"
cargo bench -- "ristretto255/point_compress"
cargo bench -- "ristretto255/point_decompress"
cargo bench -- "ristretto255/point_equals"
cargo bench -- "ristretto255/point_from_64_uniform_bytes"
cargo bench -- "ristretto255/point_identity"
cargo bench -- "ristretto255/point_mul"
cargo bench -- "ristretto255/point_neg"
cargo bench -- "ristretto255/point_sub"
#cargo bench -- "ristretto255/point_parse_arg"
cargo bench -- "ristretto255/scalar_add"
cargo bench -- "ristretto255/scalar_reduced_from_32_bytes"
cargo bench -- "ristretto255/scalar_uniform_from_64_bytes"
cargo bench -- "ristretto255/scalar_from_u128"
cargo bench -- "ristretto255/scalar_from_u64"
cargo bench -- "ristretto255/scalar_invert"
cargo bench -- "ristretto255/scalar_is_canonical"
cargo bench -- "ristretto255/scalar_mul"
cargo bench -- "ristretto255/scalar_neg"
cargo bench -- "ristretto255/scalar_sub"
#cargo bench -- "ristretto255/scalar_parse_arg"