# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/it1_profiles', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # It1Profile. As you add validations to It1Profile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      It1Profile.create! valid_attributes
      get it1_profiles_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      it1_profile = It1Profile.create! valid_attributes
      get it1_profile_url(it1_profile)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_it1_profile_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      it1_profile = It1Profile.create! valid_attributes
      get edit_it1_profile_url(it1_profile)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new It1Profile' do
        expect do
          post it1_profiles_url, params: { it1_profile: valid_attributes }
        end.to change(It1Profile, :count).by(1)
      end

      it 'redirects to the created it1_profile' do
        post it1_profiles_url, params: { it1_profile: valid_attributes }
        expect(response).to redirect_to(it1_profile_url(It1Profile.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new It1Profile' do
        expect do
          post it1_profiles_url, params: { it1_profile: invalid_attributes }
        end.to change(It1Profile, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post it1_profiles_url, params: { it1_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested it1_profile' do
        it1_profile = It1Profile.create! valid_attributes
        patch it1_profile_url(it1_profile), params: { it1_profile: new_attributes }
        it1_profile.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the it1_profile' do
        it1_profile = It1Profile.create! valid_attributes
        patch it1_profile_url(it1_profile), params: { it1_profile: new_attributes }
        it1_profile.reload
        expect(response).to redirect_to(it1_profile_url(it1_profile))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        it1_profile = It1Profile.create! valid_attributes
        patch it1_profile_url(it1_profile), params: { it1_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested it1_profile' do
      it1_profile = It1Profile.create! valid_attributes
      expect do
        delete it1_profile_url(it1_profile)
      end.to change(It1Profile, :count).by(-1)
    end

    it 'redirects to the it1_profiles list' do
      it1_profile = It1Profile.create! valid_attributes
      delete it1_profile_url(it1_profile)
      expect(response).to redirect_to(it1_profiles_url)
    end
  end
end
