require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/proposals", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Proposal. As you add validations to Proposal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Proposal.create! valid_attributes
      get proposals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      proposal = Proposal.create! valid_attributes
      get proposal_url(proposal)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_proposal_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      proposal = Proposal.create! valid_attributes
      get edit_proposal_url(proposal)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Proposal" do
        expect {
          post proposals_url, params: { proposal: valid_attributes }
        }.to change(Proposal, :count).by(1)
      end

      it "redirects to the created proposal" do
        post proposals_url, params: { proposal: valid_attributes }
        expect(response).to redirect_to(proposal_url(Proposal.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Proposal" do
        expect {
          post proposals_url, params: { proposal: invalid_attributes }
        }.to change(Proposal, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post proposals_url, params: { proposal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested proposal" do
        proposal = Proposal.create! valid_attributes
        patch proposal_url(proposal), params: { proposal: new_attributes }
        proposal.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the proposal" do
        proposal = Proposal.create! valid_attributes
        patch proposal_url(proposal), params: { proposal: new_attributes }
        proposal.reload
        expect(response).to redirect_to(proposal_url(proposal))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        proposal = Proposal.create! valid_attributes
        patch proposal_url(proposal), params: { proposal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested proposal" do
      proposal = Proposal.create! valid_attributes
      expect {
        delete proposal_url(proposal)
      }.to change(Proposal, :count).by(-1)
    end

    it "redirects to the proposals list" do
      proposal = Proposal.create! valid_attributes
      delete proposal_url(proposal)
      expect(response).to redirect_to(proposals_url)
    end
  end
end
