name: Rust Check Merge Base
description: Runs the rust merge base freshness check
inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git. Useful if you need to pull private repos for dependencies"
    required: false

runs:
  using: composite
  steps:
    # The source code must be checked out by the workflow that invokes this action.
    - name: Setup git credentials
      if: inputs.GIT_CREDENTIALS != ''
      shell: bash
      run: |
        git config --global credential.helper store
        echo "${{ inputs.GIT_CREDENTIALS }}" > ~/.git-credentials

    # Check the freshness of the merge base
    - name: Check the freshness of the merge base
      run: |
        set -euo pipefail

        if [ -n "${GITHUB_BASE_REF:-}" ]; then
          git fetch --no-tags origin "$GITHUB_BASE_REF"
        fi

        cargo x check-merge-base -vvv
      shell: bash
