[package]
name = "VeiledCoin"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[addresses]
framework_experimental = "0x7"
