processed 17 tasks

task 3 'run'. lines 39-51:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 2055

task 6 'run'. lines 66-74:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 261

task 8 'run'. lines 123-136:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 2

task 9 'run'. lines 138-148:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 258

task 10 'run'. lines 150-159:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 258

task 11 'run'. lines 161-169:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 1539

task 12 'run'. lines 171-179:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 1539

task 13 'run'. lines 181-192:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 2568

task 15 'run'. lines 207-214:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 770

task 16 'run'. lines 216-228:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 1800
