Ok(
    [
        TransactionOutput {
            write_set: Value(
                V0(
                    WriteSetV0(
                        WriteSetMut {
                            write_set: {},
                        },
                    ),
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                SIGNERS_CONTAIN_DUPLICATES,
            ),
            auxiliary_data: None,
        },
    ],
)
