Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                TRANSACTION_EXPIRED,
            ),
            call_traces: [],
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                TRANSACTION_EXPIRED,
            ),
            call_traces: [],
        },
    ],
)
