Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                INVALID_AUTH_KEY,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                SEQUENCE_NUMBER_TOO_OLD,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                SEQUENCE_NUMBER_TOO_NEW,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                SENDING_ACCOUNT_DOES_NOT_EXIST,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                GAS_UNIT_PRICE_ABOVE_MAX_BOUND,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                MAX_GAS_UNITS_BELOW_MIN_TRANSACTION_GAS_UNITS,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                MAX_GAS_UNITS_EXCEEDS_MAX_GAS_UNITS_BOUND,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {},
                    },
                ),
            ),
            events: [],
            gas_used: 0,
            status: Discard(
                EXCEEDED_MAX_TRANSACTION_SIZE,
            ),
        },
    ],
)
Ok(
    [
        TransactionOutput {
            write_set: V0(
                WriteSetV0(
                    WriteSetMut {
                        write_set: {
                            AccessPath(
                                AccessPath { address: f5b9d6f01a99e74c790e2f330c092fa05455a8193f1dfc1b113ecc54d067afe1, path: 01000000000000000000000000000000000000000000000000000000000000000104636f696e09436f696e53746f7265010700000000000000000000000000000000000000000000000000000000000000010a6170746f735f636f696e094170746f73436f696e00 },
                            ): Modification(0abb0d00000000000000000000000000000000000000000000f5b9d6f01a99e74c790e2f330c092fa05455a8193f1dfc1b113ecc54d067afe100000000000000000000000000000000f5b9d6f01a99e74c790e2f330c092fa05455a8193f1dfc1b113ecc54d067afe1),
                            AccessPath(
                                AccessPath { address: f5b9d6f01a99e74c790e2f330c092fa05455a8193f1dfc1b113ecc54d067afe1, path: 010000000000000000000000000000000000000000000000000000000000000001076163636f756e74074163636f756e7400 },
                            ): Modification(20f5b9d6f01a99e74c790e2f330c092fa05455a8193f1dfc1b113ecc54d067afe10b00000000000000000000000000000000000000000000000000000000000000f5b9d6f01a99e74c790e2f330c092fa05455a8193f1dfc1b113ecc54d067afe100000000000000000100000000000000f5b9d6f01a99e74c790e2f330c092fa05455a8193f1dfc1b113ecc54d067afe10000),
                            TableItem {
                                handle: TableHandle(
                                    1b854694ae746cdbd8d44186ca4929b2b337df21d1c74633be19b2710552fdca,
                                ),
                                key: [
                                    6,
                                    25,
                                    220,
                                    41,
                                    160,
                                    170,
                                    200,
                                    250,
                                    20,
                                    103,
                                    20,
                                    5,
                                    142,
                                    141,
                                    214,
                                    210,
                                    208,
                                    243,
                                    189,
                                    245,
                                    246,
                                    51,
                                    25,
                                    7,
                                    191,
                                    145,
                                    243,
                                    172,
                                    216,
                                    30,
                                    105,
                                    53,
                                ],
                            }: Modification(69e0f505000000000100000000000000),
                        },
                    },
                ),
            ),
            events: [],
            gas_used: 150,
            status: Keep(
                MiscellaneousError(
                    Some(
                        NUMBER_OF_ARGUMENTS_MISMATCH,
                    ),
                ),
            ),
        },
    ],
)
