Ok(
    [
        TransactionOutput {
            write_set: WriteSet {
                value: V0(
                    WriteSetV0(
                        WriteSetMut {
                            write_set: {},
                        },
                    ),
                ),
                hotness: {},
                native_positions: {},
            },
            events: [],
            gas_used: 0,
            status: Discard(
                INVALID_SIGNATURE,
            ),
            auxiliary_data: None,
        },
    ],
)
