processed 4 tasks

task 1 'run'. lines 69-76:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 2 'run'. lines 79-86:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 3 'run'. lines 89-97:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}
