processed 5 tasks

task 1 'run'. lines 5-13:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 2567

task 2 'run'. lines 15-23:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 258

task 3 'run'. lines 25-33:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 6151

task 4 'run'. lines 35-43:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 258
