[package]
name = "aptos-indexer-grpc-convert"
description = "Conversion from Aptos API transaction types to indexer protobuf types."
version = "1.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
hex = { workspace = true }
serde_json = { workspace = true }

aptos-api-types = { workspace = true }
aptos-bitvec = { workspace = true }
aptos-logger = { workspace = true }
aptos-protos = { workspace = true }
aptos-types = { workspace = true }

move-core-types = { workspace = true }
