# frozen_string_literal: true

# Copyright (c) Aptos
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.2', '>= 7.0.3.1'

# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem 'propshaft'

# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem 'jsbundling-rails'

# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem 'cssbundling-rails'

# Use pg as the database for Active Record
gem 'dotenv-rails'
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Image generation! ImageMagick
gem 'rmagick'

gem 'activeadmin'
gem 'cancancan'
gem 'devise'
gem 'kaminari'

gem 'memery'

# Oauth
gem 'omniauth'
gem 'omniauth-discord'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# Discourse
gem 'discourse_api'

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

gem 'httparty'

# Address deriviation (sha_256)
gem 'sha3'

# Cryptography
gem 'ed25519', '~> 1.3'

# Zip files
gem 'rubyzip'

# IP -> GEO via MaxMind
gem 'maxmind-geoip2'

# Postgresql backed DelayedJob
gem 'delayed'

# mailchimp
# https://github.com/mailchimp/mailchimp-transactional-ruby/
gem 'MailchimpTransactional'

gem 'recaptcha', '~> 5.10'

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem 'google-cloud-storage', require: false
# gem 'image_processing'

# UI components
gem 'better_html'
gem 'view_component', '~> 2.54'

# Monitoring
gem 'lograge', '~> 0.12.0'
gem 'sentry-rails'
gem 'sentry-ruby'

# State machines
gem 'statesman', '~> 10.0'

# Feature flags
gem 'flipper', '~> 0.25.1'
gem 'flipper-active_record', '~> 0.25.1'
gem 'flipper-ui', '~> 0.25.1'

# Redis
gem 'hiredis', '~> 0.6.3'
gem 'redis', '~> 4.7'

# Medium/RSS
gem 'rss'

# Notifications
gem 'noticed', '~> 1.5'

# Search
gem 'pg_search', '~> 2.3'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]

  # linting/formatting
  gem 'erb_lint', require: false
  gem 'rubocop', require: false
  gem 'rubocop-rails'
  # security lints
  gem 'brakeman'
  gem 'bundler-audit', '~> 0.9.1'

  # Testing
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'mocha'
  gem 'rspec-rails'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end
