processed 11 tasks

task 5 'run'. lines 45-48:
Error: Failed to execute transaction. VMStatus: status ABORTED of type Execution with sub status 775

task 6 'run'. lines 49-52:
Error: Failed to execute transaction. VMStatus: status ABORTED of type Execution with sub status 1285

task 7 'run'. lines 53-58:
Error: Failed to execute transaction. VMStatus: status ABORTED of type Execution with sub status 1031

task 8 'run'. lines 59-64:
Error: Failed to execute transaction. VMStatus: status ABORTED of type Execution with sub status 1285

task 9 'run'. lines 65-70:
Error: Failed to execute transaction. VMStatus: status ABORTED of type Execution with sub status 519

task 10 'run'. lines 71-71:
Error: Failed to execute transaction. VMStatus: status ABORTED of type Execution with sub status 7
