processed 10 tasks

task 1 'block'. lines 3-7:
Events:
{
    key:     11000000000000000000000000000000000000000a550c18
    seq_num: 0
    type:    0x1::DiemBlock::NewBlockEvent
    data:    "0000000000000000c5e34b925cf6875fec02d4b77adbd2d6000300000000000000"
}

task 3 'block'. lines 29-29:
Events:
{
    key:     11000000000000000000000000000000000000000a550c18
    seq_num: 1
    type:    0x1::DiemBlock::NewBlockEvent
    data:    "0000000000000000c5e34b925cf6875fec02d4b77adbd2d6000400000000000000"
}

task 5 'run'. lines 39-47:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 5

task 6 'run'. lines 49-56:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 5

task 8 'run'. lines 67-74:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 6

task 9 'run'. lines 76-84:
Error: Transaction discarded. VMStatus: status ABORTED of type Execution with sub status 1
