-- Your SQL goes here


DROP DOMAIN IF EXISTS uint_64;
CREATE DOMAIN uint_64 AS NUMERIC(20, 0) NOT NULL
    CHECK (VALUE >= 0 AND VALUE <= 2^64)
    CHECK (SCALE(VALUE) = 0);

DROP DOMAIN IF EXISTS uint_128;
CREATE DOMAIN uint_128 AS NUMERIC(39, 0) NOT NULL
    CHECK (VALUE >= 0 AND VALUE <= 2^128)
    CHECK (SCALE(VALUE) = 0);

DROP DOMAIN IF EXISTS uint_256;
CREATE DOMAIN uint_256 AS NUMERIC(78, 0) NOT NULL
    CHECK (VALUE >= 0 AND VALUE <= 2^256)
    CHECK (SCALE(VALUE) = 0);
