{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testnet-addons.serviceAccountName" . }}
  labels:
{{ include "testnet-addons.labels" . | nindent 4 }}
  annotations:
    {{- if and (eq .Values.cloud "AKS") .Values.azure_genesis_storage.workloadIdentityClientId }}
    azure.workload.identity/client-id: {{ .Values.azure_genesis_storage.workloadIdentityClientId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
