{
 "title": "dag",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_consensus_last_committed_round{environment=~\"$environment\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Validator Connected Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, cluster)(aptos_connections{environment=~\"$environment\", network_id=\"Validator\", role_type=\"validator\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}}-{{cluster}}"
    }
   ]
  },
  {
   "title": "Synced Version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{environment=~\"$environment\", type=\"synced\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}-{{cluster}}-synced"
    }
   ]
  },
  {
   "title": "Committed user transactions per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_consensus_last_committed_version{environment=~\"$environment\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) - 2 * rate(aptos_consensus_last_committed_round{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "NUM_TXNS_PER_BLOCK",
   "type": "timeseries",
   "description": "Histogram for the number of txns per (committed) blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_num_txns_per_block_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(aptos_consensus_num_txns_per_block_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Round latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Node broadcasted latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_round_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"NodeBroadcasted\"}[$interval]) / rate(aptos_consensus_dag_round_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"NodeBroadcasted\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CertifiedNode broadcasted latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_round_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"CertifiedNodeBroadcasted\"}[$interval]) / rate(aptos_consensus_dag_round_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"CertifiedNodeBroadcasted\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Strong links received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_round_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"StrongLinkReceived\"}[$interval]) / rate(aptos_consensus_dag_round_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"StrongLinkReceived\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Full round latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_round_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"Finished\"}[$interval]) / rate(aptos_consensus_dag_round_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"Finished\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Node latency metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Node receive latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_node_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"NodeReceived\"}[$interval]) / rate(aptos_consensus_dag_node_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"NodeReceived\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cert aggregated latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_node_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"CertAggregated\"}[$interval]) / rate(aptos_consensus_dag_node_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"CertAggregated\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Certified node received latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_node_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"CertifiedNodeReceived\"}[$interval]) / rate(aptos_consensus_dag_node_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"CertifiedNodeReceived\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Anchor ordered latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_node_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"AnchorOrdered\"}[$interval]) / rate(aptos_consensus_dag_node_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"AnchorOrdered\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node ordered latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_dag_node_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"NodeOrdered\"}[$interval]) / rate(aptos_consensus_dag_node_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"NodeOrdered\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}