{
 "title": "end-to-end-txn-latency",
 "tags": [ "aptos-core" ],
 "time": { "from": "2023-07-25T23:33:48.000Z", "to": "2023-07-26T00:00:06.000Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "End-to-End", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stacked view",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum (rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\",stage=\"commit_accepted_block\", pod=~\"^(pfn|public-fullnode-).*\" }[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", stage=\"commit_accepted_block\", pod=~\"^(pfn|public-fullnode-).*\"}[$interval])))\n-\n(sum (rate(aptos_core_mempool_txn_commit_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",stage=\"commit_accepted_block\", pod=~\"^(pfn|public-fullnode-).*\" }[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", stage=\"commit_accepted_block\", pod=~\"^(pfn|public-fullnode-).*\"}[$interval])))\n> 0",
     "legendFormat": "PFN -> VFN txn"
    },
    {
     "expr": "(sum (rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\",stage=\"commit_accepted_block\", pod=~\"^(pfn|public-fullnode-).*\" }[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", stage=\"commit_accepted_block\", pod=~\"^(pfn|public-fullnode-).*\"}[$interval])))\n-\n(sum (rate(aptos_core_mempool_txn_commit_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"commit_accepted_block\"}[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"commit_accepted_block\"}[$interval]))) \n> 0",
     "legendFormat": "VFN -> Validator txn"
    },
    {
     "expr": "sum (rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"consensus_pulled\"}[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"consensus_pulled\"}[$interval]))",
     "legendFormat": "Validator txn -> Batch"
    },
    {
     "expr": "avg(rate(quorum_store_batch_to_PoS_duration_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(quorum_store_batch_to_PoS_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Batch -> POS"
    },
    {
     "expr": "avg(rate(quorum_store_pos_to_pull_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(quorum_store_pos_to_pull_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "POS -> Proposal"
    },
    {
     "expr": "quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"signed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"signed\"}[$interval]))",
     "legendFormat": "Proposal -> Signed block"
    },
    {
     "expr": "(quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval])) < 1000000)\n-\nquantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"signed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"signed\"}[$interval]))",
     "legendFormat": "Signed block -> Ordered block"
    },
    {
     "expr": "(quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"executed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"executed\"}[$interval])) < 1000000)\n-\n(quantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval])) < 1000000)",
     "legendFormat": "Ordered block -> Executed block"
    },
    {
     "expr": "(quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval])) < 1000000)\n-\n(quantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"executed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"executed\"}[$interval])) < 1000000)",
     "legendFormat": "Executed block -> Committed block"
    },
    {
     "expr": "(sum (rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"propose_to_sync_latency\"}[$__rate_interval])) / sum (rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"propose_to_sync_latency\"}[$__rate_interval])))\n-\n(quantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval])) < 1000000)",
     "legendFormat": "Committed block -> VFN sync"
    },
    {
     "expr": "(sum (rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"propose_to_sync_latency\"}[$__rate_interval])) / sum (rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"propose_to_sync_latency\"}[$__rate_interval])))\n-\n(sum (rate(aptos_data_client_sync_latencies_sum{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"propose_to_sync_latency\"}[$__rate_interval])) / sum (rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"propose_to_sync_latency\"}[$__rate_interval])))\n",
     "legendFormat": "VFN -> PFN sync"
    }
   ]
  },
  {
   "title": "Stacked view - coarse grained",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum (rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\",stage=\"commit_accepted_block\", pod=~\"^(pfn|public-fullnode-).*\" }[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", stage=\"commit_accepted_block\", pod=~\"^(pfn|public-fullnode-).*\"}[$interval])))\n-\n(sum (rate(aptos_core_mempool_txn_commit_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"commit_accepted_block\"}[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"commit_accepted_block\"}[$interval]))) \n+\nsum (rate(aptos_core_mempool_txn_commit_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"consensus_pulled\"}[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"consensus_pulled\"}[$interval]))",
     "legendFormat": "Mempool"
    },
    {
     "expr": "avg(rate(quorum_store_batch_to_PoS_duration_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(quorum_store_batch_to_PoS_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n+\navg(rate(quorum_store_pos_to_pull_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(quorum_store_pos_to_pull_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Quorum Store"
    },
    {
     "expr": "(quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval])) < 1000000)",
     "legendFormat": "Consensus (ordering)"
    },
    {
     "expr": "(quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval])) < 1000000)\n-\n(quantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval])) < 1000000)",
     "legendFormat": "Execution and commit"
    },
    {
     "expr": "(sum (rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"propose_to_sync_latency\"}[$__rate_interval])) / sum (rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"propose_to_sync_latency\"}[$__rate_interval])))\n-\n(quantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval])) < 1000000)",
     "legendFormat": "State sync"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Txn latency per role and submitted_by",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(submitted_by) (rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"commit_accepted\"}[$interval])) / sum by(submitted_by) (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "{{role}}:{{submitted_by}}"
    }
   ]
  },
  {
   "title": "Txn to block timestamp per role and submitted_by",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(submitted_by) (rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"commit_accepted_block\"}[$interval])) / sum by(submitted_by) (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"commit_accepted_block\"}[$interval]))",
     "legendFormat": "{{role}}:{{submitted_by}}"
    }
   ]
  },
  { "title": "Quorum Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Avg Insertion-to-Batch-Pulled",
   "type": "timeseries",
   "description": "The time between the local Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"consensus_pulled\"}[$interval])) / sum (rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"consensus_pulled\"}[$interval]))",
     "legendFormat": "{{pod}}:{{role}}:{{bucket}}"
    }
   ]
  },
  {
   "title": "BATCH_TO_POS_DURATION",
   "type": "timeseries",
   "description": "Histogram of the time durations from batch creation to PoS creation.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 26 },
   "targets": [
    {
     "expr": "avg(rate(quorum_store_batch_to_PoS_duration_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(quorum_store_batch_to_PoS_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "POS_TO_PULL",
   "type": "timeseries",
   "description": "Histogram for how long it took a PoS to go from inserted to pulled into a proposed block.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "avg(rate(quorum_store_pos_to_pull_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(quorum_store_pos_to_pull_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Proposer delay (due to backpressure)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aptos_proposer_delay_proposal{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block creation to signed",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the leader signs it.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"signed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"signed\"}[$interval]))",
     "legendFormat": "{{pod}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to ordered",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node ordered the block.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"ordered\"}[$interval])) < 1000000",
     "legendFormat": "{{pod}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to executed",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node executes the block.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"executed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"executed\"}[$interval])) < 1000000",
     "legendFormat": "{{pod}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to commit",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node commits it.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$interval])) < 1000000",
     "legendFormat": "{{pod}}-{{role}}"
    }
   ]
  },
  { "title": "State Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Avg. Block timestamp to synced",
   "type": "timeseries",
   "description": "The time between when the block was proposed by the validators until the fullnodes synced the data.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])) / sum(rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval]))",
     "legendFormat": "VFN"
    },
    {
     "expr": "sum(rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])) / sum(rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval]))",
     "legendFormat": "PFN"
    }
   ]
  },
  {
   "title": "Avg. State sync latencies",
   "type": "timeseries",
   "description": "The time between when the block was committed by the validators until the fullnodes synced the data.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])) / sum(rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])))\n-\nquantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$__rate_interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$__rate_interval]))",
     "legendFormat": "VFN"
    },
    {
     "expr": "(sum by() (rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])) / sum by() (rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval]))) \n-\nquantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$__rate_interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$__rate_interval]))",
     "legendFormat": "PFN"
    }
   ]
  },
  {
   "title": "VFN state sync latencies",
   "type": "timeseries",
   "description": "The time between when the block was committed by the validators until the VFNs synced the data.",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])) / sum(rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])))\n-\nquantile(0.67, rate(aptos_consensus_block_tracing_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$__rate_interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=\"committed\"}[$__rate_interval]))",
     "legendFormat": "VFN"
    }
   ]
  },
  {
   "title": "PFN state sync latencies",
   "type": "timeseries",
   "description": "The time between when the data was committed by the VFNs until the PFNs synced the data.",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(aptos_data_client_sync_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])) / sum(rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])))\n-\n(sum by() (rate(aptos_data_client_sync_latencies_sum{namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])) / sum by() (rate(aptos_data_client_sync_latencies_count{namespace=~\"$namespace\",label=\"propose_to_sync_latency\",pod=~\"^(pfn|public-fullnode-).*\"}[$__rate_interval])))",
     "legendFormat": "PFN"
    }
   ]
  },
  {
   "title": "(Ignore) State sync latencies stacked (VFN in Forge)",
   "type": "timeseries",
   "description": "The stacked view of the state sync latencies for the VFNs in forge.",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "(sum(rate(aptos_data_client_request_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",request_type=~\"get_new_transactions_or_outputs_with_proof_compressed|get_transactions_or_outputs_with_proof_compressed\"}[$__rate_interval])))\n/\n(sum(rate(aptos_data_client_request_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",request_type=~\"get_new_transactions_or_outputs_with_proof_compressed|get_transactions_or_outputs_with_proof_compressed\"}[$__rate_interval])))",
     "legendFormat": "Fetch Chunk"
    },
    {
     "expr": "(sum(rate(aptos_state_sync_storage_synchronizer_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label!=\"commit_chunk\"}[$__rate_interval])))\n/\n(sum(rate(aptos_state_sync_storage_synchronizer_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label!=\"commit_chunk\"}[$__rate_interval])))",
     "legendFormat": "Execute/Apply Chunk"
    },
    {
     "expr": "(sum(rate(aptos_state_sync_storage_synchronizer_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"commit_chunk\"}[$__rate_interval])))\n/\n(sum(rate(aptos_state_sync_storage_synchronizer_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"commit_chunk\"}[$__rate_interval])))",
     "legendFormat": "Commit Chunk"
    }
   ]
  },
  {
   "title": "(Ignore) State sync latencies stacked (PFN in Forge)",
   "type": "timeseries",
   "description": "The stacked view of the state sync latencies for the PFNs in forge.",
   "gridPos": { "h": 14, "w": 10, "x": 10, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(aptos_data_client_request_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",request_type=~\"get_transactions_or_outputs_with_proof_compressed\"}[$__rate_interval]))\n/\nsum(rate(aptos_data_client_request_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",request_type=~\"get_transactions_or_outputs_with_proof_compressed\"}[$__rate_interval]))",
     "legendFormat": "Fetch Chunk"
    },
    {
     "expr": "sum(rate(aptos_state_sync_storage_synchronizer_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label!=\"commit_chunk\"}[$__rate_interval]))\n/\nsum(rate(aptos_state_sync_storage_synchronizer_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label!=\"commit_chunk\"}[$__rate_interval]))",
     "legendFormat": "Execute/Apply Chunk"
    },
    {
     "expr": "sum(rate(aptos_state_sync_storage_synchronizer_latencies_sum{environment=~\"$environment\", namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"commit_chunk\"}[$__rate_interval]))\n/\nsum(rate(aptos_state_sync_storage_synchronizer_latencies_count{namespace=~\"$namespace\", pod=~\"^(pfn|public-fullnode-).*\",label=\"commit_chunk\"}[$__rate_interval]))",
     "legendFormat": "Commit Chunk"
    }
   ]
  }
 ]
}