{
 "title": "execution",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Block STM Insight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_executor_other_timers_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) / rate(aptos_executor_other_timers_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{name}} {{pod}}"
    },
    {
     "expr": "rate(aptos_executor_vm_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) / rate(aptos_executor_vm_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "_vm_execute {{pod}}"
    },
    {
     "expr": "rate(aptos_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) / rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "_execute_block {{pod}}"
    },
    {
     "expr": "rate(aptos_executor_commit_blocks_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) / rate(aptos_executor_commit_blocks_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "_commit_block {{pod}}"
    },
    {
     "expr": "(rate(aptos_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) - rate(aptos_executor_vm_execute_block_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) )/ rate(aptos_executor_vm_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "_non_vm_execute {{pod}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (name) (rate(aptos_vm_timer_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) / ignoring(name) group_left block_executor_concurrency)",
     "legendFormat": "{{name}} {{pod}}"
    }
   ]
  },
  {
   "title": "Block execution time breakdown per second",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(consensus_duration_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", op='execute_block'}[$interval]) )",
     "legendFormat": "block_execution_time"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "vm_execute"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"apply_to_ledger\"}[$interval]) )",
     "legendFormat": "apply_to_ledger"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"as_state_compute_result\"}[$interval]) )",
     "legendFormat": "as_state_compute_result"
    }
   ]
  },
  {
   "title": "Storage read breakdown for execution per second",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"wait_async_proof\"}[$interval]) )",
     "legendFormat": "wait_for_proof"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"async_proof_fetcher_fetch\"}[$interval]) /  avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}))",
     "legendFormat": "async_proof_fetcher_fetch"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"get_state_value\"}[$interval]) /  avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) )",
     "legendFormat": "cached_view_get_state_value"
    }
   ]
  },
  {
   "title": "BlockSTM  time breakdown per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "vm_execution_time"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_dependency_wait_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) ",
     "legendFormat": "executor_dependency_wait"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_vm_init_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) ",
     "legendFormat": "vm_init"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_validate_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) ",
     "legendFormat": "task_validate"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_execute_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) ",
     "legendFormat": "task_execute"
    },
    {
     "expr": "quantile(0.67, rate(block_executor_signature_verification_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) ",
     "legendFormat": "signature_verification"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_transaction_dedup_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) ",
     "legendFormat": "pre_dedup"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_transaction_shuffle_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) ",
     "legendFormat": "pre_shuffle"
    },
    {
     "expr": " quantile(0.67, rate(aptos_execution_get_next_task_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) )",
     "legendFormat": "get_next_task"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_work_with_task_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) )",
     "legendFormat": "work_with_task"
    },
    {
     "expr": "quantile(0.67, rate(aptos_parallel_execution_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) ",
     "legendFormat": "parallel_execution"
    },
    {
     "expr": "quantile(0.67, rate(aptos_rayon_execution_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) ",
     "legendFormat": "rayon_execution"
    },
    {
     "expr": "quantile(0.67, rate(block_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) ",
     "legendFormat": "blk_exec"
    }
   ]
  },
  {
   "title": "Block execution time breakdown (per block)",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(consensus_duration_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", op='execute_block'}[$interval])) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "block_execution_time"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "vm_execute"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"apply_to_ledger\"}[$interval])) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "apply_to_ledger"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"as_state_compute_result\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "as_state_compute_result"
    }
   ]
  },
  {
   "title": "Storage read breakdown for execution per block",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"wait_async_proof\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "wait_for_proof"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"async_proof_fetcher_fetch\"}[$interval]) /  avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "async_proof_fetcher_fetch"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"get_state_value\"}[$interval]) /  avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "cached_view_get_state_value"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"schedule_async_proof_read\"}[$interval]) /  avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "schedule_proof_read"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_get_state_val_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) /  avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "versioned_view_get_state_val"
    }
   ]
  },
  {
   "title": "BlockSTM  time breakdown per block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "vm_execution_time"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_dependency_wait_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "executor_dependency_wait"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_vm_init_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "vm_init"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_validate_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "task_validate"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_execute_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "task_execute"
    },
    {
     "expr": "quantile(0.67, rate(block_executor_signature_verification_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "signature_verification"
    },
    {
     "expr": "quantile(0.67, rate(block_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "block_executor_execute_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_parallel_execution_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "parallel_execution_seconds"
    },
    {
     "expr": "quantile(0.67, rate(aptos_rayon_execution_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "rayon_execution_seconds"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_work_with_task_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "work_with_task"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_get_next_task_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "get_next_task"
    }
   ]
  },
  {
   "title": "BlockSTM  operations per block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_execution_dependency_wait_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "dependency_wait_per_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_validate_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "task_validate_per_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_execute_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "task_execute_per_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_consensus_num_txns_per_block_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_consensus_num_txns_per_block_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
     "legendFormat": "transactions_per_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_speculative_abort_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) /  quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "speculative_abort_per_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_transaction_dedup_filtered_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) /  quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
     "legendFormat": "deduped_per_block"
    }
   ]
  },
  {
   "title": "BlockSTM  concurrency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "block_executor_concurrency{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Execute/Commit block per second",
   "type": "timeseries",
   "description": "The average time to execute a block.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "execute_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_commit_blocks_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "commit_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "vm_execute_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"apply_to_ledger\"}[$interval]))",
     "legendFormat": "apply_to_ledger"
    }
   ]
  },
  {
   "title": "execute_block per second",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", op='execute_block'}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Block execution time [p50]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to execute a block",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_execute_block_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Block execution time [p90]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to execute a block",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_execute_block_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Block execution time [p99]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to execute a block",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_execute_block_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Time spent in storage to save transactions [p50]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_save_transactions_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Time spent in storage to save transactions [p90]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_save_transactions_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Time spent in storage to save transactions [p99]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_save_transactions_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "VM execute block time [p50]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to execute a block in VM",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "VM execute block time [p90]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to execute a block in VM",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "VM execute block time [p99]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to execute a block in VM",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Total time to commit blocks [p50]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to commit blocks",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_commit_blocks_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Total time to commit blocks [p90]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to commit blocks",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_commit_blocks_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Total time to commit blocks [p99]",
     "type": "graph",
     "description": "p50, p95 and p99 of the time spent to commit blocks",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_commit_blocks_seconds_bucket{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by(pod, le))",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Validators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg Block execution time",
     "type": "graph",
     "description": "The average time spent to execute a block",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Avg  VM execute block time",
     "type": "graph",
     "description": "The average time spent to execute a block in VM",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_executor_vm_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_executor_vm_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Avg  Total time to commit blocks",
     "type": "graph",
     "description": "The average time spent to commit blocks",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_executor_commit_blocks_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_executor_commit_blocks_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Avg  Time spent in storage to save transactions",
     "type": "graph",
     "description": "The average time spent for persisting execution result to storage when committing blocks",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_executor_save_transactions_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_executor_save_transactions_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Avg Execute and commit chunk time",
     "type": "graph",
     "description": "The average time spent for executing and committing each chunk in state-syncing",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_executor_execute_and_commit_chunk_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_executor_execute_and_commit_chunk_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Avg  Total time to execute blocks",
     "type": "graph",
     "description": "The average time spent to commit blocks",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "Execution speculative abort rate",
     "type": "graph",
     "description": "The rate of speculative ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none", "label": "aborts / s" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_execution_speculative_abort_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    },
    {
     "title": "BlockSTM  time breakdown per block (temp)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
       "legendFormat": "vm_execution_time"
      },
      {
       "expr": "quantile(0.67, rate(aptos_execution_dependency_wait_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
       "legendFormat": "executor_dependency_wait"
      },
      {
       "expr": "quantile(0.67, rate(aptos_execution_vm_init_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
       "legendFormat": "vm_init"
      },
      {
       "expr": "quantile(0.67, rate(aptos_execution_task_validate_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
       "legendFormat": "task_validate"
      },
      {
       "expr": "quantile(0.67, rate(aptos_execution_task_execute_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
       "legendFormat": "task_execute"
      },
      {
       "expr": "quantile(0.67, rate(block_executor_signature_verification_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) )",
       "legendFormat": "signature_verification"
      },
      {
       "expr": "quantile(0.67, rate(block_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
       "legendFormat": "block_executor_execute_block"
      },
      {
       "expr": "quantile(0.67, rate(aptos_parallel_execution_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
       "legendFormat": "parallel_execution_seconds"
      },
      {
       "expr": "quantile(0.67, rate(aptos_rayon_execution_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
       "legendFormat": "rayon_execution_seconds"
      },
      {
       "expr": "quantile(0.67, rate(aptos_execution_work_with_task_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
       "legendFormat": "work_with_task"
      },
      {
       "expr": "quantile(0.67, rate(aptos_execution_get_next_task_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / avg(block_executor_concurrency{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
       "legendFormat": "get_next_task"
      },
      {
       "expr": "quantile(0.67, rate(final_output_extraction_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
       "legendFormat": "final_output_extraction"
      },
      {
       "expr": "quantile(0.67, rate(final_result_collection_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
       "legendFormat": "fina_result_collection"
      },
      {
       "expr": "quantile(0.67, rate(update_counters_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / quantile(0.67, rate(aptos_executor_execute_block_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])  )",
       "legendFormat": "update_counters_latency"
      }
     ]
    },
    {
     "title": "Executor Error Counter",
     "type": "graph",
     "description": "The counter that indicates the number of errors reported.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aptos_executor_error_total{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-{{role}}"
      }
     ]
    }
   ]
  },
  { "title": "Execution Per Block Gas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Per-block execution gas",
   "type": "graph",
   "description": "The per-block gas consumed by parallel execution (BlockSTM) or sequential execution.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "quantile by(stage) (0.5, rate(aptos_execution_block_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=~\"execution_gas|io_gas|non_storage_gas\", mode=\"parallel\"}[$interval]) /  rate(aptos_execution_block_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=~\"execution_gas|io_gas|non_storage_gas\", mode=\"parallel\"}[$interval]))",
     "legendFormat": "parallel_{{stage}}"
    },
    {
     "expr": "quantile by(stage) (0.5, rate(aptos_execution_block_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=~\"execution_gas|io_gas|non_storage_gas\", mode=\"sequential\"}[$interval]) /  rate(aptos_execution_block_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=~\"execution_gas|io_gas|non_storage_gas\", mode=\"sequential\"}[$interval]))",
     "legendFormat": "sequential_{{stage}}"
    }
   ]
  },
  {
   "title": "Per-block storage gas",
   "type": "graph",
   "description": "The per-block gas consumed by parallel execution (BlockSTM) or sequential execution.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "quantile by(stage) (0.5, rate(aptos_execution_block_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=~\"storage_in_octas|storage_in_gas\", mode=\"parallel\"}[$interval]) /  rate(aptos_execution_block_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=~\"storage_in_octas|storage_in_gas\", mode=\"parallel\"}[$interval]))",
     "legendFormat": "parallel_{{stage}}"
    },
    {
     "expr": "quantile by(stage) (0.5, rate(aptos_execution_block_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=~\"storage_in_octas|storage_in_gas\", mode=\"sequential\"}[$interval]) /  rate(aptos_execution_block_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage=~\"storage_in_octas|storage_in_gas\", mode=\"sequential\"}[$interval]))",
     "legendFormat": "sequential_{{stage}}"
    }
   ]
  },
  {
   "title": "Per-block storage fee",
   "type": "graph",
   "description": "The per-block gas consumed by parallel execution (BlockSTM) or sequential execution.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "quantile by(stage) (0.5, rate(aptos_execution_block_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage='storage_in_octas', mode=\"parallel\"}[$interval]) /  rate(aptos_execution_block_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage='storage_in_octas', mode=\"parallel\"}[$interval]))",
     "legendFormat": "parallel_{{stage}}"
    },
    {
     "expr": "quantile by(stage) (0.5, rate(aptos_execution_block_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage='storage_in_octas', mode=\"sequential\"}[$interval]) /  rate(aptos_execution_block_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage='storage_in_octas', mode=\"sequential\"}[$interval]))",
     "legendFormat": "sequential_{{stage}}"
    }
   ]
  },
  {
   "title": "Avg txn gas",
   "type": "graph",
   "description": "The avg txn gas consumed by parallel execution (BlockSTM) or sequential execution.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "quantile by(stage) (0.5, rate(aptos_execution_txn_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage!='storage_in_octas', mode=\"parallel\"}[$interval]) /  rate(aptos_execution_txn_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage!='storage_in_octas', mode=\"parallel\"}[$interval]))",
     "legendFormat": "parallel_{{stage}}"
    },
    {
     "expr": "quantile by(stage) (0.5, rate(aptos_execution_txn_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage!='storage_in_octas', mode=\"sequential\"}[$interval]) /  rate(aptos_execution_txn_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage!='storage_in_octas', mode=\"sequential\"}[$interval]))",
     "legendFormat": "sequential_{{stage}}"
    }
   ]
  },
  {
   "title": "Execution speed - run-time gas / s",
   "type": "graph",
   "description": "The per-block gas consumed by parallel execution (BlockSTM) or sequential execution.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "quantile (0.5, \n    (\n        max by(pod) (\n            rate(aptos_execution_block_gas_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage='non_storage_gas'}[$interval])\n        )\n        /  \n        max by(pod) (\n            rate(aptos_execution_block_gas_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", stage='non_storage_gas'}[$interval])\n        )\n    )\n    / \n    (\n        max by(pod) (\n            rate(consensus_duration_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", op='execute_block'}[$interval])\n        )\n        / \n        max by(pod) (\n            rate(consensus_duration_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", op='execute_block'}[$interval])\n        )\n    )\n)",
     "legendFormat": "gas / s"
    }
   ]
  },
  {
   "title": "Execution exceed block gas limit rate",
   "type": "graph",
   "description": "The rate of the parallel / sequential execution exceeding the per-block gas limit. ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "none", "label": "hits / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_execution_gas_limit_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", mode=\"parallel\"}[$interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(aptos_execution_gas_limit_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", mode=\"sequential\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Txn shuffling time",
   "type": "graph",
   "description": "The average time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_execution_transaction_shuffle_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_execution_transaction_shuffle_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg Txn dedup time",
   "type": "graph",
   "description": "The average time spent to dedup the txns in a block",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_execution_transaction_dedup_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_execution_transaction_dedup_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}-{{role}}"
    }
   ]
  },
  {
   "title": "Batch wait duration (per s)",
   "type": "graph",
   "description": "The time spent waiting for batches, per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_batch_wait_duration_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}-{{role}}"
    }
   ]
  },
  {
   "title": "Sharded Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sharded execution time in 1s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": " avg by (round_id)(max by(shard_id, round_id) (rate(sharded_block_execution_by_rounds_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ))",
       "legendFormat": "sub_block_execution_{{round_id}}"
      },
      {
       "expr": "rate(sharded_block_execution_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "sharded_execution"
      },
      {
       "expr": "rate(sharded_execution_result_aggregation_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "aggregation_result"
      },
      {
       "expr": "rate(wait_for_sharded_output_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "wait_for_sharded_output"
      }
     ]
    },
    {
     "title": "Sharded execution TPS by round",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (round_id) (sum by (round_id, shard_id) (rate(sharded_block_executor_txn_count_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) / sum by(round_id, shard_id) (rate(sharded_block_execution_by_rounds_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) )",
       "legendFormat": "{{round_id}}"
      }
     ]
    },
    {
     "title": "(to fix) Sharded execution transaction counts by round",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (round_id) (avg by (round_id, shard_id) (rate(sharded_block_executor_txn_count_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ) )",
       "legendFormat": "{{round_id}}"
      }
     ]
    },
    {
     "title": "(test-only)Sharded execution time in 1s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": " avg by (round_id)(max by(shard_id, round_id) (rate(sharded_block_execution_by_rounds_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) ))",
       "legendFormat": "sub_block_execution_{{round_id}}"
      },
      {
       "expr": "rate(sharded_block_execution_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "sharded_execution"
      },
      {
       "expr": "rate(sharded_execution_result_aggregation_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "aggregation_result"
      },
      {
       "expr": "rate(wait_for_sharded_output_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
       "legendFormat": "wait_for_sharded_output"
      },
      {
       "expr": "avg(rate(drop_state_view_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
       "legendFormat": "drop_state_view"
      },
      {
       "expr": "max(avg by(shard_id) (rate(execute_shard_command_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])))",
       "legendFormat": "execute_shard_command_seconds"
      }
     ]
    }
   ]
  }
 ]
}