{
 "title": "fullnodes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "State Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State Sync Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{environment=~\"$environment\", type=\"synced\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Fullnodes lagging behind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(aptos_data_client_highest_advertised_data{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", data_type=\"transactions\"}  - on(pod, run_uuid) aptos_state_sync_version{cluster=~\"$cluster\", namespace=~\"telemetry-service\", pod=~\"$pod\", type=\"synced\"} > 50000)  OR on() vector(0)",
     "legendFormat": "{{pod}}-{{pod}}"
    }
   ]
  },
  {
   "title": "State Sync Rate",
   "type": "graph",
   "description": "Rate at which the synced version is increasing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"synced\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}-{{pod}}"
    },
    {
     "expr": "rate(aptos_state_sync_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"synced\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}-{{job}}"
    }
   ]
  },
  {
   "title": "Fullnode Upstream Peers",
   "type": "graph",
   "description": "Number of upstream peers that can provide up to date information about the ledger.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, network_id)(aptos_connections{environment=~\"$environment\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}}-{{pod}}"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Mempool Pending transactions",
   "type": "graph",
   "description": "Number of uncommitted but still valid (not expired nor discarded) transactions in the nodes Mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", index=\"system_ttl\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{pod}}"
    },
    {
     "expr": "aptos_core_mempool_index_size{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", index=\"system_ttl\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{job}}"
    }
   ]
  },
  {
   "title": "Mempool Txn Commit Latency",
   "type": "graph",
   "description": "The time between Mempool receiving the transaction and time to be committed. Note: due to reliability mechanisms, this value can be lower than it really is.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} / aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{pod}}"
    },
    {
     "expr": "aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} / aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{job}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network Connections (Incoming)",
   "type": "graph",
   "description": "Number of Inbound Connections as measured by AptosNet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,pod)(aptos_connections{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", direction=\"inbound\",network_id=\"Public\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Network Connections (Outgoing)",
   "type": "graph",
   "description": "Number of  Outbound Network Connections as measured by AptosNet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, pod)(aptos_connections{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", direction=\"outbound\",network_id=\"Public\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{environment=~\"$environment\", cluster=~\"$cluster\"}[$interval])) by (instance)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{environment=~\"$environment\", cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Percentage Disk Used (global)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - kubelet_volume_stats_available_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*-node-storage\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*-node-storage\"}",
     "legendFormat": "{{persistentvolumeclaim}}:{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"fn\", pod=~\"$pod.*\", job=\"kubelet\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{environment=~\"$environment\", container=\"fullnode\", pod=~\"$pod\", cluster=\"$cluster\"}[$interval])",
     "legendFormat": "{{pod}}-{{pod}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{environment=~\"$environment\", container=\"fullnode\", pod=~\"pfn.*\", cluster=\"$cluster\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{environment=~\"$environment\", container=\"fullnode\", pod=~\"$pod.*\", job=\"kubernetes-cadvisor\", cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}