{
 "title": "node-system-info",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{},pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Info",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_del(node_system_cpu_info{environment=~\"$environment\", pod=~\"$pod\"}, \"namespace\", \"__name__\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Info",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(brand) (node_system_cpu_info{environment=~\"$environment\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count by(pod) (node_system_cpu_usage{environment=~\"$environment\"}) - 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total System Memory",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "label_del(node_system_mem_total{environment=~\"$environment\"}, \"__name__\", \"namespace\")",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}