{
 "title": "node-resource-metrics",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Node CPU Usage (Linux Only)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "(1-($Idle/($Total-$Guest)))*10", "type": "math" }
   ]
  },
  {
   "title": "Process Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "node_process_memory{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Overall System Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_system_mem_used{environment=~\"$environment\", namespace=\"$namespace\",pod=~\"$pod\"}/node_system_mem_total{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_disk_available_space{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}/node_disk_total_space{namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_disk_total_space{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"} - node_disk_available_space{namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_total_received{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]) + rate(node_network_total_transmitted{namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO Operations (Linux Only)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_linux_disk_num_reads{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]) + rate(node_linux_disk_num_writes{namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "Write IO Operations (Linux Only)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "quantile(0.5, rate(node_linux_disk_num_writes{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P50"
    },
    {
     "expr": "quantile(0.75, rate(node_linux_disk_num_writes{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P75"
    },
    {
     "expr": "quantile(0.9, rate(node_linux_disk_num_writes{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P90"
    },
    {
     "expr": "quantile(0.99, rate(node_linux_disk_num_writes{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Read IO Operations (Linux Only)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "quantile(0.5, rate(node_linux_disk_num_reads{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P50"
    },
    {
     "expr": "quantile(0.75, rate(node_linux_disk_num_reads{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P75"
    },
    {
     "expr": "quantile(0.9, rate(node_linux_disk_num_reads{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P90"
    },
    {
     "expr": "quantile(0.99, rate(node_linux_disk_num_reads{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Overall Node CPU Usage (Non Linux Only)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_system_cpu_usage{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", cpu_id=\"cpu\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}