{
 "title": "outliers",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "role_type", "query": { "query": "label_values(role)" } }
  ]
 },
 "panels": [
  {
   "title": "Slow execution nodes (consensus)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(aptos_executor_execute_block_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow commit nodes (consensus)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(aptos_executor_commit_blocks_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow execution/apply nodes (state sync)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(aptos_executor_apply_chunk_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(aptos_executor_execute_chunk_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow commit nodes (state sync)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(aptos_executor_commit_chunk_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_linux_disk_num_reads{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_linux_disk_num_writes{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lagging nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "clamp_min(aptos_data_client_highest_advertised_data{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", data_type=\"transactions\"} - on(pod) aptos_state_sync_version{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", type=\"synced\"}, 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}