{
 "title": "Shared Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reporting Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"federate\"} == 1)"
    }
   ]
  },
  {
   "title": "Not reporting metrics",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"federate\"} == 0 or up{job=\"kubernetes-pods\"} == 0 or up{job=\"kubernetes-cadvisor\"} == 0 or up{job=\"pushgateway\"} == 0"
    }
   ]
  },
  {
   "title": "Metric status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{kubernetes_pod_name=~\"$kubernetes_pod_name\", job=~\"$job\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{job}}"
    }
   ]
  }
 ]
}