{
 "title": "single-node-view",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Versions rate and delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "(aptos_state_sync_version{environment=~\"$environment\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"synced\"}) - on(pod) (aptos_storage_latest_transaction_version{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "synced - stored"
    },
    {
     "expr": "rate(aptos_state_sync_version{environment=~\"$environment\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"synced\"}[$__rate_interval])",
     "legendFormat": "sync_rate"
    },
    {
     "expr": "rate(aptos_storage_latest_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "stored_rate"
    },
    {
     "expr": "max(aptos_state_sync_version{environment=~\"$environment\", pod=~\".*\", cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"synced\"}) - max(aptos_state_sync_version{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"synced\"})",
     "legendFormat": "lag from chain"
    }
   ]
  },
  {
   "title": "Proposal failure count (in window)",
   "type": "timeseries",
   "description": "Proposal failure rate in leader election window. Value goes back to 0 once node is not asked to propose at all in the window",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "aptos_failed_proposals_in_window{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Transaction execution per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_committed_txns_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}-{{state}}"
    }
   ]
  },
  {
   "title": "collected voting power",
   "type": "timeseries",
   "description": "Voting power of all votes for the same ledger info collected by a proposer",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(aptos_proposer_collected_most_voting_power_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/rate(aptos_proposer_collecting_round_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/aptos_total_voting_power{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "proposal"
    },
    {
     "expr": "rate(aptos_proposer_collected_conflicting_voting_power_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/rate(aptos_proposer_collecting_round_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/aptos_total_voting_power{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "conflicting"
    },
    {
     "expr": "rate(aptos_proposer_collected_timeout_voting_power_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/rate(aptos_proposer_collecting_round_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/aptos_total_voting_power{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Leader election",
   "type": "timeseries",
   "description": "The proposal rate of the node, indicating how many times it becomes leaders.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_committed_proposals_in_window{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]",
     "legendFormat": "comitted_proposals"
    },
    {
     "expr": "aptos_failed_proposals_in_window{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]",
     "legendFormat": "failed_proposals"
    },
    {
     "expr": "aptos_committed_votes_in_window{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]",
     "legendFormat": "votes"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Times from block creation to different stages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_consensus_block_tracing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Processing times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{environment=~\"$environment\", pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$interval]) / rate(consensus_duration_count{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Total time spent on rare steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "consensus_duration_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", op=~'(sync_to|block_retrieval|process_block_retrieval)', pod=~\"$pod\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Rare events per second",
   "type": "timeseries",
   "description": "=",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", op=~'(sync_to|block_retrieval|process_block_retrieval)', pod=~\"$pod\"}[1m])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network -> Consensus rates",
   "type": "timeseries",
   "description": "The channel metrics related to network layer to consensus.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_pending_network_events{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Block retrieval rates",
   "type": "timeseries",
   "description": "The channel metrics related to consensus block retrieval (dedicated channel for the rpc).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_retrieval_channel_msgs_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Mempool transaction times",
   "type": "timeseries",
   "description": "The time between Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_core_mempool_txn_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{stage}}-{{scope}}"
    }
   ]
  },
  {
   "title": "Mampool processing times",
   "type": "timeseries",
   "description": "The time between Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval]) / rate(aptos_mempool_service_latency_ms_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{type}}-{{result}}"
    }
   ]
  }
 ]
}