{
 "title": "State Sync v2.3",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "State Sync Driver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest synced version",
   "type": "timeseries",
   "description": "The latest synced version of the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "aptos_state_sync_version{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\", storage_synchronizer_operation=\"synced_transactions\"}",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Latest synced version",
   "type": "stat",
   "description": "The latest synced version.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\", storage_synchronizer_operation=\"synced_transactions\"}",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Sync lag (behind highest known)",
   "type": "stat",
   "description": "The difference between the highest advertised version and the currently synced version.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\", data_type=\"transactions\"} - on(owner,role) aptos_state_sync_version{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\", storage_synchronizer_operation=\"synced_transactions\"}, 0)",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Syncing throughput (versions per second)",
   "type": "timeseries",
   "description": "The storage synchronizer throughput (versions per second).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(aptos_state_sync_version{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\",storage_synchronizer_operation=\"synced_transactions\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{storage_synchronizer_operation}}"
    }
   ]
  },
  {
   "title": "Driver events (per second)",
   "type": "timeseries",
   "description": "The driver events per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(aptos_state_sync_driver_counters{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer versions (per operation)",
   "type": "timeseries",
   "description": "The storage synchronizer version per operation type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "aptos_state_sync_version{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}-{{role}}-{{storage_synchronizer_operation}}"
    }
   ]
  },
  {
   "title": "Continuous syncer errors (per second)",
   "type": "timeseries",
   "description": "The continuous syncer errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(aptos_state_sync_continuous_syncer_errors{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Bootstrapper errors (per second)",
   "type": "timeseries",
   "description": "The bootstrapper errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(aptos_state_sync_bootstrapper_errors{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer errors (per second)",
   "type": "timeseries",
   "description": "The storage synchronizer errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(aptos_state_sync_storage_synchronizer_errors{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer gauges",
   "type": "timeseries",
   "description": "The storage synchronizer gauges",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "aptos_state_sync_storage_synchronizer_gauges{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}-{{role}}-{{label}}"
    }
   ]
  },
  { "title": "Data Streaming Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Created data streams (per second)",
   "type": "timeseries",
   "description": "The data streams created per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(aptos_data_streaming_service_create_data_stream{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{request_type}}"
    }
   ]
  },
  {
   "title": "Terminated data streams (per second)",
   "type": "timeseries",
   "description": "The data streams terminated per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(aptos_data_streaming_service_terminate_data_stream{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{feedback_type}}"
    }
   ]
  },
  {
   "title": "Sent data requests (per second)",
   "type": "timeseries",
   "description": "The sent data requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(aptos_data_streaming_service_sent_data_requests{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{request_type}}"
    }
   ]
  },
  {
   "title": "Received data responses (per second)",
   "type": "timeseries",
   "description": "The data responses received per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(aptos_data_streaming_service_received_data_response{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{response_type}}"
    }
   ]
  },
  {
   "title": "Average request processing latencies (per type)",
   "type": "timeseries",
   "description": "The average request processing latencies per data type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aptos_data_streaming_service_data_request_processing_latency_sum{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}/aptos_data_streaming_service_data_request_processing_latency_count{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}",
     "legendFormat": "{{owner}}-{{role}}-{{request_type}}"
    }
   ]
  },
  {
   "title": "Request processing latencies (0.99 quantile)",
   "type": "timeseries",
   "description": "The 0.99 quantile of all request processing latencies.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_data_streaming_service_data_request_processing_latency_bucket{chain_name=~\"$chain_name\", owner=~\"$owner\",role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Check progress errors (per second)",
   "type": "timeseries",
   "description": "The check progress errors encountered per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(aptos_data_streaming_service_check_progress_error{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{error_type}}"
    }
   ]
  },
  {
   "title": "Global data summary errors (per second)",
   "type": "timeseries",
   "description": "The global data summary errors encountered per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "rate(aptos_data_streaming_service_global_summary_error{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{error_type}}"
    }
   ]
  },
  {
   "title": "Received response errors (per second)",
   "type": "timeseries",
   "description": "The data response errors received per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(aptos_data_streaming_service_received_response_error{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}-{{error_type}}"
    }
   ]
  },
  {
   "title": "Aptos Data Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent requests (per second)",
     "type": "timeseries",
     "description": "The sent data requests per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "rate(aptos_data_client_sent_requests{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{owner}}-{{role}}-{{request_types}}"
      }
     ]
    },
    {
     "title": "Error responses (per second)",
     "type": "timeseries",
     "description": "The error responses per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "rate(aptos_data_client_error_responses{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{owner}}-{{role}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Request latencies (0.99 quantile)",
     "type": "timeseries",
     "description": "The 0.99 quantile of all request latencies",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(aptos_data_client_request_latencies_bucket{chain_name=~\"$chain_name\", owner=~\"$owner\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{owner}}-{{role}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Average request latencies (per type)",
     "type": "timeseries",
     "description": "The average request latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "aptos_data_client_request_latencies_sum{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}/aptos_data_client_request_latencies_count{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}",
       "legendFormat": "{{owner}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Successful responses (per second)",
     "type": "timeseries",
     "description": "The successful data responses per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "rate(aptos_data_client_success_responses{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{owner}}-{{role}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Optimal chunk sizes (per type)",
     "type": "timeseries",
     "description": "The optimal chunk sizes per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "aptos_data_client_optimal_chunk_sizes{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}",
       "legendFormat": "{{owner}}-{{role}}-{{data_type}}"
      }
     ]
    },
    {
     "title": "Highest advertised transaction data",
     "type": "stat",
     "description": "The highest advertised transaction data.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\",data_type=\"transactions\"}",
       "legendFormat": "{{owner}}-{{role}}"
      }
     ]
    },
    {
     "title": "Highest advertised data (per type)",
     "type": "timeseries",
     "description": "The highest advertised data version per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}",
       "legendFormat": "{{owner}}-{{role}}-{{data_type}}"
      }
     ]
    },
    {
     "title": "Lowest advertised transaction data",
     "type": "stat",
     "description": "The lowest advertised transaction data.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aptos_data_client_lowest_advertised_data{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\",data_type=\"transactions\"}",
       "legendFormat": "{{owner}}-{{role}}"
      }
     ]
    },
    {
     "title": "Lowest advertised data (per type)",
     "type": "timeseries",
     "description": "The lowest advertised data version per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "expr": "aptos_data_client_lowest_advertised_data{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}",
       "legendFormat": "{{owner}}-{{role}}-{{data_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Service Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests received (per second)",
     "type": "timeseries",
     "description": "The requests received per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "rate(aptos_storage_service_server_requests_received{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{owner}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Storage errors (per second)",
     "type": "timeseries",
     "description": "The storage errors per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "rate(aptos_storage_service_server_errors{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{owner}}-{{role}}-{{error_type}}"
      }
     ]
    },
    {
     "title": "Request processing latencies (0.99 quantile)",
     "type": "timeseries",
     "description": "The 0.99 quantile of all request processing latencies",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(aptos_storage_service_server_request_latency_bucket{chain_name=~\"$chain_name\", owner=~\"$owner\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{request_type}}"
      }
     ]
    },
    {
     "title": "Average request processing latencies (per type)",
     "type": "timeseries",
     "description": "The average request processing latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "aptos_storage_service_server_request_latency_sum{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}/aptos_storage_service_server_request_latency_count{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}",
       "legendFormat": "{{owner}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Storage responses sent (per second)",
     "type": "timeseries",
     "description": "The storage responses sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "rate(aptos_storage_service_server_responses_sent{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{owner}}-{{role}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Pending network events (per second)",
     "type": "timeseries",
     "description": "The pending network events per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "rate(aptos_storage_service_server_pending_network_events{chain_name=~\"$chain_name\", owner=~\"$owner\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{owner}}-{{role}}-{{state}}"
      }
     ]
    }
   ]
  }
 ]
}