{
 "title": "storage-backup-and-restore",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "backup_service_api_name",
    "query": {
     "query": "aptos_backup_service_latency_s_count"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Coordinator Activities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backup Coordinator Heartbeats",
   "type": "bargauge",
   "description": "When the backup coordinator is live, this shows as a upward trend line.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "now() * 1000", "legendFormat": "now" },
    {
     "expr": "last_over_time(aptos_db_backup_coordinator_heartbeat_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\"}[7d]) * 1000",
     "legendFormat": " {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Latest epoch ending backed up",
   "type": "bargauge",
   "description": "When the backup coordinator is live, this shows as a upward trend line.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aptos_storage_next_block_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "latest"
    },
    {
     "expr": "last_over_time(aptos_db_backup_coordinator_epoch_ending_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[7d])",
     "legendFormat": " {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Epoch Ending Backup: Epoch vs Latest Epoch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(aptos_storage_next_block_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "latest"
    },
    {
     "expr": "aptos_db_backup_coordinator_epoch_ending_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}} backed up"
    }
   ]
  },
  {
   "title": "Latest transaction backed up",
   "type": "bargauge",
   "description": "When the backup coordinator is live, this shows as a upward trend line.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aptos_storage_latest_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "latest"
    },
    {
     "expr": "last_over_time(aptos_db_backup_coordinator_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[7d])",
     "legendFormat": " {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Transaction Backup: Version vs latest version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(aptos_storage_latest_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "latest"
    },
    {
     "expr": "aptos_db_backup_coordinator_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}} backed up"
    }
   ]
  },
  {
   "title": "Transaction backup: transactions per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_backup_handler_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Latest state snapshot (epoch) backed up",
   "type": "bargauge",
   "description": "When the backup coordinator is live, this shows as a upward trend line.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aptos_storage_next_block_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "latest"
    },
    {
     "expr": "last_over_time(aptos_db_backup_coordinator_state_snapshot_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[7d])",
     "legendFormat": " {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "State Snapshot: epoch vs Latest epoch",
   "type": "timeseries",
   "description": "State version of the snapshot being taken, compared to latest version of the ledger.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(aptos_storage_next_block_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "latest"
    },
    {
     "expr": "aptos_db_backup_coordinator_state_snapshot_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}} backed up"
    }
   ]
  },
  {
   "title": "State snapshot: items per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_backup_handler_state_snapshot_leaf_index{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "State snapshot: Progress vs Total Accounts",
   "type": "timeseries",
   "description": "Note the number of accounts is the latest, not that at specified version.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aptos_backup_handler_state_snapshot_leaf_index{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} + 1 ",
     "legendFormat": "{{cluster}} {{pod}}-progress"
    },
    {
     "expr": "quantile(0.8, aptos_jellyfish_leaf_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{cluster}} {{pod}} total"
    }
   ]
  },
  {
   "title": "Backup Verify",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Verified epoch ending epoch in backup",
     "type": "bargauge",
     "description": "When the backup coordinator is live, this shows as a upward trend line.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aptos_storage_next_block_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "latest"
      },
      {
       "expr": "last_over_time(aptos_db_backup_verify_epoch_ending_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1d])",
       "legendFormat": " {{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "Epoch Ending Epoch",
     "type": "graph",
     "description": "Epoch of the epoch ending LedgerInfo verified",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_epoch_ending_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_backup_verify_epoch_ending_epoch{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) != 0",
       "legendFormat": "{{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "Epoch Ending Version",
     "type": "graph",
     "description": "Version of the epoch ending LedgerInfo verified",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_epoch_ending_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_backup_verify_epoch_ending_version{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) != 0",
       "legendFormat": "{{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "Verified transaction version in backup",
     "type": "bargauge",
     "description": "When the backup coordinator is live, this shows as a upward trend line.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aptos_storage_latest_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "latest"
      },
      {
       "expr": "last_over_time(aptos_db_backup_verify_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1d])",
       "legendFormat": " {{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "Transaction Version",
     "type": "graph",
     "description": "Version of the transaction verified",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_backup_verify_transaction_version{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) != 0",
       "legendFormat": "{{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "Transactions per Second",
     "type": "graph",
     "description": "The speed of transaction verification.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_db_backup_verify_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) > 0",
       "legendFormat": "{{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "Verified state snapshot version in backup",
     "type": "bargauge",
     "description": "When the backup coordinator is live, this shows as a upward trend line.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aptos_storage_latest_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "latest"
      },
      {
       "expr": "last_over_time(aptos_db_backup_verify_state_snapshot_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1d])",
       "legendFormat": " {{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "State Snapshot Version",
     "type": "graph",
     "description": "Version of the state snapshot being verified",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_state_snapshot_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_backup_verify_state_snapshot_leaf_index[1m]) != 0",
       "legendFormat": "{{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "Job State",
     "type": "timeseries",
     "description": "Right edge of the graph shows latest state of the backup-verify job and when it entered such state.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "targets": [
      {
       "expr": "sort_desc(last_over_time(aptos_db_backup_verify_coordinator_start_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[2d]) * 1000\r\nunless last_over_time(aptos_db_backup_verify_coordinator_succeed_timestamp_s[2d]) >  last_over_time(aptos_db_backup_verify_coordinator_start_timestamp_s[2d])\r\nunless last_over_time(aptos_db_backup_verify_coordinator_fail_timestamp_s[2d]) >  last_over_time(aptos_db_backup_verify_coordinator_start_timestamp_s[2d]))",
       "legendFormat": "{{cluster}} {{pod}} running since"
      },
      {
       "expr": "sort_desc(last_over_time(aptos_db_backup_verify_coordinator_succeed_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[2d]) * 1000\r\nunless last_over_time(aptos_db_backup_verify_coordinator_start_timestamp_s[2d]) >  last_over_time(aptos_db_backup_verify_coordinator_succeed_timestamp_s[2d])\r\nunless last_over_time(aptos_db_backup_verify_coordinator_fail_timestamp_s[2d]) >  last_over_time(aptos_db_backup_verify_coordinator_succeed_timestamp_s[2d]))",
       "legendFormat": "{{cluster}} {{pod}} succeeded since"
      },
      {
       "expr": "sort_desc(last_over_time(aptos_db_backup_verify_coordinator_fail_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[2d]) * 1000\r\nunless last_over_time(aptos_db_backup_verify_coordinator_start_timestamp_s[2d]) >  last_over_time(aptos_db_backup_verify_coordinator_fail_timestamp_s[2d])\r\nunless last_over_time(aptos_db_backup_verify_coordinator_succeed_timestamp_s[2d]) >  last_over_time(aptos_db_backup_verify_coordinator_fail_timestamp_s[2d]))",
       "legendFormat": "{{cluster}} {{pod}} failed since"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Service API Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(aptos_backup_service_sent_bytes{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$backup_service_api_name\"}[1m])) by(pod, pod) > 0",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "$backup_service_api_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "repeat": "backup_service_api_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_backup_service_sent_bytes{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", endpoint=\"$backup_service_api_name\"}[1m]) and irate(aptos_backup_service_sent_bytes[1m]) > 0",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Restore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Job State",
     "type": "graph",
     "description": "Right edge of the graph shows latest state of the restore job and when it entered such state.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "dateTimeAsLocal" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_coordinator_start_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} * 1000\nunless aptos_db_restore_coordinator_succeed_timestamp_s > aptos_db_restore_coordinator_start_timestamp_s\nunless aptos_db_restore_coordinator_fail_timestamp_s > aptos_db_restore_coordinator_start_timestamp_s\n\n# any restore activity:\nand (rate(aptos_db_restore_epoch_ending_epoch[1m]) > 0 or rate(aptos_db_restore_state_snapshot_leaf_index[1m]) > 0 or rate(aptos_db_restore_transaction_save_version[1m]) > 0 or rate(aptos_db_restore_transaction_replay_version[1m]) > 0) == bool 1",
       "legendFormat": "{{pod}} running since"
      },
      {
       "expr": "aptos_db_restore_coordinator_succeed_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} * 1000\nunless aptos_db_restore_coordinator_start_timestamp_s > aptos_db_restore_coordinator_succeed_timestamp_s\nunless aptos_db_restore_coordinator_fail_timestamp_s > aptos_db_restore_coordinator_succeed_timestamp_s",
       "legendFormat": "{{pod}} succeeded since"
      },
      {
       "expr": "aptos_db_restore_coordinator_fail_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} * 1000\nunless aptos_db_restore_coordinator_start_timestamp_s > aptos_db_restore_coordinator_fail_timestamp_s\nunless aptos_db_restore_coordinator_succeed_timestamp_s > aptos_db_restore_coordinator_fail_timestamp_s",
       "legendFormat": "{{pod}} failed since"
      }
     ]
    },
    {
     "title": "Epoch Ending Epoch",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_epoch_ending_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_restore_epoch_ending_epoch[1m]) != 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Epoch Ending Version",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_epoch_ending_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_restore_epoch_ending_version[1m]) != 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "State Snapshot Version",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_state_snapshot_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_restore_state_snapshot_target_leaf_index[1m]) != 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transaction Restore Progress",
     "type": "graph",
     "description": "save: Version of txn being saved without replaying\nreplay: Version of txn being replayed\ntarget: When \"replay\" hits this version, the restore is done.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_transaction_save_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_restore_transaction_save_version[1m]) != 0",
       "legendFormat": "{{pod}} saved"
      },
      {
       "expr": "aptos_db_restore_transaction_replay_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_restore_transaction_replay_version[1m]) != 0",
       "legendFormat": "{{pod}}  replayed"
      },
      {
       "expr": "aptos_db_restore_coordinator_target_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and (irate(aptos_db_restore_transaction_save_version[1m]) != 0 or irate(aptos_db_restore_transaction_replay_version[1m]) != 0)",
       "legendFormat": "{{pod}} target"
      }
     ]
    },
    {
     "title": "Transaction Restore Progress %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(aptos_db_restore_transaction_save_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_restore_transaction_save_version[1m]) != 0) / aptos_db_restore_coordinator_target_version",
       "legendFormat": "{{pod}} saved"
      },
      {
       "expr": "(aptos_db_restore_transaction_replay_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} and irate(aptos_db_restore_transaction_replay_version[1m]) != 0) / aptos_db_restore_coordinator_target_version",
       "legendFormat": "{{pod}} replayed"
      }
     ]
    },
    {
     "title": "Transaction Save per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_db_restore_transaction_save_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) != 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transaction Replay per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_db_restore_transaction_replay_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) != 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Restore Status Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Job State",
     "type": "graph",
     "description": "Right edge of the graph shows latest state of the restore job and when it entered such state.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "dateTimeAsLocal" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_coordinator_start_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} * 1000\nunless aptos_db_restore_coordinator_succeed_timestamp_s > aptos_db_restore_coordinator_start_timestamp_s\nunless aptos_db_restore_coordinator_fail_timestamp_s > aptos_db_restore_coordinator_start_timestamp_s\n\n# any restore activity:\nand (rate(aptos_db_restore_epoch_ending_epoch[1m]) > 0 or rate(aptos_db_restore_state_snapshot_leaf_index[1m]) > 0 or rate(aptos_db_restore_transaction_save_version[1m]) > 0 or rate(aptos_db_restore_transaction_replay_version[1m]) > 0) == bool 1",
       "legendFormat": "{{pod}} running since"
      },
      {
       "expr": "aptos_db_restore_coordinator_succeed_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} * 1000\nunless aptos_db_restore_coordinator_start_timestamp_s > aptos_db_restore_coordinator_succeed_timestamp_s\nunless aptos_db_restore_coordinator_fail_timestamp_s > aptos_db_restore_coordinator_succeed_timestamp_s",
       "legendFormat": "{{pod}} succeeded since"
      },
      {
       "expr": "aptos_db_restore_coordinator_fail_timestamp_s{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} * 1000\nunless aptos_db_restore_coordinator_start_timestamp_s > aptos_db_restore_coordinator_fail_timestamp_s\nunless aptos_db_restore_coordinator_succeed_timestamp_s > aptos_db_restore_coordinator_fail_timestamp_s",
       "legendFormat": "{{pod}} failed since"
      }
     ]
    },
    {
     "title": "Transaction Restore Progress",
     "type": "graph",
     "description": "save: Version of txn being saved without replaying\nreplay: Version of txn being replayed\ntarget: When \"replay\" hits this version, the restore is done.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_transaction_save_version and irate(aptos_db_restore_transaction_save_version[1m]) > 0",
       "legendFormat": "{{pod}} saved"
      },
      {
       "expr": "aptos_db_restore_transaction_replay_version and irate(aptos_db_restore_transaction_replay_version[1m]) > 0",
       "legendFormat": "{{pod}}  replayed"
      },
      {
       "expr": "aptos_db_restore_coordinator_target_version and (irate(aptos_db_restore_transaction_save_version[1m]) > 0 or irate(aptos_db_restore_transaction_replay_version[1m]) > 0)",
       "legendFormat": "{{pod}} target"
      }
     ]
    },
    {
     "title": "Transaction Restore Progress %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(aptos_db_restore_transaction_save_version and irate(aptos_db_restore_transaction_save_version[1m]) > 0) / aptos_db_restore_coordinator_target_version",
       "legendFormat": "{{pod}} saved"
      },
      {
       "expr": "(aptos_db_restore_transaction_replay_version and irate(aptos_db_restore_transaction_replay_version[1m]) > 0) / aptos_db_restore_coordinator_target_version",
       "legendFormat": "{{pod}} replayed"
      }
     ]
    },
    {
     "title": "State Snapshot Restore Progress",
     "type": "graph",
     "description": "save: Version of txn being saved without replaying\nreplay: Version of txn being replayed\ntarget: When \"replay\" hits this version, the restore is done.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_state_snapshot_leaf_index and irate(aptos_db_restore_state_snapshot_leaf_index[1m])",
       "legendFormat": "{{pod}} saved"
      },
      {
       "expr": "aptos_db_restore_state_snapshot_target_leaf_index and irate(aptos_db_restore_state_snapshot_leaf_index[1m])",
       "legendFormat": "{{pod}}  target"
      }
     ]
    },
    {
     "title": "Committed and Synced Versions",
     "type": "graph",
     "description": "\"Committed\" version is the version on the latest ledger info saved.\n\n\"Synced\" version is the version on the latest transaction saved, it's only different when state-sync is working to catch up with peers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_storage_latest_transaction_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} {{pod}} synced"
      },
      {
       "expr": "aptos_storage_ledger_version{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} {{pod}} committed"
      }
     ]
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{environment=~\"$environment\", pod=~\".*backup-0.*\", job=\"kubernetes-cadvisor\",container=\"backup\"})",
     "legendFormat": "{{cluster}}-{{pod}}"
    }
   ]
  },
  {
   "title": "backup memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{environment=~\"$environment\", pod=~\".*backup-0.*\", job=\"kubernetes-cadvisor\",container=\"backup\"}",
     "legendFormat": "{{cluster}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Backup-verify memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{environment=~\"$environment\", pod=~\".*backup-verify.*\", job=\"kubernetes-cadvisor\"}",
     "legendFormat": "{{cluster}}-{{pod}}"
    }
   ]
  }
 ]
}