{
 "title": "storage-details",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "cf_name", "query": { "query": "label_values(cf_name)" } },
   { "name": "api_name", "query": { "query": "label_values(api_name)" } },
   {
    "name": "timer_name",
    "query": {
     "query": "aptos_storage_other_timers_seconds_sum"
    }
   },
   { "name": "db_name", "query": { "query": "label_values(db_name)" } },
   { "name": "rocksdb_property_name", "query": { "query": "label_values(property_name)" } }
  ]
 },
 "panels": [
  {
   "title": "AptosDB API Latency by api_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$api_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_api_latency_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", api_name=\"$api_name\"}[1m]) / irate(aptos_storage_api_latency_seconds_count[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AptosDB API Success Rate by api_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "OVERALL",
     "type": "graph",
     "description": "Successes / (Successes + Errors)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (rate(aptos_storage_api_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", result=\"Ok\", api_name=~\"$api_name\"}[1m])) / sum by (pod) (rate(aptos_storage_api_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", api_name=~\"$api_name\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (rate(aptos_storage_api_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", api_name=\"$api_name\", result=\"Ok\"}[1m])) / sum by (pod) (rate(aptos_storage_api_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", api_name=\"$api_name\"}[1m]))",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AptosDB API Call per Second by api_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TOTAL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod, pod) (irate(aptos_storage_api_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", api_name=~\"$api_name\"}[1m]))",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_api_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AptosDB API Error per Second by api_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TOTAL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod, pod) (irate(aptos_storage_api_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", api_name=~\"$api_name\", result=\"Err\"}[1m]))",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_api_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", result=\"Err\", api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB get() Latency by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "repeat": "cf_name",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(aptos_schemadb_get_latency_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=\"$cf_name\"}[1m])/ irate(aptos_schemadb_get_latency_seconds_count[1m])",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "SchemaDB get() per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, pod) (irate(aptos_schemadb_get_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_get_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=\"$cf_name\"}[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB get() Bytes per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, pod) (irate(aptos_schemadb_get_bytes_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, pod) (irate(aptos_schemadb_get_bytes_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=\"$cf_name\"}[1m]))",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB iterator next() Latency by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_iter_latency_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=\"$cf_name\"}[1m])/irate(aptos_schemadb_iter_latency_seconds_count[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB iterator next() per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$cf_name",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "repeat": "cf_name",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(aptos_schemadb_iter_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=\"$cf_name\"}[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB iterator next() Bytes per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, pod) (irate(aptos_schemadb_iter_bytes_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_iter_bytes_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=\"$cf_name\"}[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB iterator seek() per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, pod) (irate(aptos_schemadb_seek_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "repeat": "cf_name",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod, pod) (irate(aptos_schemadb_seek_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB iterator seek() Latency by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$cf_name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "repeat": "cf_name",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(aptos_schemadb_seek_latency_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=~\"$cf_name\"}[1m]) / irate(aptos_schemadb_seek_latency_seconds_count[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB commit() ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_batch_commit_latency_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", db_name=~\"$db_name\"}[1m])/irate(aptos_schemadb_batch_commit_latency_seconds_count[1m])",
       "legendFormat": "{{pod}} {{pod}} {{db_name}}"
      }
     ]
    },
    {
     "title": "Commits per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_batch_commit_latency_seconds_count{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", db_name=~\"$db_name\"}[1m])",
       "legendFormat": "{{pod}} {{pod}} {{db_name}}"
      }
     ]
    },
    {
     "title": "Commit Bytes per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, run_uuid) (rate(aptos_schemadb_batch_commit_bytes_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", db_name=~\"$db_name\"}[5m]))",
       "legendFormat": "{{pod}} {{pod}} {{db_name}}"
      }
     ]
    },
    {
     "title": "Average Commit Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_batch_commit_bytes_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", db_name=~\"$db_name\"}[1m]) / irate(aptos_schemadb_batch_commit_bytes_count[1m])",
       "legendFormat": "{{pod}} {{pod}} {{db_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other Latencies by timer_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$timer_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "repeat": "timer_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_other_timers_seconds_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", name=\"$timer_name\"}[1m])/ irate(aptos_storage_other_timers_seconds_count[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Column Family Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, pod) (aptos_rocksdb_properties{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", pod=~\"$pod\", cf_name=~\"$cf_name\"})",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "aptos_rocksdb_properties{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", pod=~\"$pod\", cf_name=\"$cf_name\"}",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Structure Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Accounts vs Internal Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_storage_ledger{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type=\"new_state_leaves\"} - ignoring(type) aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"stale_state_leaves\"}",
       "legendFormat": "{{pod}} {{pod}} accounts"
      },
      {
       "expr": "aptos_storage_ledger{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type=\"new_state_nodes\"} - ignoring(type) aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"stale_state_nodes\"} - ignoring(type) aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"new_state_leaves\"} + ignoring(type) aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"stale_state_leaves\"}",
       "legendFormat": "{{pod}} {{pod}} internal_nodes"
      }
     ]
    },
    {
     "title": "Next Block Epoch",
     "type": "graph",
     "description": "On the version that wraps up an epoch, the \"next block epoch\" is the current epoch plus one.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_storage_next_block_epoch{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "Jellyfish Tree Disk Size vs Calculated Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "aptos_rocksdb_properties{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", pod=~\"$pod\", cf_name=\"jellyfish_merkle_node\"}",
       "legendFormat": "{{pod}} {{pod}} rocksdb"
      },
      {
       "expr": "rate(aptos_schemadb_put_bytes_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", cf_name=\"jellyfish_merkle_node\"}[10m]) / rate(aptos_schemadb_put_bytes_count[10m]) * ignoring(cf_name) ((aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"new_state_nodes\"} - ignoring(type) aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"stale_state_nodes\"}) + 1000000 * (log2(aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"new_state_leaves\"} - ignoring(type) aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"stale_state_leaves\"}) / 2 - 1))",
       "legendFormat": "{{pod}} {{pod}} calculated"
      }
     ]
    },
    {
     "title": "Avg Account Updates per Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_ledger{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type=\"new_state_leaves\"}[1m]) / ignoring(type) irate(aptos_storage_latest_transaction_version[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "Avg Events Emits per Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_ledger{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type=\"events_created\"}[1m]) / on(pod, pod) irate(aptos_storage_latest_transaction_version[1m])",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    },
    {
     "title": "Record size (key + value) by Column Family",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg by(cf_name)(irate(aptos_schemadb_put_bytes_sum{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) / irate(aptos_schemadb_put_bytes_count[1m]))",
       "legendFormat": "{{cf_name}}"
      }
     ]
    },
    {
     "title": "Avg Internal Node Updates per Account Update",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_ledger{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type=\"new_state_nodes\"}[1m]) / ignoring(type) irate(aptos_storage_ledger{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"new_state_leaves\"}[1m]) - 1",
       "legendFormat": "{{pod}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB Properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "$rocksdb_property_name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "repeat": "rocksdb_property_name",
     "targets": [
      {
       "expr": "aptos_rocksdb_properties{environment=~\"$environment\", namespace=~\"$namespace\", cluster=~\"$cluster\", pod=~\"$pod\", property_name=~\"$rocksdb_property_name\"}",
       "legendFormat": "{{pod}} {{run_uuid}} {{cf_name}}"
      }
     ]
    }
   ]
  }
 ]
}