{
 "title": "Storage",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   { "name": "cf_name", "query": { "query": "label_values(cf_name)" } },
   {
    "name": "api_name",
    "query": {
     "query": "aptos_storage_api_latency_seconds_count"
    }
   },
   {
    "name": "backup_service_api_name",
    "query": {
     "query": "aptos_backup_service_latency_s_count"
    }
   },
   {
    "name": "timer_name",
    "query": {
     "query": "aptos_storage_other_timers_seconds_sum"
    }
   },
   { "name": "db_name", "query": { "query": "label_values(db_name)" } }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free Disk Space",
   "type": "graph",
   "description": "Free disk space on the DB volume. Less than a few GiBs, it's a problem.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", persistentvolumeclaim!~\".*prometheus.*\"} - kubelet_volume_stats_used_bytes",
     "legendFormat": "{{kubernetes_pod_name}} {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "AptosDB API Success Rate",
   "type": "graph",
   "description": "Successes / (Successes + Errors)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", result=\"Ok\"}[1m])) / sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count[1m]))",
     "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "SchemaDB get() latency",
   "type": "graph",
   "description": "This reflects the IO performance of the underlying device.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_schemadb_get_latency_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])) / sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_schemadb_get_latency_seconds_count[1m]))",
     "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "AptosDB API Latency by api_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$api_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_api_latency_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", api_name=\"$api_name\"}[1m]) / irate(aptos_storage_api_latency_seconds_count[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AptosDB API Success Rate by api_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "OVERALL",
     "type": "graph",
     "description": "Successes / (Successes + Errors)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", result=\"Ok\", api_name=~\"$api_name\"}[1m])) / sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", api_name=~\"$api_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", result=\"Ok\", api_name=\"$api_name\"}[1m])) / sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", api_name=\"$api_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AptosDB API Call per Second by api_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", api_name=~\"$api_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AptosDB API Error per Second by api_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", api_name=~\"$api_name\", result=\"Err\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", result=\"Err\", api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB get() Latency by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_get_latency_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"$cf_name\"}[1m])/ irate(aptos_schemadb_get_latency_seconds_count[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB get() per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_schemadb_get_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_get_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"$cf_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB get() Bytes per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_schemadb_get_bytes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_schemadb_get_bytes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"$cf_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB iterator next() Latency by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_iter_latency_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"$cf_name\"}[1m])/irate(aptos_schemadb_iter_latency_seconds_count[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB iterator next() per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_schemadb_iter_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_iter_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"$cf_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB iterator next() Bytes per Second by cf_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (irate(aptos_schemadb_iter_bytes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"$cf_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_iter_bytes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"$cf_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SchemaDB commit() ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_batch_commit_latency_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", db_name=~\"$db_name\"}[1m])/irate(aptos_schemadb_batch_commit_latency_seconds_count[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} {{db_name}}"
      }
     ]
    },
    {
     "title": "Commits per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_batch_commit_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", db_name=~\"$db_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} {{db_name}}"
      }
     ]
    },
    {
     "title": "Commit Bytes per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_batch_commit_bytes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", db_name=~\"$db_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} {{db_name}}"
      }
     ]
    },
    {
     "title": "Average Commit Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_schemadb_batch_commit_bytes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", db_name=~\"$db_name\"}[1m]) / irate(aptos_schemadb_batch_commit_bytes_count[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} {{db_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other Latencies by timer_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$timer_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "repeat": "timer_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_other_timers_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", name=\"$timer_name\"}[1m])/ irate(aptos_storage_other_timers_seconds_count[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Column Family Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name) (aptos_rocksdb_properties{chain_name=~\"$chain_name\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"$cf_name\"})",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "aptos_rocksdb_properties{chain_name=~\"$chain_name\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"$cf_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Structure Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Committed, Synced and Pruned-till Versions",
     "type": "graph",
     "description": "\"Pruned-till\" version is the first version that's readable, but named such for simplicity.\n\n\"Committed\" version is the version on the latest ledger info saved.\n\n\"Synced\" version is the version on the latest transaction saved, it's only different when state-sync is working to catch up with peers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} synced"
      },
      {
       "expr": "aptos_storage_ledger_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} committed"
      },
      {
       "expr": "aptos_storage_pruner_min_readable_state_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} pruned-till"
      }
     ]
    },
    {
     "title": "Next Block Epoch",
     "type": "graph",
     "description": "On the version that wraps up an epoch, the \"next block epoch\" is the current epoch plus one.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_storage_next_block_epoch{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Jellyfish Tree Disk Size vs Calculated Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "aptos_rocksdb_properties{chain_name=~\"$chain_name\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"jellyfish_merkle_node\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} rocksdb"
      },
      {
       "expr": "rate(aptos_schemadb_put_bytes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=\"jellyfish_merkle_node\"}[10m]) / rate(aptos_schemadb_put_bytes_count[10m]) * ignoring(cf_name) ((aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"new_state_nodes\"} - ignoring(type) aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"stale_state_nodes\"}) + 1000000 * (log2(aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"new_state_leaves\"} - ignoring(type) aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"stale_state_leaves\"}) / 2 - 1))",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} calculated"
      }
     ]
    },
    {
     "title": "Number of Accounts vs Internal Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"new_state_leaves\"} - ignoring(type) aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"stale_state_leaves\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} accounts"
      },
      {
       "expr": "aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"new_state_nodes\"} - ignoring(type) aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"stale_state_nodes\"} - ignoring(type) aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"new_state_leaves\"} + ignoring(type) aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"stale_state_leaves\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} internal_nodes"
      }
     ]
    },
    {
     "title": "Avg Column Family Size By Name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg by(cf_name)(aptos_rocksdb_properties{chain_name=~\"$chain_name\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
       "legendFormat": "{{cf_name}}"
      }
     ]
    },
    {
     "title": "Record size (key + value) by Column Family",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg by(cf_name)(irate(aptos_schemadb_put_bytes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])) / avg by(cf_name)(irate(aptos_schemadb_put_bytes_count[1m]))",
       "legendFormat": "{{cf_name}}"
      }
     ]
    },
    {
     "title": "Avg Account Updates per Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"new_state_leaves\"}[1m]) / ignoring(type) irate(aptos_storage_latest_transaction_version[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Avg Events Emits per Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"events_created\"}[1m]) / on(kubernetes_pod_name, kubernetes_pod_name) irate(aptos_storage_latest_transaction_version[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Avg Internal Node Updates per Account Update",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"new_state_nodes\"}[1m]) / ignoring(type) irate(aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"new_state_leaves\"}[1m]) - 1",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transactions per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transactions per save",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m]) / on (kubernetes_pod_name, kubernetes_pod_name) irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", api_name=\"save_transactions\", result=\"Ok\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Restore Status Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job State",
     "type": "graph",
     "description": "Right edge of the graph shows latest state of the restore job and when it entered such state.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "dateTimeAsLocal" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_coordinator_start_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_restore_coordinator_succeed_timestamp_s > aptos_db_restore_coordinator_start_timestamp_s\nunless aptos_db_restore_coordinator_fail_timestamp_s > aptos_db_restore_coordinator_start_timestamp_s\n\n# any restore activity:\nand (rate(aptos_db_restore_epoch_ending_epoch[1m]) > 0 or rate(aptos_db_restore_state_snapshot_leaf_index[1m]) > 0 or rate(aptos_db_restore_transaction_save_version[1m]) > 0 or rate(aptos_db_restore_transaction_replay_version[1m]) > 0) == bool 1",
       "legendFormat": "{{kubernetes_pod_name}} running since"
      },
      {
       "expr": "aptos_db_restore_coordinator_succeed_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_restore_coordinator_start_timestamp_s > aptos_db_restore_coordinator_succeed_timestamp_s\nunless aptos_db_restore_coordinator_fail_timestamp_s > aptos_db_restore_coordinator_succeed_timestamp_s",
       "legendFormat": "{{kubernetes_pod_name}} succeeded since"
      },
      {
       "expr": "aptos_db_restore_coordinator_fail_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_restore_coordinator_start_timestamp_s > aptos_db_restore_coordinator_fail_timestamp_s\nunless aptos_db_restore_coordinator_succeed_timestamp_s > aptos_db_restore_coordinator_fail_timestamp_s",
       "legendFormat": "{{kubernetes_pod_name}} failed since"
      }
     ]
    },
    {
     "title": "Transaction Restore Progress",
     "type": "graph",
     "description": "save: Version of txn being saved without replaying\nreplay: Version of txn being replayed\ntarget: When \"replay\" hits this version, the restore is done.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_transaction_save_version and irate(aptos_db_restore_transaction_save_version[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} saved"
      },
      {
       "expr": "aptos_db_restore_transaction_replay_version and irate(aptos_db_restore_transaction_replay_version[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}}  replayed"
      },
      {
       "expr": "aptos_db_restore_coordinator_target_version and (irate(aptos_db_restore_transaction_save_version[1m]) > 0 or irate(aptos_db_restore_transaction_replay_version[1m]) > 0)",
       "legendFormat": "{{kubernetes_pod_name}} target"
      }
     ]
    },
    {
     "title": "Transaction Restore Progress %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(aptos_db_restore_transaction_save_version and irate(aptos_db_restore_transaction_save_version[1m]) > 0) / aptos_db_restore_coordinator_target_version",
       "legendFormat": "{{kubernetes_pod_name}} saved"
      },
      {
       "expr": "(aptos_db_restore_transaction_replay_version and irate(aptos_db_restore_transaction_replay_version[1m]) > 0) / aptos_db_restore_coordinator_target_version",
       "legendFormat": "{{kubernetes_pod_name}} replayed"
      }
     ]
    },
    {
     "title": "Committed and Synced Versions",
     "type": "graph",
     "description": "\"Committed\" version is the version on the latest ledger info saved.\n\n\"Synced\" version is the version on the latest transaction saved, it's only different when state-sync is working to catch up with peers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"validator|fullnode\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} synced"
      },
      {
       "expr": "aptos_storage_ledger_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"validator|fullnode\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}} committed"
      }
     ]
    },
    {
     "title": "Consensus Current Round",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aptos_consensus_current_round",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Coordinator Activities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Coordinator Heartbeats",
     "type": "graph",
     "description": "When the backup coordinator is live, this shows as a upward trend line.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_backup_service_latency_s_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", endpoint=\"db_state\"} and irate(aptos_backup_service_latency_s_count[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Epoch Ending Backup: Num Taken",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_backup_service_latency_s_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", endpoint=\"epoch_ending_ledger_infos\"} and irate(aptos_backup_service_latency_s_count[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "State Snapsho: Num Taken",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aptos_backup_service_latency_s_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", endpoint=\"state_snapshot\"} and irate(aptos_backup_service_latency_s_count[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transaction Backup: Num Taken",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_backup_service_latency_s_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", endpoint=\"transactions\"} and irate(aptos_backup_service_latency_s_count[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Epoch Ending Backup: Epoch vs Latest Epoch",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_backup_handler_epoch_ending_epoch{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} and irate(aptos_backup_handler_epoch_ending_epoch[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      },
      {
       "expr": "aptos_storage_next_block_epoch{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} and irate(aptos_backup_handler_epoch_ending_epoch[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "State Snapshot: Version vs Latest Version",
     "type": "graph",
     "description": "State version of the snapshot being taken, compared to latest version of the ledger.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_backup_handler_state_snapshot_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}-snapshot"
      },
      {
       "expr": "aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} and aptos_backup_handler_state_snapshot_version",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}-latest"
      }
     ]
    },
    {
     "title": "State snapshot: Progress vs Total Accounts",
     "type": "graph",
     "description": "Note the number of accounts is the latest, not that at specified version.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_backup_handler_state_snapshot_leaf_index{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} + 1 ",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}-progress"
      },
      {
       "expr": "(aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"new_state_leaves\"} - ignoring(type) aptos_storage_ledger{chain_name=~\"$chain_name\", namespace=~\"$namespace\", type=\"stale_state_leaves\"}) and aptos_backup_handler_state_snapshot_leaf_index",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}-total"
      }
     ]
    },
    {
     "title": "State snapshot: accounts per second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_backup_handler_state_snapshot_leaf_index{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transaction Backup: Version vs latest version",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_backup_handler_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} and irate(aptos_backup_handler_transaction_version[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      },
      {
       "expr": "aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} and irate(aptos_backup_handler_transaction_version[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transaction backup: transactions per second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_backup_handler_transaction_version[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Service API Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(aptos_backup_service_sent_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", endpoint=~\"$backup_service_api_name\"}[1m])) by(kubernetes_pod_name, kubernetes_pod_name) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "$backup_service_api_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 109 },
     "repeat": "backup_service_api_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_backup_service_sent_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", endpoint=\"$backup_service_api_name\"}[1m]) and irate(aptos_backup_service_sent_bytes[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}} {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Restore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job State",
     "type": "graph",
     "description": "Right edge of the graph shows latest state of the restore job and when it entered such state.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "dateTimeAsLocal" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_coordinator_start_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_restore_coordinator_succeed_timestamp_s > aptos_db_restore_coordinator_start_timestamp_s\nunless aptos_db_restore_coordinator_fail_timestamp_s > aptos_db_restore_coordinator_start_timestamp_s\n\n# any restore activity:\nand (rate(aptos_db_restore_epoch_ending_epoch[1m]) > 0 or rate(aptos_db_restore_state_snapshot_leaf_index[1m]) > 0 or rate(aptos_db_restore_transaction_save_version[1m]) > 0 or rate(aptos_db_restore_transaction_replay_version[1m]) > 0) == bool 1",
       "legendFormat": "{{kubernetes_pod_name}} running since"
      },
      {
       "expr": "aptos_db_restore_coordinator_succeed_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_restore_coordinator_start_timestamp_s > aptos_db_restore_coordinator_succeed_timestamp_s\nunless aptos_db_restore_coordinator_fail_timestamp_s > aptos_db_restore_coordinator_succeed_timestamp_s",
       "legendFormat": "{{kubernetes_pod_name}} succeeded since"
      },
      {
       "expr": "aptos_db_restore_coordinator_fail_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_restore_coordinator_start_timestamp_s > aptos_db_restore_coordinator_fail_timestamp_s\nunless aptos_db_restore_coordinator_succeed_timestamp_s > aptos_db_restore_coordinator_fail_timestamp_s",
       "legendFormat": "{{kubernetes_pod_name}} failed since"
      }
     ]
    },
    {
     "title": "Epoch Ending Epoch",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_epoch_ending_epoch{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_restore_epoch_ending_epoch[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Epoch Ending Version",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_epoch_ending_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_restore_epoch_ending_version[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "State Snapshot Version",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_state_snapshot_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_restore_state_snapshot_target_leaf_index[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transaction Restore Progress",
     "type": "graph",
     "description": "save: Version of txn being saved without replaying\nreplay: Version of txn being replayed\ntarget: When \"replay\" hits this version, the restore is done.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_restore_transaction_save_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_restore_transaction_save_version[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}} saved"
      },
      {
       "expr": "aptos_db_restore_transaction_replay_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_restore_transaction_replay_version[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}  replayed"
      },
      {
       "expr": "aptos_db_restore_coordinator_target_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and (irate(aptos_db_restore_transaction_save_version[1m]) != 0 or irate(aptos_db_restore_transaction_replay_version[1m]) != 0)",
       "legendFormat": "{{kubernetes_pod_name}} target"
      }
     ]
    },
    {
     "title": "Transaction Restore Progress %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(aptos_db_restore_transaction_save_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_restore_transaction_save_version[1m]) != 0) / aptos_db_restore_coordinator_target_version",
       "legendFormat": "{{kubernetes_pod_name}} saved"
      },
      {
       "expr": "(aptos_db_restore_transaction_replay_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_restore_transaction_replay_version[1m]) != 0) / aptos_db_restore_coordinator_target_version",
       "legendFormat": "{{kubernetes_pod_name}} replayed"
      }
     ]
    },
    {
     "title": "Transaction Save per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_db_restore_transaction_save_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transaction Replay per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_db_restore_transaction_replay_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Verify",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job State",
     "type": "graph",
     "description": "Right edge of the graph shows latest state of the backup-verify job and when it entered such state.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "dateTimeAsLocal" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_coordinator_start_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_backup_verify_coordinator_succeed_timestamp_s > aptos_db_backup_verify_coordinator_start_timestamp_s\nunless aptos_db_backup_verify_coordinator_fail_timestamp_s > aptos_db_backup_verify_coordinator_start_timestamp_s\n\n# any restore activity:\nand (rate(aptos_db_backup_verify_epoch_ending_epoch[1m]) > 0 or rate(aptos_db_backup_verify_state_snapshot_leaf_index[1m]) > 0 or rate(aptos_db_backup_verify_transaction_version[1m]) > 0)",
       "legendFormat": "{{kubernetes_pod_name}} running since"
      },
      {
       "expr": "aptos_db_backup_verify_coordinator_succeed_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_backup_verify_coordinator_start_timestamp_s > aptos_db_backup_verify_coordinator_succeed_timestamp_s\nunless aptos_db_backup_verify_coordinator_fail_timestamp_s > aptos_db_backup_verify_coordinator_succeed_timestamp_s",
       "legendFormat": "{{kubernetes_pod_name}} succeeded since"
      },
      {
       "expr": "aptos_db_backup_verify_coordinator_fail_timestamp_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} * 1000\nunless aptos_db_backup_verify_coordinator_start_timestamp_s > aptos_db_backup_verify_coordinator_fail_timestamp_s\nunless aptos_db_backup_verify_coordinator_succeed_timestamp_s > aptos_db_backup_verify_coordinator_fail_timestamp_s",
       "legendFormat": "{{kubernetes_pod_name}} failed since"
      }
     ]
    },
    {
     "title": "Epoch Ending Epoch",
     "type": "graph",
     "description": "Epoch of the epoch ending LedgerInfo verified",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_epoch_ending_epoch{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_backup_verify_epoch_ending_epoch{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Epoch Ending Version",
     "type": "graph",
     "description": "Version of the epoch ending LedgerInfo verified",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_epoch_ending_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_backup_verify_epoch_ending_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "State Snapshot Version",
     "type": "graph",
     "description": "Version of the state snapshot being verified",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_state_snapshot_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_backup_verify_state_snapshot_leaf_index[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transaction Version",
     "type": "graph",
     "description": "Version of the transaction verified",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aptos_db_backup_verify_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} and irate(aptos_db_backup_verify_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]) != 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Transactions per Second",
     "type": "graph",
     "description": "The speed of transaction verification.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(aptos_db_backup_verify_transaction_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]) > 0",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}