{
 "title": "validator",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(node_process_start_time{}, environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(node_process_start_time{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ValidatorSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Down node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_current_epoch_validators) - (count(rate(aptos_consensus_current_round[10m]) > 0) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Down node %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (count(rate(aptos_consensus_current_round[10m]) > 0) OR on() vector(0)) / quantile(0.67, aptos_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Node not Participating Consensus",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_current_round{environment=~\"$environment\"}[1m]) == 0"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Validator Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{environment=~\"$environment\", container=\"validator\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "time() - container_start_time_seconds{environment=~\"$environment\", container_name=\"validator\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(aptos_connections{environment=~\"$environment\", network_id=\"Validator\", role_type=\"validator\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Committed & Synced Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{environment=~\"$environment\", type=\"committed\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "aptos_state_sync_version{environment=~\"$environment\", type=\"synced\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-synced"
    }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_current_round{environment=~\"$environment\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Committed Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_last_committed_round{environment=~\"$environment\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_last_committed_version{environment=~\"$environment\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Transaction Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "sum without (state) (rate(aptos_consensus_committed_txns_count{environment=~\"$environment\", state=\"failed\", pod=~\"$pod\"}[1m])) / sum without (state) (rate(aptos_consensus_committed_txns_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_txn_commit_latency_sum{environment=~\"$environment\", stage=~\"commit_accepted|commit_rejected\", pod=~\"$pod\"}[1m])/rate(aptos_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted|commit_rejected\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{environment=~\"$environment\", index=\"system_ttl\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Key Manager: Keys Still Fresh (Last Hour)",
   "type": "graph",
   "description": "This panel tracks whether the key manager successfully ran within the last hour and determined if the keys are still fresh. If so, the key manager is healthy and 1 is displayed, otherwise, the key manager is unhealthy and 0 is displayed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    {
     "format": "short",
     "label": "Keys Still Fresh? (Bool: 1 = Yes, 0 = No)"
    }
   ],
   "targets": [
    {
     "expr": "increase(aptos_key_manager_state{environment=~\"$environment\", state=\"keys_still_fresh\", pod=~\"$pod\"}[1h]) > bool 1",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}