{
 "title": "Vault",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Vault Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(vault_route_read_secret__count[1m])",
     "legendFormat": "read secret"
    },
    {
     "expr": "irate(vault_route_update_secret__count[1m])",
     "legendFormat": "update secret"
    },
    {
     "expr": "irate(vault_route_read_transit__count[1m])",
     "legendFormat": "read transit"
    }
   ]
  },
  {
   "title": "Vault Core Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "vault_core_handle_request", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Vault GC Pauses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ns/s" }
   ],
   "targets": [
    {
     "expr": "irate(vault_runtime_total_gc_pause_ns[1m])"
    }
   ]
  },
  {
   "title": "Vault Backend p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vault_dynamodb_get{chain_name=~\"$chain_name\", namespace=~\"$namespace\", quantile=\"0.99\"}",
     "legendFormat": "get"
    },
    {
     "expr": "vault_dynamodb_put{chain_name=~\"$chain_name\", namespace=~\"$namespace\", quantile=\"0.99\"}",
     "legendFormat": "put"
    },
    {
     "expr": "vault_spanner_list{chain_name=~\"$chain_name\", namespace=~\"$namespace\", quantile=\"0.99\"}",
     "legendFormat": "list"
    },
    {
     "expr": "vault_spanner_put{chain_name=~\"$chain_name\", namespace=~\"$namespace\", quantile=\"0.99\"}",
     "legendFormat": "put"
    },
    {
     "expr": "vault_azure_get{chain_name=~\"$chain_name\", namespace=~\"$namespace\", quantile=\"0.99\"}",
     "legendFormat": "get"
    },
    {
     "expr": "vault_azure_put{chain_name=~\"$chain_name\", namespace=~\"$namespace\", quantile=\"0.99\"}",
     "legendFormat": "put"
    }
   ]
  }
 ]
}