# This file is source-d when running Forge
# LEAVE ALL LINES COMMENTED OUT UNLESS FOR TESTING. NEVER LAND THIS WITH VALUES UNCOMMENTED

# FORGE_ENABLE_INDEXER=true
# FORGE_ENABLE_HAPROXY=true
# FORGE_RETAIN_DEBUG_LOGS=true
   
