processed 17 tasks

task 1 'run'. lines 17-22:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2 'run'. lines 24-29:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 4 'run'. lines 48-53:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 5 'run'. lines 55-60:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7 'run'. lines 77-82:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 8 'run'. lines 84-89:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 10 'run'. lines 108-113:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 11 'run'. lines 115-120:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 12 'run'. lines 122-127:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 14 'run'. lines 146-151:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 15 'run'. lines 153-158:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 16 'run'. lines 160-165:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
