processed 12 tasks

task 0 'run'. lines 1-7:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 1 'run'. lines 9-14:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2 'run'. lines 16-21:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 3 'run'. lines 23-28:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 4 'run'. lines 30-35:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 5 'run'. lines 37-45:
Error: Script execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
