ResolutionGraph {
    build_options: BuildConfig {
        dev_mode: true,
        test_mode: false,
    },
    root_package: SourceManifest {
        package: PackageInfo {
            name: "®´∑œ",
            version: (
                0,
                1,
                2,
            ),
            authors: [],
            license: None,
        },
        addresses: None,
        dev_address_assignments: None,
        build: None,
        dependencies: {},
        dev_dependencies: {},
    },
    graph: {
        "®´∑œ": [],
    },
    package_table: {
        "®´∑œ": ResolutionPackage {
            resolution_graph_index: "®´∑œ",
            source_package: SourceManifest {
                package: PackageInfo {
                    name: "®´∑œ",
                    version: (
                        0,
                        1,
                        2,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: None,
                dev_address_assignments: None,
                build: None,
                dependencies: {},
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {},
            resolution_table: {},
            source_digest: "ELIDED_FOR_TEST",
        },
    },
}
