processed 10 tasks

task 3 'view'. lines 13-15:
[No Resource Exists]

task 5 'run'. lines 37-37:
Error: Function execution failed with VMError: VMError { major_status: ABORTED, sub_status: Some(0), message: Some("0x00000000000000000000000000000042::N::ex at offset 1"), location: Module(ModuleId { address: 00000000000000000000000000000042, name: Identifier("N") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 1)] }

task 7 'view'. lines 47-49:
key 0x42::N::R<U64> {
    v: 0
}

task 9 'view'. lines 59-61:
[No Resource Exists]
