processed 9 tasks

task 1 'publish'. lines 12-25:
Error: Unbound struct Self.T

task 2 'publish'. lines 28-41:
Error: Unbound struct Self.T

task 3 'publish'. lines 44-57:
Error: ParserError: Invalid Token: expected Tok::NameValue

task 4 'publish'. lines 60-73:
Error: ParserError: Invalid Token: expected Tok::NameValue

task 5 'run'. lines 76-87:
Error: Unbound struct Self.T

task 6 'run'. lines 90-101:
Error: Unbound struct Self.T

task 7 'run'. lines 104-115:
Error: ParserError: Invalid Token: expected Tok::NameValue

task 8 'run'. lines 118-129:
Error: ParserError: Invalid Token: expected Tok::NameValue
