processed 10 tasks

task 2 'publish'. lines 19-30:
Error: Transaction discarded. VMStatus: status INVALID_AUTH_KEY of type Validation

task 3 'publish'. lines 31-39:
Error: Transaction discarded. VMStatus: status INVALID_AUTH_KEY of type Validation

task 4 'publish'. lines 40-54:
Error: Transaction discarded. VMStatus: status INVALID_AUTH_KEY of type Validation

task 5 'run'. lines 55-63:
Error: Transaction discarded. VMStatus: status INVALID_AUTH_KEY of type Validation

task 6 'run'. lines 64-71:
Error: Transaction discarded. VMStatus: status INVALID_AUTH_KEY of type Validation

task 7 'run'. lines 72-79:
Error: Transaction discarded. VMStatus: status INVALID_AUTH_KEY of type Validation

task 8 'view'. lines 80-85:
key 0x1::DiemAccount::DiemAccount {
    authentication_key: 000000000000000000000000000000004777eb94491650dd3f095ce6f778acb6
    withdraw_capability: copy drop store 0x1::Option::Option<0x1::DiemAccount::WithdrawCapability> {
        vec: [
            store 0x1::DiemAccount::WithdrawCapability {
                account_address: 4777eb94491650dd3f095ce6f778acb6
            },
        ]
    }
    key_rotation_capability: copy drop store 0x1::Option::Option<0x1::DiemAccount::KeyRotationCapability> {
        vec: [
            store 0x1::DiemAccount::KeyRotationCapability {
                account_address: 4777eb94491650dd3f095ce6f778acb6
            },
        ]
    }
    received_events: store 0x1::Event::EventHandle<0x1::DiemAccount::ReceivedPaymentEvent> {
        counter: 0
        guid: drop store 0x1::Event::GUIDWrapper {
            len_bytes: 40u8
            guid: drop store 0x1::GUID::GUID {
                id: copy drop store 0x1::GUID::ID {
                    creation_num: 0
                    addr: 4777eb94491650dd3f095ce6f778acb6
                }
            }
        }
    }
    sent_events: store 0x1::Event::EventHandle<0x1::DiemAccount::SentPaymentEvent> {
        counter: 0
        guid: drop store 0x1::Event::GUIDWrapper {
            len_bytes: 40u8
            guid: drop store 0x1::GUID::GUID {
                id: copy drop store 0x1::GUID::ID {
                    creation_num: 1
                    addr: 4777eb94491650dd3f095ce6f778acb6
                }
            }
        }
    }
    sequence_number: 0
}
