(function() {var implementors = {};
implementors["backup_cli"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"backup_cli/storage/struct.ShellSafeName.html\" title=\"struct backup_cli::storage::ShellSafeName\">ShellSafeName</a>","synthetic":false,"types":["backup_cli::storage::ShellSafeName"]}];
implementors["consensus_types"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"consensus_types/vote_proposal/struct.MaybeSignedVoteProposal.html\" title=\"struct consensus_types::vote_proposal::MaybeSignedVoteProposal\">MaybeSignedVoteProposal</a>","synthetic":false,"types":["consensus_types::vote_proposal::MaybeSignedVoteProposal"]}];
implementors["diem_crypto"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"diem_crypto/hash/struct.HashValue.html\" title=\"struct diem_crypto::hash::HashValue\">HashValue</a>","synthetic":false,"types":["diem_crypto::hash::HashValue"]}];
implementors["diem_fuzzer"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"diem_fuzzer/struct.FuzzTarget.html\" title=\"struct diem_fuzzer::FuzzTarget\">FuzzTarget</a>","synthetic":false,"types":["diem_fuzzer::FuzzTarget"]}];
implementors["diem_json_rpc_types"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"diem_json_rpc_types/views/struct.BytesView.html\" title=\"struct diem_json_rpc_types::views::BytesView\">BytesView</a>","synthetic":false,"types":["diem_json_rpc_types::views::BytesView"]}];
implementors["diem_proptest_helpers"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"diem_proptest_helpers/struct.Index.html\" title=\"struct diem_proptest_helpers::Index\">Index</a>","synthetic":false,"types":["diem_proptest_helpers::Index"]}];
implementors["diem_types"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"enum\" href=\"diem_types/contract_event/enum.ContractEvent.html\" title=\"enum diem_types::contract_event::ContractEvent\">ContractEvent</a>","synthetic":false,"types":["diem_types::contract_event::ContractEvent"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"enum\" href=\"diem_types/ledger_info/enum.LedgerInfoWithSignatures.html\" title=\"enum diem_types::ledger_info::LedgerInfoWithSignatures\">LedgerInfoWithSignatures</a>","synthetic":false,"types":["diem_types::ledger_info::LedgerInfoWithSignatures"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"diem_types/transaction/struct.SignatureCheckedTransaction.html\" title=\"struct diem_types::transaction::SignatureCheckedTransaction\">SignatureCheckedTransaction</a>","synthetic":false,"types":["diem_types::transaction::SignatureCheckedTransaction"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"enum\" href=\"diem_types/transaction/enum.TransactionInfo.html\" title=\"enum diem_types::transaction::TransactionInfo\">TransactionInfo</a>","synthetic":false,"types":["diem_types::transaction::TransactionInfo"]}];
implementors["diem_vm"] = [{"text":"impl&lt;'a, R:&nbsp;MoveResolver&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"diem_vm/read_write_set_analysis/struct.ReadWriteSetAnalysis.html\" title=\"struct diem_vm::read_write_set_analysis::ReadWriteSetAnalysis\">ReadWriteSetAnalysis</a>&lt;'a, R&gt;","synthetic":false,"types":["diem_vm::read_write_set_analysis::ReadWriteSetAnalysis"]}];
implementors["forge"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.56.1/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"enum\" href=\"forge/enum.SwarmDirectory.html\" title=\"enum forge::SwarmDirectory\">SwarmDirectory</a>","synthetic":false,"types":["forge::backend::local::swarm::SwarmDirectory"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()