processed 2 tasks

task 0 'publish'. lines 1-12:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 1 'publish'. lines 14-22:
Error: Unable to publish module '00000000000000000000000000000042::N'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::N,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}
