processed 2 tasks

task 0 'run'. lines 1-6:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 1 'run'. lines 8-13:
Error: Script execution failed with VMError: {
    major_status: NUMBER_OF_SIGNER_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}
