# podman build -t nodejs:test .
FROM docker.io/node:22-bookworm

ENV NETWORK_IP="127.0.0.1"
ENV FAUCET_URL="none"
ENV FULLNODE_URL="none"
ENV CHAIN_ID="1"
ENV APTOS_NETWORK="none"

RUN npm install -g pnpm

COPY ./libvoidstar.so /usr/lib/libvoidstar.so
COPY ./aptos /usr/local/bin/aptos
ENV PATH="/usr/local/bin:$PATH"

COPY ./antithesis-tests/ /opt/antithesis/test/v1/
RUN find /opt/antithesis/ -type f -name "*.sh" -exec chmod +x {} \;

# TODO: Once test client is in a public repo git clone it and install dependencies. We also need anthesis-ts-sdk to be published on NPM.
COPY ./antithesis-ts-test.tar.gz /antithesis-ts-test.tar.gz
RUN tar -xzf /antithesis-ts-test.tar.gz -C /opt/
WORKDIR /opt/antithesis-ts-test
RUN rm -rf node_modules
RUN pnpm install
RUN rm /antithesis-ts-test.tar.gz
WORKDIR /

ENTRYPOINT ["sleep", "infinity"]