ResolutionGraph {
    root_package_path: "tests/test_sources/resolution/one_dep_assigned_address",
    build_options: BuildConfig {
        dev_mode: true,
        test_mode: false,
        generate_docs: false,
        generate_abis: false,
        install_dir: Some(
            "ELIDED_FOR_TEST",
        ),
        force_recompilation: false,
    },
    root_package: SourceManifest {
        package: PackageInfo {
            name: "Root",
            version: (
                0,
                0,
                0,
            ),
            authors: [],
            license: None,
        },
        addresses: None,
        dev_address_assignments: None,
        build: None,
        dependencies: {
            "OtherDep": Dependency {
                local: "./deps_only/other_dep",
                subst: Some(
                    {
                        "A": RenameFrom(
                            "B",
                        ),
                    },
                ),
                version: None,
                digest: None,
                git_info: None,
            },
        },
        dev_dependencies: {},
    },
    graph: {
        "Root": [
            (
                "OtherDep",
                Outgoing,
            ),
        ],
        "OtherDep": [
            (
                "Root",
                Incoming,
            ),
        ],
    },
    package_table: {
        "OtherDep": ResolutionPackage {
            resolution_graph_index: "OtherDep",
            source_package: SourceManifest {
                package: PackageInfo {
                    name: "OtherDep",
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: Some(
                    {
                        "B": Some(
                            00000000000000000000000000000001,
                        ),
                    },
                ),
                dev_address_assignments: None,
                build: None,
                dependencies: {},
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {},
            resolution_table: {
                "B": 00000000000000000000000000000001,
            },
            source_digest: "ELIDED_FOR_TEST",
        },
        "Root": ResolutionPackage {
            resolution_graph_index: "Root",
            source_package: SourceManifest {
                package: PackageInfo {
                    name: "Root",
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: None,
                dev_address_assignments: None,
                build: None,
                dependencies: {
                    "OtherDep": Dependency {
                        local: "./deps_only/other_dep",
                        subst: Some(
                            {
                                "A": RenameFrom(
                                    "B",
                                ),
                            },
                        ),
                        version: None,
                        digest: None,
                        git_info: None,
                    },
                },
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {
                "A": (
                    "OtherDep",
                    "B",
                ),
            },
            resolution_table: {
                "A": 00000000000000000000000000000001,
            },
            source_digest: "ELIDED_FOR_TEST",
        },
    },
}
