{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.validatorServiceAccountName" . }}
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
  {{- if and .Values.azure_genesis_storage.enabled .Values.azure_genesis_storage.workloadIdentityClientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure_genesis_storage.workloadIdentityClientId | quote }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.fullnodeServiceAccountName" . }}
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
  {{- if and .Values.azure_genesis_storage.enabled .Values.azure_genesis_storage.workloadIdentityClientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure_genesis_storage.workloadIdentityClientId | quote }}
  {{- end }}
--- 
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.fullname" . }}-haproxy
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
