name: "Lint+Test"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - devnet
      - testnet
      - mainnet
      - aptos-node-v*
      - aptos-release-v*
  workflow_dispatch:

env:
  HAS_BUILDPULSE_SECRETS: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID != '' && secrets.BUILDPULSE_SECRET_ACCESS_KEY != '' }}
  HAS_DATADOG_SECRETS: ${{ secrets.DD_API_KEY != '' }}
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true
permissions:
  contents: read


jobs:
  file_change_determinator:
    runs-on: 2cpu-gh-ubuntu24-x64
    outputs:
      only_docs_changed: ${{ steps.determine_file_changes.outputs.only_docs_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Run the file change determinator
        id: determine_file_changes
        uses: ./.github/actions/file-change-determinator

  # Run all general lints (i.e., non-rust and docs lints). This is a PR required job.
  general-lints:
    needs: file_change_determinator
    runs-on: 2cpu-gh-ubuntu24-x64
    steps:
      - uses: actions/checkout@v4
        if: needs.file_change_determinator.outputs.only_docs_changed != 'true'
        with:
          fetch-depth: 0 # get all the history because python-lint-tests requires it.
      - name: Run general lints
        uses: ./.github/actions/general-lints
        if: needs.file_change_determinator.outputs.only_docs_changed != 'true'
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      - name: Skip general lints for documentation-only changes
        if: needs.file_change_determinator.outputs.only_docs_changed == 'true'
        run: echo "Skipping general lints for documentation-only changes."

  # Run all rust lints. This is a PR required job.
  rust-lints:
    needs: file_change_determinator
    runs-on: runs-on,cpu=64,family=c7,disk=large,image=aptos-ubuntu-x64,run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
        if: needs.file_change_determinator.outputs.only_docs_changed != 'true'
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - name: Run rust lints
        uses: ./.github/actions/rust-lints
        if: needs.file_change_determinator.outputs.only_docs_changed != 'true'
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      - run: echo "Skipping rust lints! Unrelated changes detected."
        if: needs.file_change_determinator.outputs.only_docs_changed == 'true'

  # Run cargo deny. This is a PR required job.
  rust-cargo-deny:
    needs: file_change_determinator
    runs-on: 2cpu-gh-ubuntu24-x64
    steps:
      - uses: actions/checkout@v4
        if: needs.file_change_determinator.outputs.only_docs_changed != 'true'
      - uses: EmbarkStudios/cargo-deny-action@v2
        if: needs.file_change_determinator.outputs.only_docs_changed != 'true'
        with:
          command: check licenses
      - run: echo "Skipping cargo deny! Unrelated changes detected."
        if: needs.file_change_determinator.outputs.only_docs_changed == 'true'

  # Check the freshness of the merge base. This is a PR required job.
  rust-check-merge-base:
    if: | # Don't run on release branches
      (
        !contains(github.event.pull_request.base.ref, '-release-')
      )
    needs: file_change_determinator
    runs-on: runs-on,cpu=64,family=c7,disk=large,image=aptos-ubuntu-x64,run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Fetch all git history for accurate target determination
      - name: Run the merge base freshness check
        uses: ./.github/actions/rust-check-merge-base
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          BASE_REF: origin/${{ github.base_ref || 'main' }}

  # Run only the targeted rust unit tests. This is a PR required job.
  rust-targeted-unit-tests:
    if: | # Don't run on release branches. Instead, all unit tests will be triggered.
      (
        !contains(github.event.pull_request.base.ref, '-release-')
      )
    needs: file_change_determinator
    runs-on: runs-on,cpu=64,family=c7,disk=large,image=aptos-ubuntu-x64,run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Fetch all git history for accurate target determination

      - name: Run dev_setup.sh
        run: |
          scripts/dev_setup.sh -b -p -r -y -P -t

      - name: Run targeted rust unit tests
        uses: ./.github/actions/rust-targeted-unit-tests
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          DETERMINATOR_MODE: ${{ vars.APTOS_TEST_DETERMINATOR || 'legacy' }}
          BASE_REF: origin/${{ github.base_ref || 'main' }}

  # Run all rust unit tests. This is not a PR required job.
  rust-unit-tests:
    if: | # Only run when an appropriate event occurs
      (
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'push' ||
        contains(github.event.pull_request.base.ref, '-release-')
      )
    runs-on: runs-on,cpu=64,family=c7,disk=large,image=aptos-ubuntu-x64,run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      # Install Move Prover tools
      - name: Run dev_setup.sh
        run: |
          scripts/dev_setup.sh -b -y
      - name: Run rust unit tests
        uses: ./.github/actions/rust-unit-tests
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          TRUNK_API_TOKEN: ${{ secrets.TRUNK_API_TOKEN }}
