# This workflow runs periodically to delete obsolete workflow runs of workflows that don't exist anymore in the repo.
# This is the keep the Workflow list on the left here https://github.com/aptos-labs/aptos-core/actions tidy.
# The only way to remove a workflow from that list is to delete _all_ runs of a workflow.
name: Prune old workflow runs
on:
  workflow_dispatch:
  # schedule: # NOTE: the schedule is dictated by PIES

permissions:
  actions: write

jobs:
  prune:
    if: github.repository == 'aptos-labs/aptos-core'
    runs-on: 2cpu-gh-ubuntu24-x64
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - run: pnpm i && pnpm pruneGithubWorkflowRuns
        env:
          GITHUB_TOKEN: ${{ github.token }}
        working-directory: .github/ts-tasks
