Move prover returns: exiting with boogie verification errors
warning: Failed to instantiate all type parameters in this global invariant
   ┌─ tests/sources/regression/mono_after_global_invariant.move:44:9
   │
10 │           move_to(s, B {});
   │           ------- When instrumenting the global invariant here
   ·
44 │ ╭         invariant<T> update
45 │ │             Base::has_b() ==> (has_r<T>() ==> old(has_r<T>()));
   │ ╰───────────────────────────────────────────────────────────────^

error: global memory invariant does not hold
   ┌─ tests/sources/regression/mono_after_global_invariant.move:44:9
   │
44 │ ╭         invariant<T> update
45 │ │             Base::has_b() ==> (has_r<T>() ==> old(has_r<T>()));
   │ ╰───────────────────────────────────────────────────────────────^
   │
   =     at tests/sources/regression/mono_after_global_invariant.move:30: put_r
   =         s = <redacted>
   =         v = <redacted>
   =     at tests/sources/regression/mono_after_global_invariant.move:31: put_r
   =     at tests/sources/regression/mono_after_global_invariant.move:9: put_b
   =         s = <redacted>
   =     at tests/sources/regression/mono_after_global_invariant.move:10: put_b
   =     at tests/sources/regression/mono_after_global_invariant.move:14: put_b
   =     at tests/sources/regression/mono_after_global_invariant.move:32: put_r
   =     at tests/sources/regression/mono_after_global_invariant.move:30: put_r
   =     at tests/sources/regression/mono_after_global_invariant.move:32: put_r
   =     at tests/sources/regression/mono_after_global_invariant.move:44
