CompiledPackageInfo {
    package_name: "test",
    address_alias_instantiation: {},
    module_resolution_metadata: {},
    source_digest: Some(
        "ELIDED_FOR_TEST",
    ),
    build_flags: BuildConfig {
        dev_mode: true,
        test_mode: false,
        generate_docs: false,
        generate_abis: false,
        install_dir: Some(
            "ELIDED_FOR_TEST",
        ),
        force_recompilation: false,
    },
}
